Repository antvis/L7, pull requests merged in 2019-11, with the labels that each got.

#56 fix: locale json
  site/locale.json
Labels: PR: reviewed-changes-requested, bug

#58 fix: gatsby site examples
  .gitignore
  babel.config.js
  examples/point/chartmap/demo/chart.js
  gatsby-browser.js
  gatsby-node.js
  package-lock.json
  package.json
  yarn.lock
Labels: PR: unreviewed, bug

#61 fix: duplicated gatsby config
  gatsby-config.js
Labels: PR: reviewed-changes-requested, bug

#68 fix git push --set-upstream origin next_tmp
  .cache/redirects.json
  .cache/redux.state
  docs/api/component/control.en.md
  docs/api/component/control.zh.md
  docs/api/component/marker.en.md
  docs/api/component/marker.zh.md
  docs/api/component/popup.en.md
  docs/api/component/popup.zh.md
  docs/api/l7.en.md
  docs/api/l7.zh.md
  docs/api/layer/heatmap.en.md
  docs/api/layer/heatmap.zh.md
  docs/api/layer/imagelayer.en.md
  docs/api/layer/imagelayer.zh.md
  docs/api/layer/layer.en.md
  docs/api/layer/layer.zh.md
  docs/api/layer/linelayer.en.md
  docs/api/layer/linelayer.zh.md
  docs/api/layer/pointlayer.en.md
  docs/api/layer/pointlayer.zh.md
  docs/api/layer/polygonlayer.en.md
  docs/api/layer/polygonlayer.zh.md
  docs/api/quickstart.en.md
  docs/api/quickstart.zh.md
  docs/api/scene.en.md
  docs/api/scene.zh.md
  docs/api/source/geojson.en.md
  docs/api/source/geojson.zh.md
  docs/api/source/source.en.md
  docs/api/source/source.zh.md
  packages/component/src/css/l7.css
  site/pages/index.zh.tsx
Labels: PR: unreviewed

#67 🚀 l7.antv.vision
  gatsby-config.js
  package.json
Labels: PR: unreviewed

#75 fix(babel): gatsby env
  babel.config.js
  package.json
  packages/l7/es/index.js
  packages/l7/es/index.js.map
Labels: PR: reviewed-changes-requested, bug

#72 test: improve travis ci
  .travis.yml
  .yarnrc
  README.md
  README.zh.md
  babel.config.js
  docs/api/l7.en.md
  docs/api/l7.zh.md
  package.json
  packages/renderer/src/regl/__tests__/model.spec.ts
Labels: PR: unreviewed, test

#81 Fix site
  .gitignore
  docs/manual/tutorial/data.en.md
  docs/tutorial/data.en.md
  gatsby-config.js
  packages/l7/.gitignore
  site/css/home.css
  site/locale.json
  site/pages/index.zh.tsx
Labels: PR: reviewed-changes-requested

#82 Update home page slogan
  site/locale.json
  site/pages/index.zh.tsx
Labels: PR: unreviewed

#83 add tutorial map docs
  .cache/redirects.json
  .cache/redux.state
  .gitignore
  docs/manual/tutorial/data.en.md
  docs/manual/tutorial/data.zh.md
  docs/manual/tutorial/map/amap.md
  docs/manual/tutorial/quickstart.en.md
  docs/manual/tutorial/quickstart.zh.md
  docs/tutorial/map/amap.en.md
  docs/tutorial/map/amap.zh.md
  docs/tutorial/map/mapbox.en.md
  docs/tutorial/map/mapbox.zh.md
  docs/tutorial/quickstart.en.md
  docs/tutorial/quickstart.zh.md
  gatsby-config.js
  jest.config.js
  package.json
  packages/core/src/services/scene/SceneService.ts
  packages/core/src/utils/dom.ts
  packages/l7/.gitignore
  packages/l7/package_bak.json
  packages/layers/src/line/shaders/line_arc2d_vert.glsl
  packages/maps/src/amap/index.ts
  yarn.lock
Labels: PR: unreviewed

#88 docs(docs): add 1.x 版本的介绍
  docs/api/l7.zh.md
  docs/api/l7stable.en.md
  docs/api/l7stable.zh.md
  docs/api/scene.en.md
  docs/api/scene.zh.md
  docs/tutorial/map/amap.en.md
  docs/tutorial/map/amap.zh.md
  docs/tutorial/map/mapbox.en.md
  docs/tutorial/map/mapbox.zh.md
  docs/tutorial/quickstart.en.md
  gatsby-config.js
Labels: PR: reviewed-changes-requested

#91 docs(example): fix example md
  .travis.yml
  docs/tutorial/data.en.md
  examples/heatmap/grid/index.zh.md
  examples/heatmap/heatmap/index.zh.md
  examples/heatmap/hexagon/index.zh.md
  examples/line/isoline/index.zh.md
  examples/line/path/index.zh.md
  examples/point/chart/index.zh.md
  examples/point/column/index.zh.md
  examples/point/image/index.zh.md
  examples/point/marker/index.zh.md
  examples/point/scatter/index.zh.md
  examples/polygon/3d/index.zh.md
  examples/polygon/fill/index.zh.md
  examples/raster/basic/index.zh.md
  package.json
  yarn.lock
Labels: PR: unreviewed, documentation

#97 docs(readme): update en readme
  README.md
  README.zh-CN.md
Labels: PR: unreviewed, documentation

#99 docs(api): update setMapStyle API fix:#98
  docs/api/component/control.zh.md
  docs/api/component/marker.en.md
  docs/api/scene.en.md
  docs/api/scene.zh.md
  docs/tutorial/quickstart.en.md
  docs/tutorial/quickstart.zh.md
Labels: PR: unreviewed, documentation

#103 Fix(component): marker
  docs/api/layer/layer.en.md
  docs/api/layer/layer.zh.md
  docs/tutorial/map/mapbox.zh.md
  docs/tutorial/quickstart.en.md
  docs/tutorial/quickstart.zh.md
  examples/point/chart/demo/bar.js
  examples/point/chart/demo/chart.js
  examples/point/chart/demo/ring.js
  examples/point/marker/demo/marker.js
  examples/tutorial/marker/demo/amap.js
  packages/component/package.json
  packages/core/package.json
  packages/core/src/services/component/MarkerService.ts
  packages/l7/package.json
  packages/layers/package.json
  packages/maps/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/utils/package.json
  stories/Components/components/Marker.tsx
  stories/Components/components/Popup.tsx
  stories/Components/components/Scale.tsx
  stories/Components/components/Zoom.tsx
Labels: Fix, PR: reviewed-changes-requested, PR: unreviewed

#104 docs(docs): fix docs error
  docs/tutorial/map/amap.en.md
  docs/tutorial/map/amap.zh.md
  docs/tutorial/map/mapbox.en.md
  docs/tutorial/map/mapbox.zh.md
  docs/tutorial/quickstart.en.md
  docs/tutorial/quickstart.zh.md
  packages/layers/src/point/shaders/extrude_vert.glsl
Labels: PR: unreviewed, documentation

#105 docs(docs): update 2.x version
  docs/tutorial/map/amap.en.md
  docs/tutorial/map/amap.zh.md
  docs/tutorial/map/mapbox.en.md
  docs/tutorial/map/mapbox.zh.md
  docs/tutorial/quickstart.en.md
  docs/tutorial/quickstart.zh.md
Labels: PR: unreviewed, documentation

#106 fix(map): temporarily closed amap offset coordinate
  .storybook/webpack.config.js
  packages/component/src/control/BaseControl.ts
  packages/core/src/shaders/projection.glsl
  packages/maps/src/amap/index.ts
  stories/Layers/Layers.stories.tsx
  stories/Layers/components/column.tsx
Labels: PR: unreviewed, bug

#108 chore(version): update docs demo version
  docs/api/l7stable.en.md
  docs/api/l7stable.zh.md
  docs/tutorial/map/amap.en.md
  docs/tutorial/map/amap.zh.md
  docs/tutorial/map/mapbox.en.md
  docs/tutorial/map/mapbox.zh.md
  docs/tutorial/quickstart.en.md
  docs/tutorial/quickstart.zh.md
  gatsby-config.js
Labels: PR: reviewed-changes-requested, chore

#107 Update README.md
  README.md
Labels: PR: unreviewed

#109 修复 Windows 环境开发问题
  .github/CONTRIBUTING.md
  .travis.yml
  README.md
  README.zh-CN.md
  jest.config.js
  package.json
  stories/Components/components/Popup.tsx
  yarn.lock
Labels: PR: unreviewed

#110 Update version
  docs/tutorial/map/amap.en.md
  docs/tutorial/map/amap.zh.md
  docs/tutorial/map/mapbox.en.md
  docs/tutorial/map/mapbox.zh.md
  docs/tutorial/quickstart.en.md
  docs/tutorial/quickstart.zh.md
  package.json
Labels: PR: unreviewed
