Repository antvis/L7, pull requests merged in 2019-12, with the labels that each got.

#113 build(babel): transpile according to browserslist, add `core-js`
  babel.config.js
  package.json
  yarn.lock
Labels: PR: reviewed-changes-requested, build

#116 docs: update l7 cdn version
  docs/tutorial/map/amap.en.md
  docs/tutorial/map/amap.zh.md
  docs/tutorial/map/blankmap.en.md
  docs/tutorial/map/blankmap.zh.md
  docs/tutorial/map/mapbox.en.md
  docs/tutorial/map/mapbox.zh.md
  docs/tutorial/quickstart.en.md
  docs/tutorial/quickstart.zh.md
Labels: PR: unreviewed, documentation

#118 docs: update add prettier readme
  CHANGELOG.md
  LICENSE.md
  README.md
  README.zh-CN.md
  package.json
Labels: PR: unreviewed, documentation

#117 Source
  .gitignore
  .storybook/addons.ts
  .storybook/config.ts
  .storybook/webpack.config.js
  docs/api/source/geojson.en.md
  docs/api/source/geojson.zh.md
  docs/api/source/json.en.md
  docs/api/source/json.zh.md
  docs/api/source/source.en.md
  docs/api/source/source.zh.md
  docs/tutorial/map/blankmap.en.md
  docs/tutorial/map/blankmap.zh.md
  examples/tutorial/data/demo/data_update.js
  examples/tutorial/data/demo/meta.json
  package.json
  packages/core/package.json
  packages/core/src/services/config/ConfigService.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/layer/IStyleAttributeService.ts
  packages/core/src/services/layer/LayerService.ts
  packages/core/src/services/layer/StyleAttribute.ts
  packages/core/src/services/layer/StyleAttributeService.ts
  packages/core/src/services/log/LogService.ts
  packages/core/src/services/renderer/IElements.ts
  packages/core/src/services/renderer/IModel.ts
  packages/core/src/services/scene/SceneService.ts
  packages/core/src/services/source/ISourceService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/core/BaseModel.ts
  packages/layers/src/plugins/DataMappingPlugin.ts
  packages/layers/src/plugins/DataSourcePlugin.ts
  packages/layers/src/plugins/FeatureScalePlugin.ts
  packages/layers/src/plugins/RegisterStyleAttributePlugin.ts
  packages/layers/src/plugins/ShaderUniformPlugin.ts
  packages/layers/src/plugins/UpdateStyleAttributePlugin.ts
  packages/layers/src/point/index.ts
  packages/layers/src/point/models/fill.ts
  packages/maps/src/amap/index.ts
  packages/maps/src/mapbox/theme.ts
  packages/renderer/src/regl/index.ts
  packages/source/__tests__/data/point.ts
  packages/source/__tests__/source.spec.ts
  packages/source/src/source.ts
  packages/source/src/utils/statistics.ts
  packages/source/src/utils/util.ts
  packages/utils/src/dom.ts
  stories/Layers/Layers.stories.tsx
  stories/Layers/components/Point.tsx
  stories/Layers/components/Point3D.tsx
  stories/Layers/components/data_update.tsx
  tsconfig.json
  tslint.prod.json
  tslint.test.json
Labels: PR: unreviewed

#120 docs: 🔍 Add algolia docsearchOptions
  gatsby-config.js
  package.json
Labels: PR: reviewed-changes-requested, documentation

#119 Source
  .gitignore
  docs/api/layer/pointlayer.zh.md
  docs/api/source/csv.en.md
  docs/api/source/csv.zh.md
  docs/api/source/image.en.md
  docs/api/source/image.zh.md
  docs/api/source/json.en.md
  docs/api/source/json.zh.md
  docs/api/source/source.en.md
  docs/api/source/source.zh.md
  docs/tutorial/quickstart.zh.md
  examples/point/chart/demo/ring.js
  packages/core/src/services/component/MarkerService.ts
  packages/core/src/services/config/ConfigService.ts
  packages/core/src/services/interaction/IInteractionService.ts
  packages/core/src/services/interaction/InteractionService.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/renderer/passes/PixelPickingPass.ts
  packages/core/src/services/source/ISourceService.ts
  packages/l7/package.json
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/heatmap/models/hexagon.ts
  packages/layers/src/index.ts
  packages/layers/src/plugins/DataMappingPlugin.ts
  packages/layers/src/plugins/DataSourcePlugin.ts
  packages/layers/src/plugins/LayerStylePlugin.ts
  packages/layers/src/plugins/PixelPickingPlugin.ts
  packages/layers/src/utils/color.ts
  packages/source/__tests__/source.spec.ts
  packages/source/src/index.ts
  packages/source/src/source.ts
  packages/source/src/transform/filter.ts
  packages/source/src/transform/join.ts
  packages/source/src/transform/map.ts
  stories/Components/Components.stories.tsx
  stories/Components/components/chart.tsx
  stories/Layers/Layers.stories.tsx
  stories/Layers/components/HeatmapGrid.tsx
  stories/Layers/components/Point.tsx
  stories/Picking/components/AdvancedAPI.tsx
Labels: PR: unreviewed

#122 fix(doc): fix typo
  docs/api/source/image.zh.md
Labels: PR: unreviewed, bug

#128 fix(mapbox): 针对传递 mapInstance 时，一些参数判断问题。
  packages/maps/src/mapbox/index.ts
Labels: PR: reviewed-changes-requested, bug

#129 fix(doc): remove duplicated method
  docs/api/scene.en.md
  docs/api/scene.zh.md
Labels: PR: unreviewed, bug

#132 Animate
  babel.config.js
  docs/api/layer/point_layer/marker.zh.md
  docs/api/layer/point_layer/symbol.zh.md
  docs/api/map.en.md
  docs/api/map.zh.md
  docs/tutorial/map/blankmap.en.md
  docs/tutorial/map/blankmap.zh.md
  examples/gallery/basic/demo/bus_dark.js
  examples/line/path/demo/bus_dark.js
  examples/line/path/demo/bus_light.js
  package.json
  packages/component/package.json
  packages/core/package.json
  packages/core/src/services/config/ConfigService.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/layers/package.json
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/core/BaseModel.ts
  packages/layers/src/heatmap/index.ts
  packages/layers/src/line/dash.ts
  packages/layers/src/line/index.ts
  packages/layers/src/line/models/line.ts
  packages/layers/src/line/shaders/line_dash_vert.glsl
  packages/layers/src/point/index.ts
  packages/layers/src/point/models/image.ts
  packages/layers/src/point/models/normal.ts
  packages/layers/src/polygon/index.ts
  packages/layers/src/raster/image.ts
  packages/maps/package.json
  packages/maps/src/amap/index.ts
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/utils/package.json
  stories/Layers/Layers.stories.tsx
  stories/Layers/components/Point.tsx
  stories/Layers/components/dash.tsx
  stories/Layers/components/light.tsx
  yarn.lock
Labels: PR: unreviewed

#135 fix(doc): add Scale example
  docs/api/component/control.zh.md
Labels: PR: unreviewed, bug

#136 Example
  build/rollup.config.js
  examples/gallery/basic/demo/meta.json
  examples/gallery/basic/index.en.md
  examples/gallery/basic/index.zh.md
  examples/gallery/index.en.md
  examples/gallery/index.zh.md
  examples/line/line/demo/isoline.js
  examples/point/bubble/demo/meta.json
  examples/point/bubble/demo/scatter.js
  examples/point/image/demo/meta.json
  examples/tutorial/data/demo/data_update.js
  examples/tutorial/map/demo/amapInstance.js
  examples/tutorial/map/demo/meta.json
  gatsby-config.js
  package.json
  packages/component/package.json
  packages/core/package.json
  packages/core/src/services/asset/FontService.ts
  packages/core/src/services/config/ConfigService.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/scene/SceneService.ts
  packages/l7/package.json
  packages/layers/package.json
  packages/layers/src/citybuliding/building.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/core/BaseModel.ts
  packages/layers/src/core/triangulation.ts
  packages/layers/src/heatmap/index.ts
  packages/layers/src/index.ts
  packages/layers/src/line/index.ts
  packages/layers/src/plugins/LayerAnimateStylePlugin.ts
  packages/layers/src/plugins/LayerStylePlugin.ts
  packages/layers/src/plugins/UpdateModelPlugin.ts
  packages/layers/src/point/index.ts
  packages/layers/src/point/models/extrude.ts
  packages/layers/src/point/models/image.ts
  packages/layers/src/point/models/text.ts
  packages/layers/src/point/shaders/text_vert.glsl
  packages/layers/src/polygon/index.ts
  packages/layers/src/polygon/models/index.ts
  packages/layers/src/utils/collision-index.ts
  packages/layers/src/utils/geo.ts
  packages/layers/src/utils/grid-index.ts
  packages/layers/src/utils/symbol-layout.ts
  packages/maps/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/utils/package.json
  stories/Components/components/Zoom.tsx
  stories/Layers/components/Text.tsx
  yarn.lock
Labels: PR: unreviewed
