Repository antvis/L7, pull requests merged in 2020-01, with the labels that each got.

#141 Docs
  CHANGELOG.md
  babel.config.js
  docs/api/layer/cityBuilding.en.md
  docs/api/layer/cityBuilding.zh.md
  docs/api/layer/line_layer/arc.zh.md
  docs/api/layer/line_layer/path.zh.md
  docs/api/layer/point_layer/bubble.zh.md
  docs/api/layer/polygon_layer/extrude.zh.md
  docs/api/layer/polygon_layer/fill.zh.md
  docs/api/map.zh.md
  gatsby-config.js
  lerna.json
  package.json
  packages/component/CHANGELOG.md
  packages/component/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/core/src/services/layer/IStyleAttributeService.ts
  packages/l7/CHANGELOG.md
  packages/l7/package.json
  packages/layers/CHANGELOG.md
  packages/layers/package.json
  packages/layers/src/point/models/fill.ts
  packages/layers/src/point/shaders/fill_frag.glsl
  packages/maps/CHANGELOG.md
  packages/maps/package.json
  packages/renderer/CHANGELOG.md
  packages/renderer/package.json
  packages/scene/CHANGELOG.md
  packages/scene/package.json
  packages/source/CHANGELOG.md
  packages/source/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
  tsconfig.json
  yarn.lock
Labels: PR: unreviewed

#143 docs: fix home page unexpected scrollbar
  site/pages/index.zh.tsx
Labels: PR: unreviewed, documentation

#145 feat: add raster layer
  docs/api/layer/point_layer/cluster.zh.md
  docs/api/map.en.md
  docs/api/map.zh.md
  docs/api/source/json.zh.md
  examples/raster/basic/demo/raster.js
  packages/core/src/services/config/ConfigService.ts
  packages/core/src/services/config/__tests__/schema.spec.ts
  packages/core/src/services/config/mapConfigSchema.ts
  packages/core/src/services/config/warnInfo.ts
  packages/core/src/services/map/IMapService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/core/BaseModel.ts
  packages/layers/src/image/index.ts
  packages/layers/src/image/models/image.ts
  packages/layers/src/image/models/index.ts
  packages/layers/src/image/shaders/image_frag.glsl
  packages/layers/src/image/shaders/image_vert.glsl
  packages/layers/src/index.ts
  packages/layers/src/raster/image.ts
  packages/layers/src/raster/index.ts
  packages/layers/src/raster/models/index.ts
  packages/layers/src/raster/models/raster.ts
  packages/layers/src/raster/raster.ts
  packages/layers/src/raster/shaders/raster_2d_frag.glsl
  packages/maps/src/amap/index.ts
  packages/renderer/src/regl/index.ts
  stories/Layers/components/RasterImage.tsx
  stories/Layers/components/RasterLayer.tsx
Labels: PR: unreviewed, enhancement

#146 feat: marker 支持鼠标事件
  docs/api/component/marker.zh.md
  docs/api/layer/line_layer/linelayer.zh.md
  examples/gallery/basic/demo/animate.js
  examples/gallery/basic/demo/build.js
  examples/gallery/basic/demo/meta.json
  examples/line/path/demo/meta.json
  examples/line/path/demo/road_dark_dash.js
  examples/raster/basic/demo/dem.js
  examples/raster/basic/demo/light.js
  examples/raster/basic/demo/meta.json
  examples/raster/basic/demo/ndvi.js
  packages/component/src/css/l7.css
  packages/component/src/marker.ts
  packages/core/src/services/scene/ISceneService.ts
  packages/core/src/services/scene/SceneService.ts
  packages/layers/src/citybuliding/shaders/build_frag.glsl
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/line/shaders/line_frag.glsl
  packages/scene/src/index.ts
  stories/Components/components/Marker.tsx
Labels: PR: unreviewed, enhancement

#154 set data
  README.md
  README.zh-CN.md
  docs/api/scene.zh.md
  examples/gallery/animate/demo/world.js
  examples/gallery/animate/demo/world2.js
  packages/core/src/services/component/IMarkerService.ts
  packages/core/src/services/component/MarkerService.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/layer/LayerService.ts
  packages/core/src/services/map/IMapService.ts
  packages/maps/src/amap/index.ts
  packages/maps/src/mapbox/index.ts
  packages/scene/src/index.ts
  stories/Layers/components/data_update.tsx
Labels: PR: unreviewed

#157 chore: 测试用例jest-electron 环境 & 修复一些文档问题
  .travis.yml
  docs/api/layer/heatmap_layer/grid.en.md
  docs/api/layer/heatmap_layer/grid.zh.md
  docs/api/layer/heatmap_layer/hexagon.en.md
  docs/api/layer/heatmap_layer/hexagon.zh.md
  docs/api/layer/heatmap_layer/normal.en.md
  docs/api/layer/heatmap_layer/normal.zh.md
  examples/tutorial/control/demo/amap.js
  jest.config.js
  package.json
  packages/component/src/control/layer.ts
  packages/component/src/css/l7.css
  packages/core/src/services/log/LogService.ts
  packages/core/src/shaders/projection.glsl
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/point/shaders/extrude_vert.glsl
  packages/layers/src/point/shaders/fill_vert.glsl
  packages/layers/src/point/shaders/normal_vert.glsl
  packages/maps/src/amap/index.ts
  packages/scene/__tests__/index.spec.ts
  stories/Components/components/Marker.tsx
  stories/Layers/components/column.tsx
  yarn.lock
Labels: PR: unreviewed, chore

#161 fix: 修复图层高亮不正常显示的问题 fix #150
  README.md
  README.zh-CN.md
  demos/raster/basic/demo/image.js
  demos/tutorial/data/demo/line.js
  docs/api/layer/heatmap_layer/grid.en.md
  docs/api/layer/heatmap_layer/grid.zh.md
  docs/api/layer/heatmap_layer/hexagon.en.md
  docs/api/layer/heatmap_layer/hexagon.zh.md
  docs/api/source/csv.en.md
  docs/api/source/csv.zh.md
  docs/api/source/json.en.md
  docs/api/source/json.zh.md
  docs/api/source/source.zh.md
  packages/core/src/services/config/ConfigService.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/layer/LayerService.ts
  packages/core/src/services/renderer/passes/PixelPickingPass.ts
  packages/core/src/shaders/picking.frag.glsl
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/plugins/LayerStylePlugin.ts
  packages/layers/src/plugins/PixelPickingPlugin.ts
  packages/renderer/src/regl/ReglModel.ts
  stories/Components/components/Scale.tsx
  stories/Layers/components/Arcline.tsx
Labels: PR: unreviewed, bug

#164 docs: 增加图层高亮教程
  docs/api/layer/layer.zh.md
  docs/tutorial/demo.zh.md
  docs/tutorial/interactive/hightlight.en.md
  docs/tutorial/interactive/hightlight.zh.md
  docs/tutorial/map/offline.en.md
  docs/tutorial/map/offline.zh.md
Labels: PR: unreviewed, documentation

#165 fix: 修复数据更新方法
  babel.config.js
  examples/gallery/animate/demo/world.js
  examples/gallery/animate/demo/world2.js
  package.json
  packages/component/src/marker.ts
  packages/core/src/services/config/IConfigService.ts
  packages/core/src/services/layer/LayerService.ts
  packages/core/src/services/log/LogService.ts
  packages/core/src/services/map/IMapService.ts
  packages/core/src/services/scene/SceneService.ts
  packages/core/src/services/source/ISourceService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/plugins/DataSourcePlugin.ts
  packages/maps/src/BaseMapWrapper.ts
  packages/maps/src/amap/index.ts
  packages/scene/src/index.ts
  packages/source/src/source.ts
  stories/Components/components/chart.tsx
  stories/Layers/components/Point.tsx
  stories/MapAdaptor/components/MapInstance.tsx
  stories/MapAdaptor/components/Mapbox.tsx
  stories/MapAdaptor/components/amapInstance.tsx
  yarn.lock
Labels: PR: reviewed-changes-requested, bug

#168 chore: add buildmodels plugin
  docs/api/component/marker.zh.md
  docs/api/component/popup.en.md
  docs/api/component/popup.zh.md
  docs/api/layer/layer.en.md
  docs/api/layer/layer.zh.md
  docs/tutorial/data.en.md
  docs/tutorial/data.zh.md
  gatsby-config.js
  package.json
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/log/LogService.ts
  packages/core/src/services/scene/SceneService.ts
  packages/layers/src/citybuliding/building.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/heatmap/index.ts
  packages/layers/src/image/index.ts
  packages/layers/src/index.ts
  packages/layers/src/line/index.ts
  packages/layers/src/plugins/DataMappingPlugin.ts
  packages/layers/src/plugins/DataSourcePlugin.ts
  packages/layers/src/plugins/LayerModelPlugin.ts
  packages/layers/src/plugins/LayerStylePlugin.ts
  packages/layers/src/point/index.ts
  packages/layers/src/polygon/index.ts
  packages/layers/src/raster/image.ts
  packages/layers/src/raster/index.ts
  packages/layers/src/raster/raster.ts
  packages/layers/src/raster/raster2d.ts
  packages/maps/src/amap/index.ts
  packages/source/src/parser/geojson.ts
  stories/Components/components/Zoom.tsx
  stories/Layers/components/Arcline.tsx
  stories/Layers/components/HeatMap.tsx
  stories/Layers/components/data_update.tsx
  stories/MapAdaptor/components/MultiAMap.tsx
  yarn.lock
Labels: PR: unreviewed, chore

#169 docs: update layer docs
  docs/api/component/marker.zh.md
  docs/api/component/popup.en.md
  docs/api/component/popup.zh.md
  docs/api/layer/layer.en.md
  docs/api/layer/layer.zh.md
Labels: PR: unreviewed, documentation

#171 Image
  .storybook/main.js
  .storybook/webpack.config.js
  docs/api/component/marker.zh.md
  docs/api/component/markerLayer.zh.md
  docs/api/component/popup.zh.md
  docs/api/layer/point_layer/cluster.zh.md
  docs/api/source/source.en.md
  docs/api/source/source.zh.md
  examples/point/marker/demo/clustermarker.js
  package.json
  packages/component/src/marker.ts
  packages/component/src/popup.ts
  packages/core/src/inversify.config.ts
  packages/core/src/services/component/IMarkerService.ts
  packages/core/src/services/component/IPopupService.ts
  packages/core/src/services/component/PopupService.ts
  packages/core/src/services/scene/SceneService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/core/BaseModel.ts
  packages/layers/src/point/models/image.ts
  packages/layers/src/point/shaders/image_frag.glsl
  packages/layers/src/point/shaders/image_vert.glsl
  packages/layers/src/point/shaders/text_frag.glsl
  packages/layers/src/point/shaders/text_vert.glsl
  packages/utils/src/dom.ts
  stories/Components/components/Marker.tsx
  stories/Layers/components/PointImage.tsx
  stories/Layers/components/Text.tsx
  stories/MapAdaptor/Map.stories.tsx
  stories/MapAdaptor/components/MultiAMap.tsx
  stories/MapAdaptor/components/image/icon.svg
  stories/MapAdaptor/components/multiMaptest.tsx
  yarn.lock
Labels: PR: unreviewed

#173 Fix line
  docs/api/component/popup.en.md
  docs/api/component/popup.zh.md
  packages/component/src/popup.ts
  packages/core/src/services/layer/StyleAttributeService.ts
  packages/layers/src/utils/polylineNormal.ts
  stories/Source/components/multiPolygon.tsx
  yarn.lock
Labels: PR: reviewed-changes-requested

#175 fix: hightlight opacity
  packages/core/src/shaders/picking.frag.glsl
  stories/Source/Map.stories.tsx
  stories/Source/components/updatedata.tsx
Labels: PR: unreviewed, bug

#176 fix: text overlap
  packages/layers/src/point/models/text.ts
  packages/source/src/source.ts
  packages/source/src/transform/hexagon.ts
  packages/source/src/transform/join.ts
  stories/Layers/components/Text.tsx
Labels: PR: reviewed-changes-requested, bug

#178 Mapbox
  docs/api/component/markerLayer.en.md
  docs/api/component/markerLayer.zh.md
  lerna.json
  packages/component/package.json
  packages/component/src/markerlayer.ts
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/maps/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/source/src/transform/grid.ts
  packages/source/src/transform/grid2.ts
  packages/source/src/transform/hexagon.ts
  packages/utils/package.json
  packages/utils/src/index.ts
  packages/utils/src/statistics.ts
  stories/Components/components/clusterMarker.tsx
  stories/Layers/components/HeatMap.tsx
Labels: PR: unreviewed

#179 Layer async
  docs/api/component/markerLayer.zh.md
  packages/component/src/control/BaseControl.ts
  packages/component/src/control/layer.ts
  packages/component/src/control/logo.ts
  packages/component/src/control/scale.ts
  packages/component/src/control/zoom.ts
  packages/component/src/markerlayer.ts
  packages/core/src/services/component/ControlService.ts
  packages/core/src/services/component/IControlService.ts
  packages/core/src/services/layer/LayerService.ts
  packages/core/src/services/renderer/IMultiPassRenderer.ts
  packages/core/src/services/renderer/passes/MultiPassRenderer.ts
  packages/core/src/services/renderer/passes/PixelPickingPass.ts
  packages/core/src/services/scene/SceneService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/point/models/text.ts
  packages/scene/src/index.ts
  stories/Components/components/clusterMarker.tsx
Labels: PR: unreviewed

#180 Fix event
  docs/api/component/control.en.md
  docs/api/component/control.zh.md
  docs/api/component/marker.en.md
  docs/api/component/marker.zh.md
  docs/api/component/markerLayer.zh.md
  docs/api/component/popup.en.md
  docs/api/component/popup.zh.md
  docs/api/layer/heatmap_layer/grid.en.md
  docs/api/layer/heatmap_layer/grid.zh.md
  docs/api/layer/heatmap_layer/hexagon.en.md
  docs/api/layer/heatmap_layer/hexagon.zh.md
  docs/api/layer/heatmap_layer/normal.en.md
  docs/api/layer/heatmap_layer/normal.zh.md
  docs/api/layer/layer.en.md
  docs/api/layer/layer.zh.md
  docs/api/layer/line_layer/arc.en.md
  docs/api/layer/line_layer/arc.zh.md
  docs/api/layer/line_layer/linelayer.en.md
  docs/api/layer/line_layer/linelayer.zh.md
  docs/api/layer/point_layer/cluster.zh.md
  docs/api/layer/point_layer/dot.en.md
  docs/api/layer/point_layer/dot.zh.md
  docs/api/layer/polygon_layer/polygonlayer.zh.md
  docs/api/layer/raster_layer.en.md
  docs/api/layer/raster_layer.zh.md
  docs/api/map.en.md
  docs/api/map.zh.md
  docs/api/scene.en.md
  docs/api/scene.zh.md
  docs/api/source/csv.en.md
  docs/api/source/csv.zh.md
  docs/api/source/json.en.md
  docs/api/source/json.zh.md
  docs/api/source/source.en.md
  docs/api/source/source.zh.md
  docs/tutorial/data.en.md
  docs/tutorial/data.zh.md
  docs/tutorial/demo.en.md
  docs/tutorial/demo.zh.md
  docs/tutorial/map/offline.zh.md
  docs/tutorial/quickstart.zh.md
  lerna.json
  packages/component/package.json
  packages/component/src/control/layer.ts
  packages/core/package.json
  packages/core/src/services/interaction/InteractionService.ts
  packages/l7/package.json
  packages/layers/package.json
  packages/maps/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/source/src/source.ts
  packages/utils/package.json
Labels: PR: unreviewed

#181 Fix event
  docs/api/component/control.zh.md
  docs/api/component/marker.zh.md
  docs/api/component/markerLayer.zh.md
  docs/api/component/popup.en.md
  docs/api/component/popup.zh.md
  docs/api/layer/layer.en.md
  docs/api/layer/layer.zh.md
  docs/api/layer/raster_layer.en.md
  docs/api/layer/raster_layer.zh.md
  docs/api/scene.en.md
  docs/api/scene.zh.md
  docs/api/source/source.zh.md
  site/pages/index.zh.tsx
Labels: PR: unreviewed
