Repository antvis/L7, pull requests merged in 2020-03, with the labels that each got.

#235 fix: fix map reference
  packages/maps/package.json
  packages/maps/typings/index.d.ts
  packages/react/src/component/Scene.tsx
Labels: bug

#198 test: 新增scene测试用例
  packages/component/src/utils/anchor.ts
  packages/core/src/services/scene/SceneService.ts
  packages/layers/src/line/shaders/line_arc2d_vert.glsl
  packages/layers/src/line/shaders/line_bezier_vert.glsl
  packages/layers/src/plugins/DataMappingPlugin.ts
  packages/maps/src/amap/map.ts
  packages/scene/__tests__/index.spec.ts
Labels: PR: unreviewed, test

#247 docs: fix marker popup docs
  docs/api/component/control.zh.md
  docs/api/component/marker.en.md
  docs/api/component/marker.zh.md
  docs/api/component/popup.en.md
  docs/api/component/popup.zh.md
  docs/api/react/layer.en.md
  docs/api/react/layer.zh.md
  docs/api/source/source.zh.md
  gatsby-config.js
  stories/Layers/components/data_update.tsx
Labels: PR: unreviewed, documentation

#253 Ios 12 event
  examples/react/covid/demo/covid_bubble.tsx
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/core/src/services/interaction/InteractionService.ts
  packages/l7/demo/polygon.html
  packages/l7/package.json
  packages/layers/package.json
  packages/maps/package.json
  packages/react/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  site/pages/index.zh.tsx
Labels: PR: reviewed-changes-requested

#255 fix: ios touchstart && double touch
  packages/core/src/services/interaction/InteractionService.ts
Labels: PR: reviewed-changes-requested, bug

#257 L7 draw
  build/bundle.ts
  build/rollup-plugin-glsl.js
  packages/core/src/services/interaction/IInteractionService.ts
  packages/core/src/services/interaction/InteractionService.ts
  packages/core/src/services/interaction/PickingService.ts
  packages/core/src/services/scene/ISceneService.ts
  packages/core/src/services/scene/SceneService.ts
  packages/draw/README.md
  packages/draw/package.json
  packages/draw/rollup.config.js
  packages/draw/src/index.ts
  packages/draw/src/modes/draw_feature.ts
  packages/draw/src/source.ts
  packages/draw/src/util/constant.ts
  packages/draw/src/util/theme.ts
  packages/draw/tsconfig.build.json
  packages/l7/demo/circle.html
  packages/l7/demo/polygon.html
  packages/renderer/package.json
  packages/scene/src/index.ts
  stories/Draw/Components/DrawCircle.tsx
  stories/Draw/Components/DrawPolygon.tsx
  stories/Draw/Components/DrawRect.tsx
  stories/Draw/Draw.stories.tsx
  stories/React/components/Scene.tsx
  stories/React/components/world.tsx
  stories/React/components/world_ncov_bubble_animate.tsx
  yarn.lock
Labels: PR: unreviewed

#258 fix: picking
  packages/core/src/services/interaction/PickingService.ts
  stories/Draw/Components/DrawCircle.tsx
  stories/React/components/world.tsx
Labels: PR: reviewed-changes-requested, bug

#259 L7 draw
  babel.config.js
  docs/api/scene.en.md
  docs/api/scene.zh.md
  examples/react/covid/demo/meta.json
  package.json
  packages/draw/package.json
  packages/draw/src/modes/draw_circle.ts
  packages/draw/src/modes/draw_feature.ts
  packages/l7/demo/circle.html
  packages/l7/demo/polygon.html
  packages/l7/src/index.ts
  yarn.lock
Labels: PR: reviewed-changes-requested

#264 fix: 修复文本更新bug fixes #232
  packages/layers/src/citybuliding/models/build.ts
  packages/layers/src/line/models/arc.ts
  packages/layers/src/line/models/arc_3d.ts
  packages/layers/src/line/models/great_circle.ts
  packages/layers/src/plugins/DataMappingPlugin.ts
  packages/layers/src/plugins/RegisterStyleAttributePlugin.ts
  packages/layers/src/plugins/UpdateModelPlugin.ts
  packages/layers/src/point/models/fill.ts
  packages/layers/src/point/models/image.ts
  packages/layers/src/point/models/normal.ts
  packages/layers/src/point/models/text.ts
  packages/layers/src/polygon/models/extrude.ts
  packages/source/src/parser/json.ts
  stories/Layers/components/Arcline.tsx
  stories/Layers/components/heatmap3d.tsx
Labels: PR: unreviewed, bug

#267 fix: 修复颜色纹理取色问题 & 图片标注默认颜色问题
  packages/layers/src/heatmap/index.ts
  packages/layers/src/heatmap/models/heatmap.ts
  packages/layers/src/heatmap/shaders/heatmap_3d_frag.glsl
  packages/layers/src/heatmap/shaders/heatmap_frag.glsl
  packages/layers/src/heatmap/shaders/heatmap_framebuffer_frag.glsl
  packages/layers/src/heatmap/shaders/heatmap_framebuffer_vert.glsl
  packages/layers/src/heatmap/shaders/heatmap_vert.glsl
  packages/layers/src/point/shaders/image_frag.glsl
  packages/layers/src/raster/models/raster.ts
  packages/layers/src/raster/raster.ts
  packages/layers/src/raster/raster2d.ts
  packages/layers/src/raster/shaders/raster_2d_frag.glsl
  packages/layers/src/raster/shaders/raster_vert.glsl
  packages/utils/src/color.ts
  stories/Layers/Layers.stories.tsx
  stories/Layers/components/HeatMap.tsx
  stories/Layers/components/heatmap3d.tsx
Labels: PR: reviewed-changes-requested, bug

#268 Heatmap3d
  CHANGELOG.md
  README.zh-CN.md
  packages/core/src/services/interaction/PickingService.ts
  packages/layers/src/heatmap/models/heatmap.ts
  packages/layers/src/heatmap/shaders/heatmap_3d_frag.glsl
  packages/layers/src/heatmap/shaders/heatmap_3d_vert.glsl
  stories/Layers/components/HeatMap.tsx
  stories/Layers/components/heatmap3d.tsx
Labels: PR: reviewed-changes-requested

#270 feat: mapbox添加fitBoundsOptions
  packages/core/src/services/config/ConfigService.ts
  packages/core/src/services/config/IConfigService.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/map/IMapService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/plugins/LayerStylePlugin.ts
  packages/maps/src/amap/map.ts
  packages/maps/src/mapbox/map.ts
  packages/react/src/component/LayerAttribute/Layer.tsx
  packages/react/src/component/LayerAttribute/Source.tsx
  packages/react/src/component/LayerAttribute/index.ts
  packages/scene/src/IMapController.ts
  packages/scene/src/index.ts
  stories/React/components/world_ncov_fill.tsx
Labels: PR: unreviewed, enhancement
