Repository antvis/L7, pull requests merged in 2020-02, with the labels that each got.

#182 Fix hexagon_map
  docs/api/layer/layer.en.md
  docs/api/layer/layer.zh.md
  docs/tutorial/map/amap.en.md
  docs/tutorial/map/amap.zh.md
  docs/tutorial/map/mapbox.en.md
  docs/tutorial/map/mapbox.zh.md
  docs/tutorial/quickstart.en.md
  docs/tutorial/quickstart.zh.md
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/core/src/services/interaction/InteractionService.ts
  packages/l7/package.json
  packages/layers/package.json
  packages/maps/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/source/src/source.ts
  packages/source/src/transform/grid.ts
  packages/source/src/transform/hexagon.ts
  packages/utils/package.json
  stories/Layers/Layers.stories.tsx
  stories/Layers/components/hexagon.tsx
Labels: PR: reviewed-changes-requested

#183 fix: Update README.md
  README.md
Labels: PR: unreviewed, bug

#184 Map plugin
  docs/api/component/control.zh.md
  docs/api/component/popup.en.md
  docs/api/component/popup.zh.md
  packages/maps/src/amap/index.ts
  stories/Layers/components/AnimatePoint.tsx
Labels: PR: reviewed-changes-requested

#185 Map
  docs/api/scene.en.md
  docs/api/scene.zh.md
  lerna.json
  packages/component/package.json
  packages/component/src/control/layer.ts
  packages/core/package.json
  packages/core/src/services/config/ConfigService.ts
  packages/core/src/services/config/IConfigService.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/scene/ISceneService.ts
  packages/core/src/services/scene/SceneService.ts
  packages/core/src/shaders/picking.frag.glsl
  packages/l7/package.json
  packages/layers/package.json
  packages/layers/src/core/BaseLayer.ts
  packages/maps/package.json
  packages/maps/src/amap/Wrapper.ts
  packages/maps/src/amap/index.ts
  packages/maps/src/amap/map.ts
  packages/maps/src/index.ts
  packages/maps/src/mapbox/Wrapper.ts
  packages/maps/src/mapbox/index.ts
  packages/maps/src/mapbox/map.ts
  packages/renderer/package.json
  packages/scene/package.json
  packages/scene/src/index.ts
  packages/source/package.json
  packages/utils/package.json
  stories/Components/components/Scale.tsx
  stories/Layers/components/Point.tsx
  stories/Layers/lib/colorscales.ts
Labels: PR: unreviewed

#189 fix: many bugs
  .travis.yml
  docs/api/component/marker.en.md
  docs/api/component/marker.zh.md
  docs/api/source/source.en.md
  docs/api/source/source.zh.md
  package.json
  packages/component/src/marker.ts
  packages/core/src/services/layer/IStyleAttributeService.ts
  packages/core/src/services/layer/StyleAttribute.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/plugins/DataMappingPlugin.ts
  packages/layers/src/plugins/FeatureScalePlugin.ts
  packages/layers/src/point/shaders/image_vert.glsl
  packages/source/src/transform/join.ts
  stories/Components/components/Marker.tsx
  stories/Layers/components/Line.tsx
  stories/Layers/components/Point3D.tsx
  stories/Layers/components/PointImage.tsx
Labels: PR: unreviewed, bug

#194 Fix layer
  docs/api/source/source.en.md
  docs/api/source/source.zh.md
  lerna.json
  package.json
  packages/component/package.json
  packages/core/package.json
  packages/core/src/services/layer/LayerService.ts
  packages/core/src/services/renderer/passes/PixelPickingPass.ts
  packages/l7/package.json
  packages/layers/package.json
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/line/shaders/line_frag.glsl
  packages/layers/src/plugins/PixelPickingPlugin.ts
  packages/layers/src/point/models/text.ts
  packages/layers/src/point/shaders/text_frag.glsl
  packages/maps/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/utils/package.json
  stories/Layers/components/Arc2DLine.tsx
  stories/Layers/components/Arcline.tsx
  stories/Layers/components/Line.tsx
  stories/Layers/components/Text.tsx
  stories/Layers/components/dash.tsx
  yarn.lock
Labels: PR: reviewed-changes-requested

#195 fix(layer): getLayer method
  docs/api/layer/layer.en.md
  docs/api/layer/layer.zh.md
  docs/api/scene.en.md
  docs/api/scene.zh.md
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/layer/LayerService.ts
  packages/l7/package.json
  packages/layers/package.json
  packages/maps/package.json
  packages/renderer/package.json
  packages/scene/__tests__/index.spec.ts
  packages/scene/package.json
  packages/scene/src/index.ts
  packages/source/package.json
  packages/utils/package.json
  stories/Components/components/Scale.tsx
  stories/Layers/components/Line.tsx
  yarn.lock
Labels: PR: reviewed-changes-requested, bug

#197 fix(docs): 修改文档
  docs/api/layer/layer.en.md
  docs/api/layer/layer.zh.md
  docs/api/scene.en.md
  docs/api/scene.zh.md
Labels: PR: unreviewed, bug

#170 feat(marker): 针对聚合点只渲染视野范围内的元素，提高性能
  packages/component/src/markerlayer.ts
Labels: PR: unreviewed, enhancement

#199 Marker layer
  docs/api/component/markerLayer.en.md
  docs/api/layer/cityBuilding.en.md
  docs/api/layer/cityBuilding.zh.md
  docs/api/scene.en.md
  lerna.json
  package.json
  packages/component/package.json
  packages/component/src/markerlayer.ts
  packages/core/package.json
  packages/core/src/services/config/__tests__/schema.spec.ts
  packages/core/src/services/config/sceneConfigSchema.ts
  packages/core/src/services/log/LogService.ts
  packages/l7/package.json
  packages/layers/package.json
  packages/layers/src/citybuliding/building.ts
  packages/layers/src/citybuliding/models/build.ts
  packages/maps/package.json
  packages/maps/src/BaseMapWrapper.ts
  packages/maps/src/mapbox/map.ts
  packages/renderer/package.json
  packages/scene/package.json
  packages/scene/src/index.ts
  packages/source/package.json
  packages/utils/__tests__/geo.spec.ts
  packages/utils/package.json
  packages/utils/src/geo.ts
  stories/Components/components/clusterMarker.tsx
  stories/Layers/components/AnimatePoint.tsx
  stories/Layers/components/Point.tsx
  stories/Layers/components/citybuilding.tsx
Labels: PR: unreviewed

#203 fix: 弧线显示有虚线存在
  .storybook/config.ts
  examples/line/arc/demo/arcCircle.js
  package.json
  packages/layers/src/line/models/arc.ts
  packages/layers/src/line/models/arc_3d.ts
  packages/layers/src/line/models/great_circle.ts
  packages/layers/src/line/shaders/line_arc_3d_vert.glsl
  packages/layers/src/line/shaders/line_arc_frag.glsl
  packages/layers/src/line/shaders/line_arc_great_circle_vert.glsl
  packages/layers/src/line/shaders/line_arc_vert.glsl
  packages/layers/src/line/shaders/line_bezier_vert.glsl
  stories/Layers/components/Arc2DLine.tsx
Labels: PR: reviewed-changes-requested, bug

#206 fix: 🆙 upgrade gatsby theme version
  package.json
  yarn.lock
Labels: bug

#202 feat: L7 React 2.0
  gatsby-node.js
  packages/component/src/marker.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/map/IMapService.ts
  packages/core/src/services/renderer/passes/PixelPickingPass.ts
  packages/core/src/services/scene/ISceneService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/react/README.md
  packages/react/package.json
  packages/react/src/component/Layer.ts
  packages/react/src/component/LayerAttribute/Color.tsx
  packages/react/src/component/LayerAttribute/Layer.tsx
  packages/react/src/component/LayerAttribute/Scales.tsx
  packages/react/src/component/LayerAttribute/Shape.tsx
  packages/react/src/component/LayerAttribute/Size.tsx
  packages/react/src/component/LayerAttribute/Source.tsx
  packages/react/src/component/LayerAttribute/Style.tsx
  packages/react/src/component/LayerAttribute/index.ts
  packages/react/src/component/Scene.tsx
  packages/react/src/component/SceneContext.tsx
  packages/react/src/index.ts
  packages/react/tsconfig.build.json
  stories/React/React.stories.tsx
  stories/React/components/Scene.tsx
Labels: enhancement

#215 feat: 地图画布的底色继承外面的颜色
  packages/core/src/utils/dom.ts
Labels: enhancement

#218 improvement: update l7-react
  packages/component/src/marker.ts
  packages/component/src/popup.ts
  packages/core/src/services/component/IPopupService.ts
  packages/core/src/services/interaction/PickingService.ts
  packages/core/src/shaders/projection.glsl
  packages/layers/src/point/shaders/fill_vert.glsl
  packages/react/src/component/LayerAttribute/Layer.tsx
  packages/react/src/component/LayerAttribute/index.ts
  packages/react/src/component/LayerEvent.tsx
  packages/react/src/component/LoadImage.tsx
  packages/react/src/component/MapboxScene.tsx
  packages/react/src/component/Marker.tsx
  packages/react/src/component/Popup.tsx
  packages/react/src/component/Scene.tsx
  packages/react/src/component/SceneEvent.tsx
  packages/react/src/index.ts
  packages/utils/src/anchor.ts
  packages/utils/src/index.ts
  stories/Layers/components/PointImage.tsx
  stories/Layers/components/dash.tsx
  stories/React/components/Scene.tsx
Labels: improvement

#220 fix: mapbox 3d 柱图显示问题
  packages/core/src/shaders/projection.glsl
  stories/Layers/components/Point3D.tsx
  stories/Layers/components/PointImage.tsx
Labels: bug

#221 修复l7-react中的几个小问题
  packages/react/src/component/LayerAttribute/Layer.tsx
  packages/react/src/component/LayerEvent.tsx
  packages/react/src/component/Scene.tsx
  packages/react/src/component/SceneEvent.tsx
Labels: PR: unreviewed

#222 refactor: tslint error
  .github/CONTRIBUTING.md
  packages/core/src/services/map/IMapService.ts
  packages/core/src/services/renderer/passes/BasePostProcessingPass.ts
  packages/core/src/utils/math.ts
  packages/layers/src/utils/polylineNormal.ts
  packages/maps/src/mapbox/map.ts
  packages/react/src/component/AMapScene.tsx
  packages/react/src/component/LayerAttribute/Layer.tsx
  packages/react/src/component/LayerContext.tsx
  packages/react/src/component/MapboxScene.tsx
  packages/react/src/component/Popup.tsx
  packages/react/src/component/Scene.tsx
  packages/react/src/component/SceneContext.tsx
  packages/renderer/src/regl/__tests__/model.spec.ts
  packages/renderer/src/regl/__tests__/model.uniform.spec.ts
  packages/scene/src/index.ts
  yarn.lock
Labels: PR: unreviewed, refactor

#224 fix: 修复MapboxScene的容器找不到
  packages/react/src/component/AMapScene.tsx
  packages/react/src/component/MapboxScene.tsx
  packages/react/src/component/Scene.tsx
  packages/react/src/component/SceneContext.tsx
Labels: bug

#234 fix: 高德地图logo & scene 为初始化完成销毁 & 地图背景问题
  packages/core/src/services/scene/ISceneService.ts
  packages/core/src/services/scene/SceneService.ts
  packages/core/src/utils/dom.ts
  packages/maps/src/amap/map.ts
  packages/react/src/component/LayerAttribute/Source.tsx
  packages/react/src/component/LayerAttribute/index.ts
  stories/Layers/components/column.tsx
  stories/Layers/components/polygon_line.tsx
Labels: bug
