Repository antvis/L7, pull requests merged in 2020-05, with the labels that each got.

#317 fix(draw): draw control event
  packages/draw/src/draw_control.ts
  stories/Draw/Components/Circle.tsx
  stories/Draw/Components/DrawControl.tsx
Labels: PR: reviewed-changes-requested, bug

#335 fix(draw): fix draw rect bug
  packages/draw/src/modes/draw_feature.ts
  packages/draw/src/modes/draw_mode.ts
Labels: PR: reviewed-changes-requested, bug

#341 fix(district): fix polygon layer setData 样式不生效 & 增加下钻上取地图
  packages/district/src/layer/baseLayer.ts
  packages/district/src/layer/country.ts
  packages/district/src/layer/drillDown.ts
  packages/district/src/layer/interface.ts
  packages/district/src/layer/world.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/plugins/FeatureScalePlugin.ts
  stories/District/Layer/Country.tsx
  stories/Layers/components/polygon.tsx
Labels: PR: reviewed-changes-requested, bug

#379 docs: fix duplicated antd css
  examples/district/basic/demo/china_map.js
  gatsby-browser.js
  package.json
  packages/renderer/src/regl/__tests__/model.uniform.spec.ts
  yarn.lock
Labels: PR: unreviewed, documentation

#380 style: import antd less
  gatsby-browser.js
Labels: PR: reviewed-changes-requested, style

#382 refactor(district): 对行政区划进行抽稀处理
  examples/district/basic/API.zh.md
  examples/district/drill/demo/meta.json
  packages/district/src/config_1.ts
  packages/district/src/index.ts
  packages/district/src/layer/baseLayer.ts
  packages/district/src/layer/country.ts
  packages/district/src/layer/province.ts
  packages/district/src/layer/world.ts
  stories/District/district.stories.tsx
Labels: PR: unreviewed, refactor

#386 fix(storybook): 移除使用antd的demo,解决storybook ts 编译报错问题
  package.json
  stories/District/Layer/drillDown.tsx
  stories/District/district.stories.tsx
  yarn.lock
Labels: PR: unreviewed, bug

#388 fix(district): 边界不契合的问题
  docs/api/layer/layer.en.md
  docs/api/layer/layer.zh.md
  package.json
  packages/district/src/config_1.ts
  packages/district/src/index.ts
  packages/district/src/layer/baseLayer.ts
  packages/district/src/layer/country.ts
  packages/district/src/layer/province.ts
  packages/district/src/layer/world.ts
  packages/maps/package.json
  stories/Components/components/Zoom.tsx
  yarn.lock
Labels: PR: unreviewed, bug

#389 fix(layer): fix sum statistic
  examples/heatmap/grid/demo/grid_world.js
  examples/heatmap/grid/demo/meta.json
  examples/heatmap/hexagon/demo/china.js
  packages/district/src/config.ts
  packages/district/src/index.ts
  packages/district/src/layer/baseLayer.ts
  packages/district/src/layer/city.ts
  packages/district/src/layer/country.ts
  packages/district/src/layer/interface.ts
  packages/district/src/layer/province.ts
  packages/district/src/layer/world.ts
  packages/utils/__tests__/statistic.spec.ts
  packages/utils/src/statistics.ts
  stories/District/Layer/world.tsx
  stories/Layers/components/hexagon.tsx
Labels: PR: reviewed-changes-requested, bug

#390 Fix storybook
  examples/district/basic/demo/world_map.js
  examples/district/bubble/demo/world_map.js
  packages/district/src/layer/country.ts
  packages/utils/__tests__/statistic.spec.ts
  packages/utils/src/statistics.ts
  stories/Draw/Components/DrawLine.tsx
Labels: PR: reviewed-changes-requested

#391 Fix storybook
  .storybook/webpack.config.js
  gatsby-node.js
  jest.config.js
  packages/boundry/README.md
  packages/boundry/__tests__/layer.spec.ts
  packages/boundry/package.json
  packages/boundry/rollup.config.js
  packages/boundry/src/config.ts
  packages/boundry/src/index.ts
  packages/boundry/src/layer/baseLayer.ts
  packages/boundry/src/layer/city.ts
  packages/boundry/src/layer/country.ts
  packages/boundry/src/layer/county.ts
  packages/boundry/src/layer/drillDown.ts
  packages/boundry/src/layer/interface.ts
  packages/boundry/src/layer/province.ts
  packages/boundry/src/layer/world.ts
  packages/boundry/tsconfig.build.json
  packages/district/src/config_1.ts
  stories/District/Layer/country_bubble.tsx
  stories/District/Layer/country_city.tsx
  stories/District/Layer/country_county.tsx
  stories/District/Layer/world.tsx
  stories/Draw/Components/DrawLine.tsx
  tsconfig.json
Labels: PR: reviewed-changes-requested

#392 fix(component): remove all markers from clusterMarkers in MarkerLayer.clear()
  packages/component/src/markerlayer.ts
Labels: PR: reviewed-changes-requested, bug
