Repository antvis/L7, pull requests merged in 2020-10, with the labels that each got.

#535 chore: 修改ts 相关配置
  .storybook/webpack.config.js
  tsconfig.build.json
  tsconfig.json
Labels: PR: unreviewed, chore

#537 fix(scene): 地图panBy 方法
  packages/scene/src/index.ts
Labels: PR: unreviewed, bug

#539 feat(core): interaction
  packages/core/src/services/interaction/IInteractionService.ts
  packages/core/src/services/interaction/InteractionService.ts
  packages/core/src/services/interaction/PickingService.ts
  stories/Layers/components/polygon.tsx
Labels: PR: unreviewed, enhancement

#540 fix(layer): 采用默认抗锯齿效果
  packages/l7/src/version.ts
  packages/layers/src/line/shaders/line_frag.glsl
  stories/Layers/components/Line.tsx
  stories/Layers/components/dash.tsx
Labels: PR: unreviewed, bug

#544 fix: 暂时去除后处理
  gatsby-node.js
  packages/core/src/services/renderer/passes/MultiPassRenderer.ts
  packages/core/src/services/renderer/passes/PostProcessor.ts
  packages/core/src/services/renderer/passes/RenderPass.ts
  tsconfig.json
Labels: PR: unreviewed
