Repository antvis/L7, pull requests merged in 2020-06, with the labels that each got.

#398 Fix draw line
  packages/boundry/src/config.ts
  packages/boundry/src/layer/country.ts
  packages/component/src/popup.ts
  packages/draw/src/modes/draw_feature.ts
  packages/draw/src/modes/draw_line.ts
  packages/draw/src/modes/draw_point.ts
  packages/draw/src/modes/draw_polygon.ts
  packages/layers/src/line/models/arc.ts
  packages/layers/src/line/models/arc_3d.ts
  packages/layers/src/line/models/great_circle.ts
  packages/layers/src/line/models/line.ts
  packages/layers/src/line/shaders/line_arc2d_vert.glsl
  packages/layers/src/line/shaders/line_arc_3d_vert.glsl
  packages/layers/src/line/shaders/line_arc_frag.glsl
  packages/layers/src/line/shaders/line_arc_great_circle_vert.glsl
  packages/layers/src/line/shaders/line_arc_vert.glsl
  packages/layers/src/line/shaders/line_bezier_vert.glsl
  packages/layers/src/line/shaders/line_frag.glsl
  packages/layers/src/line/shaders/line_vert.glsl
  packages/maps/src/mapbox/map.ts
  stories/District/Layer/country_city.tsx
  stories/Draw/Components/DrawLine.tsx
  stories/Draw/Components/DrawPoint.tsx
  stories/Layers/components/Polygon3D.tsx
  stories/Layers/components/dash.tsx
  stories/Layers/components/polygon.tsx
  stories/Source/components/multiPolygon.tsx
Labels: PR: reviewed-changes-requested

#400 District data
  examples/district/basic/demo/china_map_2.js
  examples/district/basic/demo/world_map.js
  packages/boundry/src/config.ts
  packages/maps/package.json
  stories/District/Layer/Country.tsx
  stories/District/Layer/Country2.tsx
  stories/District/Layer/world.tsx
Labels: PR: unreviewed

#405 fix(district): 区划接口定义导出
  packages/boundry/src/index.ts
Labels: PR: reviewed-changes-requested, bug

#406 fix(source & layer): setData update cfg
  packages/layers/src/core/BaseLayer.ts
  packages/source/src/source.ts
  stories/District/Layer/world.tsx
Labels: PR: reviewed-changes-requested, bug

#411 fix(layer): 更新空数据& filter 方法
  examples/react/layer/demo/world.jsx
  packages/boundry/package.json
  packages/boundry/src/config.ts
  packages/boundry/src/layer/baseLayer.ts
  packages/boundry/src/layer/interface.ts
  packages/draw/src/draw_control.ts
  packages/draw/src/modes/draw_feature.ts
  packages/layers/src/plugins/FeatureScalePlugin.ts
  packages/layers/src/point/__tests__/layer.spec.ts
  packages/source/src/transform/join.ts
  stories/District/Layer/world.tsx
  stories/Layers/components/Point.tsx
  tslint.test.json
Labels: PR: unreviewed, bug

#415 docs: Add english version of CONTRIBUTING.md
  .github/CONTRIBUTING_ENGLISH.md
Labels: PR: unreviewed, documentation

#416 fix(boundry): option merge
  packages/boundry/__tests__/layer.spec.ts
  packages/boundry/src/config.ts
  packages/boundry/src/layer/baseLayer.ts
  packages/boundry/src/layer/interface.ts
  packages/boundry/src/layer/province.ts
  packages/core/src/services/layer/StyleAttributeService.ts
  stories/District/Layer/province.tsx
  stories/District/Layer/world.tsx
  stories/District/district.stories.tsx
  yarn.lock
Labels: PR: unreviewed, bug

#417 chore(district): update china data
  docs/api/district/baselayer.zh.md
  examples/district/basic/API.zh.md
  examples/district/basic/demo/attach_map.js
  examples/district/basic/demo/hainan.js
  examples/district/basic/demo/meta.json
  examples/district/react/demo/province.tsx
  packages/boundry/src/config.ts
  packages/boundry/src/layer/drillDown.ts
  packages/boundry/src/layer/interface.ts
  stories/District/Layer/Country.tsx
  stories/District/Layer/drillDown.tsx
Labels: PR: reviewed-changes-requested, chore

#418 fix(source): 获取选中数据数据被修改的bug
  packages/source/src/source.ts
Labels: PR: reviewed-changes-requested, bug
