Repository antvis/L7, pull requests merged in 2020-04, with the labels that each got.

#275 fix: 修复版本锁定&marker事件
  .gitignore
  examples/react/covid/demo/covid_animate.tsx
  examples/react/covid/demo/covid_bubble.tsx
  examples/react/covid/demo/covid_column.tsx
  examples/react/covid/demo/covid_extrude.tsx
  examples/react/covid/demo/covid_fill.tsx
  examples/react/covid/demo/covid_grid.tsx
  packages/core/src/services/interaction/InteractionService.ts
  packages/core/src/shaders/picking.frag.glsl
  packages/draw/__tests__/util/create_geometry.spec.ts
  packages/draw/src/css/draw.less
  packages/draw/src/draw_control.ts
  packages/draw/src/modes/draw_circle.ts
  packages/draw/src/modes/draw_delete.ts
  packages/draw/src/modes/draw_line.ts
  packages/draw/src/modes/draw_mode.ts
  packages/draw/src/modes/draw_point.ts
  packages/draw/src/modes/draw_polygon.ts
  packages/draw/src/modes/draw_rect.ts
  packages/draw/src/util/create_geometry.ts
  packages/l7/package.json
  packages/maps/package.json
  stories/Components/components/Marker.tsx
  stories/Layers/components/Point.tsx
Labels: PR: reviewed-changes-requested, bug

#280 fix: 低端移动设备拾取画布太大内存泄漏的问题
  CHANGELOG.md
  packages/core/src/services/config/ConfigService.ts
  packages/core/src/services/config/IConfigService.ts
  packages/core/src/services/interaction/IPickingService.ts
  packages/core/src/services/interaction/PickingService.ts
  packages/core/src/services/scene/SceneService.ts
  packages/l7/src/version.ts
  stories/Layers/components/Point.tsx
Labels: PR: unreviewed, bug

#282 layer 过滤方法
  packages/layers/src/plugins/DataMappingPlugin.ts
  stories/Layers/components/RasterLayer.tsx
  stories/Layers/components/light.tsx
Labels: PR: reviewed-changes-requested

#293 chore: upgrade dependences and fix warning
  docs/api/draw/index.en.md
  package.json
  packages/draw/package.json
  yarn.lock
Labels: PR: unreviewed, chore

#295 chore: 🔀 add GitHub Action to sync Gitee
  .github/workflows/mirror.yml
Labels: PR: unreviewed, chore

#297 chore: add gitleaks
  .github/workflows/gitleaks.yml
  .gitleaks.toml
  .travis.yml
Labels: PR: unreviewed, chore

#283 Draw doc
  .travis.yml
  build/bundle.ts
  docs/api/layer/line_layer/arc.en.md
  docs/api/layer/line_layer/arc.zh.md
  docs/api/layer/line_layer/path.en.md
  docs/api/layer/line_layer/path.zh.md
  docs/tutorial/interactive/hightlight.en.md
  examples/draw/UI/API.en.md
  examples/draw/UI/API.zh.md
  examples/draw/UI/demo/amap.js
  examples/draw/UI/demo/mapbox.js
  examples/draw/UI/demo/meta.json
  examples/draw/UI/index.en.md
  examples/draw/UI/index.zh.md
  examples/line/animate/demo/arcCircle.js
  examples/line/animate/demo/meta.json
  examples/line/animate/demo/trip_arc.js
  examples/line/animate/demo/trip_arc_dark.js
  examples/line/animate/index.en.md
  examples/line/animate/index.zh.md
  examples/polygon/fill/demo/city.js
  examples/polygon/fill/demo/meta.json
  examples/polygon/fill/demo/polygon.js
  examples/polygon/fill/demo/province.js
  examples/react/control/API.en.md
  examples/react/control/API.zh.md
  examples/react/layer/API.en.md
  examples/react/layer/API.zh.md
  examples/react/scene/API.en.md
  examples/react/scene/API.zh.md
  gatsby-browser.js
  gatsby-config.js
  gatsby-node.js
  package.json
  packages/component/src/control/scale.ts
  packages/component/src/marker.ts
  packages/core/src/services/scene/SceneService.ts
  packages/core/src/utils/dom.ts
  packages/draw/package.json
  packages/draw/src/draw_control.ts
  packages/draw/src/modes/draw_feature.ts
  packages/l7/demo/circle.html
  packages/l7/demo/text.html
  packages/layers/src/line/shaders/line_frag.glsl
  stories/Components/components/Scale.tsx
  stories/Layers/Layers.stories.tsx
  stories/Layers/components/Arc2DLine.tsx
  stories/Layers/components/light.tsx
  stories/Layers/components/lineAnimate.tsx
  yarn.lock
Labels: PR: unreviewed

#298 fix(source): 聚合图支持其它数据格式
  packages/source/src/source.ts
  packages/source/src/transform/cluster.ts
  stories/Layers/Layers.stories.tsx
  stories/Layers/components/cluster.tsx
Labels: PR: unreviewed, bug

#301 Bug fix
  build/rollup.config.js
  docs/api/changelog.zh.md
  docs/api/l7.zh.md
  docs/api/layer/layer.zh.md
  docs/api/react/layer.zh.md
  docs/api/react/popup.zh.md
  docs/api/scene.zh.md
  packages/component/src/marker.ts
  packages/draw/src/css/draw.less
  packages/draw/src/draw_control.ts
  packages/l7/src/version.ts
  packages/layers/src/point/models/text.ts
  packages/react/src/component/Popup.tsx
  stories/Components/components/Zoom.tsx
  stories/Components/components/markerlayer.tsx
  stories/React/components/Scene.tsx
Labels: PR: unreviewed

#304 fix: animate shader bug
  packages/layers/src/line/shaders/line_arc_frag.glsl
Labels: PR: unreviewed, bug
