Repository antvis/L7, pull requests merged in 2020-08, with the labels that each got.

#462 fix: 解决PointLayer ImageModel频繁调用setData()GPU内存不释放问题
  packages/layers/src/point/models/image.ts
Labels: PR: reviewed-changes-requested, bug

#477 fix(layer): PointLayer图片纹理浮点数据精度问题
  packages/layers/src/point/shaders/image_frag.glsl
Labels: PR: unreviewed, bug

#479 fix(source & line model): 支持带洞的边形绘制边界
  docs/api/district/baselayer.en.md
  docs/api/district/baselayer.zh.md
  docs/api/district/start.en.md
  docs/api/scene.en.md
  docs/api/scene.zh.md
  examples/district/basic/API.en.md
  examples/district/basic/API.zh.md
  examples/district/bubble/API.en.md
  examples/district/bubble/API.zh.md
  packages/layers/src/core/triangulation.ts
  packages/layers/src/utils/extrude_polyline.ts
  packages/react/src/index.ts
  packages/source/src/parser/geojson.ts
  stories/District/Layer/drillDown.tsx
  stories/Layers/components/hexagon.tsx
  stories/Source/Map.stories.tsx
  stories/Source/components/hole.tsx
  stories/Source/components/multiLine.tsx
  stories/Source/components/multiPolygon.tsx
Labels: PR: unreviewed, bug

#482 Feature fix
  packages/boundary/src/layer/baseLayer.ts
  packages/boundary/src/layer/drillDown.ts
  packages/boundary/src/layer/province.ts
  packages/l7/src/version.ts
  stories/District/Layer/drillDown.tsx
Labels: PR: unreviewed

#487 fix(react): 高德地图地图状态同步
  packages/react/src/component/AMapScene.tsx
Labels: PR: unreviewed, bug

#490 fix(layer): heatmap layer grid无法渲染squareColumn 3D图形问题
  docs/api/layer/heatmap_layer/grid.en.md
  docs/api/layer/heatmap_layer/grid.zh.md
  docs/api/layer/heatmap_layer/hexagon.en.md
  docs/api/layer/heatmap_layer/hexagon.zh.md
  docs/api/layer/heatmap_layer/normal.en.md
  docs/api/layer/heatmap_layer/normal.zh.md
  docs/api/layer/line_layer/arc.en.md
  docs/api/layer/line_layer/arc.zh.md
  docs/api/layer/line_layer/linelayer.zh.md
  docs/api/layer/line_layer/path.en.md
  docs/api/layer/line_layer/path.zh.md
  docs/api/layer/point_layer/bubble.en.md
  docs/api/layer/point_layer/bubble.zh.md
  docs/api/layer/point_layer/chart.en.md
  docs/api/layer/point_layer/chart.zh.md
  docs/api/layer/point_layer/cluster.en.md
  docs/api/layer/point_layer/cluster.zh.md
  docs/api/layer/point_layer/column.en.md
  docs/api/layer/point_layer/column.zh.md
  docs/api/layer/point_layer/dot.en.md
  docs/api/layer/point_layer/dot.zh.md
  docs/api/layer/point_layer/marker.en.md
  docs/api/layer/point_layer/marker.zh.md
  docs/api/layer/point_layer/scatter.en.md
  docs/api/layer/point_layer/scatter.zh.md
  docs/api/layer/point_layer/symbol.en.md
  docs/api/layer/point_layer/symbol.zh.md
  docs/api/layer/point_layer/text.en.md
  docs/api/layer/point_layer/text.zh.md
  docs/api/layer/polygon_layer/extrude.zh.md
  docs/api/layer/polygon_layer/fill.zh.md
  docs/api/layer/polygon_layer/polygonlayer.en.md
  docs/api/layer/polygon_layer/polygonlayer.zh.md
  packages/l7/src/version.ts
  packages/layers/src/heatmap/shaders/grid_vert.glsl
  packages/source/src/transform/grid.ts
  stories/Layers/Layers.stories.tsx
  stories/Layers/components/gridtest.tsx
  stories/customMap/map.stories.tsx
Labels: PR: unreviewed, bug

#491 feat(draw): draw circle add change event
  packages/draw/src/modes/draw_circle.ts
  packages/draw/src/util/constant.ts
  packages/source/src/transform/grid.ts
  stories/Layers/components/gridtest.tsx
  stories/Layers/components/hexagon.tsx
Labels: PR: unreviewed, enhancement

#494 fix(layer): 解决线图层绘制异常的问题
  packages/l7/src/version.ts
  packages/layers/src/utils/extrude_polyline.ts
  packages/scene/__tests__/index.spec.ts
Labels: PR: unreviewed, bug

#497 fix: 修复去除重复点计算逻辑的 bug
  examples/line/path/demo/road_light.js
  packages/layers/src/utils/__tests__/extrude_polyline.spec.ts
  packages/layers/src/utils/extrude_polyline.ts
Labels: PR: unreviewed, bug
