Repository antvis/L7, pull requests merged in 2020-07, with the labels that each got.

#424 Layer hight
  docs/api/district/baselayer.en.md
  docs/api/district/baselayer.zh.md
  examples/district/basic/API.en.md
  examples/district/basic/API.zh.md
  examples/tutorial/layer/demo/layer_highlight.js
  examples/tutorial/layer/demo/mapbox.js
  examples/tutorial/layer/demo/meta.json
  examples/tutorial/layer/index.en.md
  examples/tutorial/layer/index.zh.md
  packages/boundry/src/layer/baseLayer.ts
  packages/boundry/src/layer/country.ts
  packages/boundry/src/layer/interface.ts
  packages/boundry/src/layer/province.ts
  packages/boundry/src/layer/world.ts
  packages/core/src/services/layer/LayerService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/line/models/line.ts
  stories/District/Layer/Country.tsx
  stories/District/Layer/province.tsx
  stories/Layers/Layers.stories.tsx
  stories/Layers/components/highlight.tsx
Labels: PR: unreviewed

#425 Docs udpdte
  .storybook/webpack.config.js
  docs/api/component/markerLayer.en.md
  docs/api/component/markerLayer.zh.md
  docs/api/district/baselayer.en.md
  docs/api/district/baselayer.zh.md
  docs/api/district/drilldown.en.md
  docs/api/layer/point_layer/text.zh.md
  examples/district/basic/API.en.md
  examples/district/basic/API.zh.md
  gatsby-node.js
  packages/boundary/README.md
  packages/boundary/__tests__/layer.spec.ts
  packages/boundary/package.json
  packages/boundary/rollup.config.js
  packages/boundary/src/config.ts
  packages/boundary/src/index.ts
  packages/boundary/src/layer/baseLayer.ts
  packages/boundary/src/layer/city.ts
  packages/boundary/src/layer/country.ts
  packages/boundary/src/layer/county.ts
  packages/boundary/src/layer/drillDown.ts
  packages/boundary/src/layer/interface.ts
  packages/boundary/src/layer/province.ts
  packages/boundary/src/layer/world.ts
  packages/boundary/tsconfig.build.json
  packages/core/src/services/layer/ILayerService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/core/triangulation.ts
  packages/layers/src/heatmap/models/heatmap.ts
  packages/layers/src/line/models/line.ts
  packages/layers/src/line/shaders/line_frag.glsl
  packages/layers/src/plugins/LayerModelPlugin.ts
  packages/layers/src/point/models/text.ts
  packages/layers/src/utils/symbol-layout.ts
  packages/source/__tests__/parser/geojson.spec.ts
  packages/source/src/parser/geojson.ts
  stories/District/Layer/Country.tsx
  stories/District/Layer/country_city.tsx
  stories/District/Layer/province.tsx
  stories/District/Layer/world.tsx
  stories/Layers/components/heatmap2.tsx
  stories/Layers/components/polygon.tsx
  tsconfig.json
  yarn.lock
Labels: PR: unreviewed

#429 线图层支持拐角
  packages/boundary/src/config.ts
  packages/core/src/services/asset/IIconService.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/layer/StyleAttributeService.ts
  packages/l7/demo/circle.html
  packages/l7/demo/dot.html
  packages/l7/demo/polygon.html
  packages/layers/package.json
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/core/BaseModel.ts
  packages/layers/src/core/triangulation.ts
  packages/layers/src/line/models/line.ts
  packages/layers/src/plugins/LayerModelPlugin.ts
  packages/layers/src/point/index.ts
  packages/layers/src/point/models/image.ts
  packages/layers/src/point/models/text.ts
  packages/layers/src/utils/__tests__/extrude_polyline.spec.ts
  packages/layers/src/utils/extrude_polyline.ts
  packages/layers/src/utils/polylineNormal.ts
  packages/maps/src/amap/map.ts
  stories/District/Layer/Country.tsx
  stories/District/Layer/drillDown.tsx
  stories/District/Layer/province.tsx
  stories/District/Layer/world.tsx
  stories/Source/components/multiLine.tsx
Labels: PR: unreviewed

#430 docs(docs): update api
  docs/api/react/layer.en.md
  docs/api/react/layer.zh.md
  docs/api/react/scene.en.md
  docs/api/react/scene.zh.md
  docs/tutorial/map/offline.en.md
  docs/tutorial/map/offline.zh.md
  docs/tutorial/quickstart.zh.md
Labels: PR: unreviewed, documentation

#433 fix(layer): 图片图层重绘
  packages/layers/src/point/models/image.ts
Labels: PR: reviewed-changes-requested, bug

#436 fix(render): fix elemet double destroy error
  packages/renderer/src/regl/ReglElements.ts
Labels: PR: reviewed-changes-requested, bug

#443 fix(layer): 图层更新问题
  packages/core/src/services/layer/StyleAttributeService.ts
  stories/Layers/components/polygon.tsx
Labels: PR: reviewed-changes-requested, bug

#444 fix: update docs
  docs/api/scene.en.md
  docs/api/scene.zh.md
Labels: PR: unreviewed, bug

#445 Fix map size
  docs/api/scene.en.md
  docs/api/scene.zh.md
  packages/core/src/services/interaction/InteractionService.ts
  packages/core/src/services/interaction/PickingService.ts
  packages/core/src/services/renderer/IRendererService.ts
  packages/core/src/services/scene/SceneService.ts
  packages/l7/src/version.ts
  packages/renderer/src/regl/index.ts
  stories/Layers/components/AnimatePoint.tsx
  stories/Layers/components/PointImage.tsx
  stories/Layers/components/polygon.tsx
Labels: PR: unreviewed

#446 fix: resize
  packages/core/src/services/scene/SceneService.ts
Labels: PR: reviewed-changes-requested, bug

#447 Fix sync
  package.json
  packages/boundary/package.json
  packages/component/package.json
  packages/core/package.json
  packages/core/src/services/interaction/PickingService.ts
  packages/draw/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/maps/package.json
  packages/react/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-changes-requested

#449 fix(maps): mapbox drag rotate
  packages/maps/src/mapbox/map.ts
Labels: PR: reviewed-changes-requested, bug

#455 fix(scene): hasImage未返回有效值
  packages/scene/src/index.ts
Labels: PR: reviewed-changes-requested, bug
