Repository antvis/L7, pull requests merged in 2022-11, with the labels that each got.

#1452 Fix draw
  dev-demos/bugs/point/demos/pointstroke.tsx
  dev-demos/bugs/point/demos/pointupdate.tsx
  dev-demos/bugs/point/demos/text.tsx
  dev-demos/bugs/point/stroke.md
  dev-demos/bugs/point/text.md
  dev-demos/bugs/point/update.md
  dev-demos/bugs/polygon/demos/polygon.tsx
  dev-demos/bugs/polygon/polygon.md
  dev-demos/draw/demo/draw.tsx
  dev-demos/draw/index.md
  dev-demos/features/line/demos/linedash.tsx
  package.json
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/layer/LayerService.ts
  packages/core/src/services/layer/StyleAttributeService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/plugins/DataMappingPlugin.ts
  packages/layers/src/plugins/DataSourcePlugin.ts
  packages/layers/src/plugins/FeatureScalePlugin.ts
  packages/layers/src/plugins/LayerModelPlugin.ts
  packages/layers/src/plugins/UpdateModelPlugin.ts
  packages/layers/src/point/models/fill.ts
  packages/layers/src/point/models/text.ts
  packages/layers/src/polygon/models/fill.ts
  packages/source/src/source.ts
  packages/source/src/utils/tile/getRasterTile.ts
Labels: PR: unreviewed

#1453 chore: 更新beta 版本
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed

#1462 Feat tile
  dev-demos/draw/demo/draw.tsx
  dev-demos/features/tile/raster/satellite.tsx
  dev-demos/tile/Sentinel-2.md
  dev-demos/tile/citytile.md
  dev-demos/tile/district/Sentinel-2.tsx
  dev-demos/tile/district/chinamap.tsx
  dev-demos/tile/district/citytile.tsx
  dev-demos/tile/district/farmland.tsx
  dev-demos/tile/district/geojson-vt.tsx
  dev-demos/tile/district/rasterData.tsx
  dev-demos/tile/district/worldmap.tsx
  dev-demos/tile/farmland.md
  packages/core/src/services/config/ConfigService.ts
  packages/core/src/services/interaction/PickingService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/polygon/models/fill.ts
  packages/layers/src/tile/service/TileLayerService.ts
  packages/layers/src/tile/service/TilePickService.ts
  packages/layers/src/tile/tileFactory/Tile.ts
  packages/layers/src/tile/tileFactory/VectorTile.ts
  packages/layers/src/tile/tileFactory/util.ts
  packages/layers/src/tile/tileLayer/BaseLayer.ts
  packages/source/src/index.ts
  packages/source/src/parser/geojson.ts
  packages/source/src/parser/mvt.ts
  packages/source/src/source/baseSource.ts
  packages/source/src/source/index.ts
  packages/source/src/source/interface.ts
  packages/source/src/source/vector.ts
  packages/utils/src/tileset-manager/tile.ts
  packages/utils/src/tileset-manager/tileset-manager.ts
Labels: PR: unreviewed

#1460 docs: 修正PolygonLayer图层shape属性文档中有歧义的数据映射描述
  dev-demos/layer/control/position.tsx
  packages/site/docs/api/polygon_layer/polygonlayer.zh.md
Labels: PR: reviewed-approved, documentation

#1464 chore: 升级瓦片渲染方式
  dev-demos/features/marker/demos/marker.tsx
  dev-demos/features/rasterLayer/demos/rasterNDVI.tsx
  dev-demos/features/rasterLayer/demos/rasterRgb3.tsx
  dev-demos/layer/control/fullscreen.tsx
  dev-demos/layer/control/hide.tsx
  dev-demos/layer/control/logo.tsx
  dev-demos/layer/control/position.tsx
  dev-demos/layer/control/remove.tsx
  dev-demos/layer/control/setOptions.tsx
  dev-demos/layer/control/zoom.tsx
  dev-demos/layer/popup/layerPopup.tsx
  dev-demos/layer/popup/popup.tsx
  dev-demos/layer/scene/boxSelect.tsx
  dev-demos/raster/432.md
  dev-demos/raster/demos/rasterData.tsx
  dev-demos/raster/demos/rasterFile.tsx
  dev-demos/raster/demos/rasterFile2.tsx
  dev-demos/raster/demos/rasterNDVI.tsx
  dev-demos/raster/demos/rasterRgb.tsx
  dev-demos/raster/demos/rasterRgb2.tsx
  dev-demos/raster/demos/rasterRgb3.tsx
  dev-demos/raster/lc_08/432.tsx
  dev-demos/raster/lc_08/NDVI.tsx
  dev-demos/raster/ndvi.md
  dev-demos/raster/raster.md
  dev-demos/raster/rasterFile.md
  dev-demos/raster/rasterFile2.md
  dev-demos/raster/rasterNDVI.md
  dev-demos/raster/rasterRgb.md
  dev-demos/raster/rasterRgb2.md
  dev-demos/raster/rasterRgb3.md
  package.json
  packages/layers/src/raster/models/rasterRgb.ts
  packages/source/src/interface.ts
  packages/source/src/utils/bandOperation/bands.ts
  packages/source/src/utils/bandOperation/operationSchema.ts
Labels: PR: unreviewed, ignore-for-release

#1466 fix: 修复部分机型 GPU 计算精度问题导致的polygonLayer渲染花纹出错问题
  packages/layers/src/polygon/shaders/extrude/polygon_extrude_frag.glsl
  packages/layers/src/polygon/shaders/extrude/polygon_extrude_picklight_frag.glsl
  packages/layers/src/polygon/shaders/extrude/polygon_extrudetex_frag.glsl
Labels: bugfix

#1468 docs: update website docs
  packages/site/docs/api/raster/source.zh.md
  packages/site/docs/api/tile/geojsonvt_tile_layer.en.md
  packages/site/docs/api/tile/geojsonvt_tile_layer.zh.md
  packages/site/docs/api/tile/options.zh.md
  packages/site/docs/api/tile/raster_tile_layer.en.md
  packages/site/docs/api/tile/raster_tile_layer.zh.md
  packages/site/docs/api/tile/source.en.md
  packages/site/docs/api/tile/source.zh.md
  packages/site/docs/api/tile/style.zh.md
  packages/site/docs/api/tile/tile_layer.en.md
  packages/site/docs/api/tile/tile_layer.zh.md
  packages/site/docs/api/tile/vector_tile_layer.en.md
  packages/site/docs/api/tile/vector_tile_layer.zh.md
  packages/site/docs/tutorial/tile/rasterTile.zh.md
  packages/site/docs/tutorial/tile/vectorTile.zh.md
  packages/source/src/utils/bandOperation/math.ts
Labels: PR: unreviewed, documentation

#1465 feat: 图层气泡 LayerPopup props 中的 config => items，formatField 和 formatVa…
  dev-demos/layer/popup/layerPopup.tsx
  packages/component/__tests__/layerPopup.spec.ts
  packages/component/src/popup/layerPopup.ts
  packages/site/docs/api/component/popup/layerPopup.zh.md
  packages/site/examples/component/popup/demo/layerPopup.ts
Labels: PR: partially-approved, feature

#1470 feat: Layerpoup
  packages/component/src/popup/layerPopup.ts
Labels: PR: partially-approved, feature

#1450 fix: 修复 Components 中引用 l7-utils 路径问题
  packages/component/src/control/baseControl/buttonControl.ts
  packages/component/src/control/zoom.ts
  packages/utils/src/index.ts
Labels: PR: reviewed-approved, bugfix

#1471 fix: fix MaskTile failed
  packages/layers/src/tile/tileFactory/MaskTile.ts
Labels: PR: reviewed-approved, bugfix

#1476 chore: 升级版本
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1479 fix: 修复通过 click 方式创建 Popup 同时触发 closeOnClick 问题
  packages/component/src/popup/popup.ts
Labels: PR: reviewed-approved, bugfix

#1478 Publish
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/layers/src/core/BaseLayer.ts
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved

#1480 fix: 修复地图销毁后，更新 LayerPopup 配置报错问题
  packages/component/src/popup/popup.ts
Labels: PR: reviewed-approved, bugfix

#1482 Publish
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved

#1483 Publish
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/maps/src/amap2/map.ts
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/.dumirc.ts
  packages/site/docs/tutorial/map/amap.zh.md
  packages/site/docs/tutorial/map/tianditu.en.md
  packages/site/docs/tutorial/map/tianditu.zh.md
  packages/site/examples/raster/basic/delete/dem.js
  packages/site/examples/raster/basic/delete/ndvi.js
  packages/site/examples/raster/basic/index.zh.md
  packages/site/examples/raster/data_raster/demo/432.ts
  packages/site/examples/raster/data_raster/demo/543.ts
  packages/site/examples/raster/data_raster/demo/NDBI.ts
  packages/site/examples/raster/data_raster/demo/NDVI.ts
  packages/site/examples/raster/data_raster/demo/NDWI.ts
  packages/site/examples/raster/data_raster/demo/meta.json
  packages/site/examples/raster/data_raster/demo/multfile.ts
  packages/site/examples/raster/data_raster/demo/rgb.ts
  packages/site/examples/raster/data_raster/index.en.md
  packages/site/examples/raster/data_raster/index.zh.md
  packages/site/examples/tile/basemap/demo/amap-normal.js
  packages/site/examples/tile/basemap/demo/amap-satellite.js
  packages/site/examples/tile/basemap/demo/amap-satelliteMask.js
  packages/site/examples/tile/basemap/demo/dem.ts
  packages/site/examples/tile/basemap/demo/mask.ts
  packages/site/examples/tile/basemap/demo/meta.json
  packages/site/examples/tile/basemap/demo/normal.ts
  packages/site/examples/tile/basemap/demo/raster.ts
  packages/site/examples/tile/basemap/demo/terrain.ts
  packages/site/examples/tile/basemap/demo/wms.ts
  packages/site/examples/tile/basemap/demo/wmts.ts
  packages/site/examples/tile/basemap/index.en.md
  packages/site/examples/tile/basemap/index.zh.md
  packages/site/examples/tile/basic/demo/hillshade.ts
  packages/site/examples/tile/basic/demo/wmts.ts
  packages/site/examples/tile/raster/demo/meta.json
  packages/site/examples/tile/raster/demo/terrain.ts
  packages/site/examples/tile/raster/demo/tianditu-normal.js
  packages/site/examples/tile/raster/demo/tianditu-satellite.js
  packages/site/examples/tile/raster/index.zh.md
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed

#1484 Publish
  packages/site/.dumirc.ts
  packages/site/examples/raster/data_raster/demo/meta.json
  packages/site/package.json
  scripts/site_asyncfile.sh
Labels: PR: unreviewed

#1487 Publish
  dev-demos/bugs/line/demo/setdata.tsx
  dev-demos/bugs/line/setdata.md
  dev-demos/draw/demo/drawline.tsx
  dev-demos/draw/line.md
  dev-demos/features/heatmap/demos/heatmap.tsx
  dev-demos/features/point/pointImage.md
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/core/src/services/asset/IconService.ts
  packages/core/src/services/interaction/PickingService.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/layer/LayerService.ts
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/line/index.ts
  packages/layers/src/line/models/line.ts
  packages/layers/src/line/models/simpleTileLine.ts
  packages/layers/src/line/models/wall.ts
  packages/layers/src/tile/tileFactory/VectorTile.ts
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/scene/src/index.ts
  packages/site/.dumirc.ts
  packages/site/examples/tile/vector/demo/meta.json
  packages/site/examples/tile/vector/demo/point.ts
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed

#1488 Publish
  dev-demos/features/canvasLayer/custom.md
  dev-demos/features/point/demos/simple.tsx
  dev-demos/tile/Vector/demos/worldmap.tsx
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/layers/src/line/models/line.ts
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/.dumirc.ts
  packages/site/package.json
  packages/source/package.json
  packages/source/src/interface.ts
  packages/source/src/parser/geojsonvt.ts
  packages/source/src/parser/mvt.ts
  packages/source/src/source/baseSource.ts
  packages/source/src/source/geojsonvt.ts
  packages/source/src/source/index.ts
  packages/source/src/source/interface.ts
  packages/source/src/source/vector.ts
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed

#1489 fix: layer service clear
  dev-demos/features/point/demos/simple.tsx
  dev-demos/gallery/scale/quantile.tsx
  dev-demos/gallery/scale/quantize.tsx
  dev-demos/tile/Vector/demos/worldmap.tsx
  package.json
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/layer/LayerService.ts
  packages/core/src/services/scene/SceneService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/line/models/line.ts
  packages/layers/src/plugins/DataMappingPlugin.ts
  packages/maps/src/amap2/map.ts
  packages/maps/src/utils/amap/AMapBaseService.ts
  packages/site/.dumirc.ts
  packages/site/examples/tile/vector/demo/simpleLine.ts
  packages/site/examples/tile/vector/demo/worldmap.ts
Labels: PR: unreviewed, bugfix

#1490 chore: 版本号
  dev-demos/gallery/scale/quantile.tsx
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed, ignore-for-release

#1491 feat: 官网内容优化、高德2 Z 参数透传
  dev-demos/features/line/demos/simpleline.tsx
  dev-demos/gallery/scale/index.md
  packages/layers/src/plugins/DataMappingPlugin.ts
  packages/maps/src/amap2/map.ts
  packages/site/.dumirc.ts
  packages/site/docs/api/component/component.zh.md
  packages/site/docs/api/experiment/earth/flyline.zh.md
  packages/site/docs/api/experiment/earth/point.zh.md
  packages/site/docs/api/experiment/pass.zh.md
  packages/site/docs/api/line_layer/linelayer.zh.md
  packages/site/docs/api/mask_layer/masklayer.en.md
  packages/site/docs/api/mask_layer/masklayer.zh.md
  packages/site/docs/api/mask_layer/options.en.md
  packages/site/docs/api/mask_layer/options.zh.md
  packages/site/docs/api/mask_layer/source.en.md
  packages/site/docs/api/mask_layer/source.zh.md
  packages/site/docs/api/other/mask.en.md
  packages/site/docs/api/other/mask.zh.md
  packages/site/docs/common/layer/layer_encode.md
  packages/site/docs/common/layer/layer_event.md
  packages/site/docs/common/layer/options.md
  packages/site/docs/common/layer/scale.md
  packages/site/docs/tutorial/map/offline.en.md
  packages/site/docs/tutorial/map/tianditu.zh.md
  packages/site/docs/tutorial/mask/init.en.md
  packages/site/docs/tutorial/mask/init.zh.md
  packages/site/docs/tutorial/mask/option.en.md
  packages/site/docs/tutorial/mask/option.zh.md
  packages/site/docs/tutorial/mask/tile.en.md
  packages/site/docs/tutorial/mask/tile.zh.md
  packages/site/examples/gallery/animate/demo/grid.js
  packages/site/examples/geometry/geometry/demo/snow.js
Labels: PR: unreviewed, feature

#1495 fix: 修复 Popup 闭包问题
  packages/component/src/popup/layerPopup.ts
  packages/component/src/popup/popup.ts
  packages/site/docs/api/component/popup/popup.zh.md
Labels: PR: reviewed-approved, bugfix

#1494 chore: 更新版本 2.11.0
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1497 chore: publish
  .umirc.ts
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/.dumirc.ts
  packages/site/docs/api/raster_layer/common/style.md
  packages/site/docs/api/raster_layer/options.en.md
  packages/site/docs/api/raster_layer/options.zh.md
  packages/site/docs/api/raster_layer/raster_band_calc.zh.md
  packages/site/docs/api/raster_layer/raster_layer.en.md
  packages/site/docs/api/raster_layer/raster_multi_band.zh.md
  packages/site/docs/api/raster_layer/raster_muti_band.en.md
  packages/site/docs/api/raster_layer/raster_rgb.en.md
  packages/site/docs/api/raster_layer/raster_rgb.zh.md
  packages/site/docs/api/raster_layer/raster_single_band.en.md
  packages/site/docs/api/raster_layer/raster_single_band.zh.md
  packages/site/docs/api/raster_layer/source.en.md
  packages/site/docs/api/raster_layer/source.zh.md
  packages/site/docs/api/raster_layer/style.en.md
  packages/site/docs/api/source/raster/raster_band_calc.md
  packages/site/docs/api/source/raster/raster_rgb.md
  packages/site/docs/api/source/raster/raster_single.md
  packages/site/docs/api/source/raster_rgb.en.md
  packages/site/docs/api/source/raster_rgb.zh.md
  packages/site/docs/api/tile/common/options.zh.md
  packages/site/docs/api/tile/common/style.zh.md
  packages/site/docs/api/tile/geojsonvt_tile_layer.zh.md
  packages/site/docs/api/tile/options.zh.md
  packages/site/docs/api/tile/raster_tile_layer.zh.md
  packages/site/docs/api/tile/style.en.md
  packages/site/docs/api/tile/vector_tile_layer.zh.md
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
  scripts/site.sh
Labels: PR: unreviewed, ignore-for-release

#1500 docs: 更新 README 及新官网链接
  .github/CONTRIBUTING.md
  .github/CONTRIBUTING_ENGLISH.md
  README.en-US.md
  README.md
  packages/component/src/control/logo.ts
  packages/l7/README.en-US.md
  packages/l7/README.md
  packages/site/.dumirc.ts
  packages/site/docs/api/component/control/logo.zh.md
  packages/site/docs/common/district/choropleth.zh.md
  packages/site/package.json
Labels: PR: reviewed-approved, documentation

#1499 Publish
  packages/site/.dumirc.ts
  packages/site/docs/CNAME
  packages/site/docs/tutorial/l7.zh.md
  packages/site/package.json
  packages/site/public_site/CNAME
  packages/site/public_site/index.html
Labels: PR: unreviewed

#1498 fix: 修复 Popup 部分问题
  dev-demos/component/popup/layerPopup.tsx
  packages/component/src/css/index.css
  packages/component/src/css/popup.less
  packages/component/src/popup/popup.ts
Labels: PR: reviewed-approved, bugfix

#1430 feat: 瓦片服务请求中添加 getURLFromTemplate、transformResponse 修改默认请求配置
  packages/core/src/services/source/ISourceService.ts
  packages/source/src/utils/tile/getRasterTile.ts
  packages/utils/src/ajax.ts
Labels: PR: reviewed-approved, feature

#1507 docs: 修复官网快速开始跳转错误问题
  packages/site/.dumirc.ts
Labels: PR: reviewed-approved, documentation

#1508 chore: update version v2.11.1 -> v2.11.2
  lerna.json
  packages/component/package.json
  packages/component/src/control/logo.ts
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/docs/api/tile/geojsonvt_tile_layer.zh.md
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1504 feat: LayerPopup 新增自定义内容能力
  dev-demos/component/popup/layerPopup.tsx
  dev-demos/component/popup/popup.tsx
  package.json
  packages/component/src/popup/layerPopup.ts
  packages/component/src/popup/popup.ts
  packages/core/src/services/component/IPopupService.ts
  packages/site/docs/api/component/control/exportImage.zh.md
  packages/site/docs/api/component/control/fullscreen.zh.md
  packages/site/docs/api/component/control/layerSwitch.zh.md
  packages/site/docs/api/component/control/zoom.zh.md
  packages/site/docs/api/component/popup/layerPopup.zh.md
  packages/site/docs/api/component/popup/popup.zh.md
  packages/site/docs/common/control/btn-api.md
  packages/site/docs/common/control/popper-api.md
  packages/site/examples/component/popup/demo/customContent.ts
  packages/site/examples/component/popup/demo/meta.json
  packages/site/examples/point/chart/demo/bar.js
  packages/site/examples/point/chart/demo/chart.js
  packages/utils/src/dom.ts
Labels: PR: reviewed-approved, feature

#1514 Publish
  dev-demos/bugs/point/demos/pointstroke.tsx
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/layers/src/plugins/PixelPickingPlugin.ts
  packages/layers/src/tile/tileLayer/BaseLayer.ts
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/docs/tutorial/l7.zh.md
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed

#1515 Feat map
  dev-demos/bugs/point/demos/image.tsx
  dev-demos/bugs/point/image.md
  dev-demos/bugs/scene/demos/multiMap.tsx
  dev-demos/bugs/scene/multiMap.md
  dev-demos/features/threejs/amap2.md
  dev-demos/features/threejs/map.md
  dev-demos/features/tile/raster/satellite.tsx
  package.json
  packages/layers/src/point/index.ts
  packages/layers/src/point/models/image.ts
  packages/layers/src/point/models/text.ts
  packages/map/src/geo/mercator.ts
  packages/map/src/index.ts
  packages/maps/src/amap/map.ts
  packages/maps/src/amap2/map.ts
  packages/maps/src/map/map.ts
  packages/source/src/utils/tile/getCustomData.ts
  packages/three/src/core/threeRenderService.ts
  vercel.json
Labels: PR: unreviewed
