Repository antvis/L7, pull requests merged in 2022-08, with the labels that each got.

#1266 chore: update version 2.9.18 -> 2.9.19
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
  packages/utils/src/workers/commonFeatureFunc.ts
  packages/utils/src/workers/interface.ts
  packages/utils/src/workers/lineModel.ts
  packages/utils/src/workers/pointFillModel.ts
  packages/utils/src/workers/polygonFillModel.ts
  packages/utils/src/workers/triangulation.ts
Labels: PR: unreviewed, ignore-for-release

#1269 fix: fix simple line err
  .storybook/preview.ts
  packages/layers/src/core/triangulation.ts
  packages/layers/src/utils/extrude_polyline.ts
  stories/Map/components/gridTile.tsx
Labels: PR: reviewed-approved, bugfix

#1270 chore: update version 2.9.19 -> 2.9.20
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1272 chore: update version 2.9.20 -> 2.9.21
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1274 feat: export BaseModel to support CustomLayer
  .storybook/preview.ts
  packages/core/package.json
  packages/layers/package.json
  packages/layers/src/index.ts
  packages/map/package.json
  packages/renderer/package.json
  stories/template/components/CustomPointLayer.ts
  stories/template/components/point.tsx
  stories/template/map.stories.tsx
Labels: PR: reviewed-approved, feature

#1275 chore: remove lib
  packages/core/package.json
  packages/renderer/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1276 chore: update version 2.9.21 -> 2.9.22
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1277 chore: 修改 tslint 依赖配置
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
  tslint.prod.json
Labels: PR: reviewed-approved, ignore-for-release

#1278 chore: 工程配置优化
  .github/CONTRIBUTING.md
  .github/workflows/test.yml
  .umirc.ts
  dev-demos/bugs/index.md
  dev-demos/features/point/circle.tsx
  dev-demos/features/point/index.md
  jest.config.js
  package.json
  packages/source/__tests__/source.spec.ts
  packages/source/__tests__/utils/statistics.spec.ts
Labels: PR: reviewed-approved, ignore-for-release

#1282 feat: 优化图片的显示效果
  dev-demos/features/point/image.md
  dev-demos/features/point/image.tsx
  dev-demos/features/point/tile.md
  dev-demos/features/point/tile.tsx
  packages/layers/src/core/interface.ts
  packages/layers/src/image/models/image.ts
  packages/renderer/package.json
Labels: PR: reviewed-approved, feature

#1281 Chore test preCommit 增加测试用例校验
  .github/workflows/lint.yml
  .github/workflows/preview.yml
  .github/workflows/test.yml
  dev-demos/features/point/circle.tsx
  dev-demos/features/point/image.tsx
  dev-demos/features/point/index.md
  dev-demos/features/point/pointCircle.md
  dev-demos/features/point/pointFillImage.md
  dev-demos/features/point/pointImage.md
  dev-demos/features/point/pointWave.md
  dev-demos/features/point/tile.tsx
  package.json
  packages/renderer/package.json
Labels: PR: reviewed-approved

#1284 chore: lint check
  .eslintrc
  .eslintrc.js
  .github/workflows/build_test.yml
  .github/workflows/test.yml
  package.json
  packages/core/src/services/camera/Camera.ts
  packages/core/src/services/interaction/PickingService.ts
  packages/core/src/services/shader/ShaderModuleService.ts
  packages/layers/src/plugins/LayerAnimateStylePlugin.ts
  packages/layers/src/plugins/LightingPlugin.ts
  packages/layers/src/plugins/RegisterStyleAttributePlugin.ts
  packages/layers/src/plugins/UpdateModelPlugin.ts
  packages/layers/src/plugins/UpdateStyleAttributePlugin.ts
  packages/layers/src/point/models/fill.ts
  packages/layers/src/point/models/fillmage.ts
  packages/layers/src/point/models/radar.ts
  packages/layers/src/point/models/tile.ts
  packages/layers/src/tile/utils.ts
  packages/map/src/geo/lng_lat_bounds.ts
  packages/map/src/handler/events/render_event.ts
  packages/map/src/handler/mouse/mouse_handler.ts
  packages/map/src/handler/tap/single_tap_recognizer.ts
  packages/map/src/handler/tap/tap_drag_zoom.ts
  packages/map/src/handler/tap/tap_recognizer.ts
  packages/map/src/handler/touch/touch_pitch.ts
  packages/map/src/handler/touch/touch_rotate.ts
  packages/map/src/handler/touch/touch_zoom.ts
  packages/map/src/handler/touch/two_touch.ts
  packages/site/examples/line/path/demo/arrow.js
  packages/three/package.json
  packages/utils/src/geo.ts
  packages/utils/src/mini-adapter/Event.ts
  packages/utils/src/mini-adapter/WebGL.ts
  packages/utils/src/mini-adapter/XMLHttpRequest.ts
  packages/utils/src/mini-adapter/atob.ts
  packages/utils/src/mini-adapter/document.ts
  packages/utils/src/mini-adapter/index.ts
  packages/utils/src/mini-adapter/location.ts
  packages/utils/src/mini-adapter/performance.ts
  tsconfig.json
Labels: PR: reviewed-approved, ignore-for-release

#1283 feat: 新增枚举类型的色带
  dev-demos/features/point/linearline.md
  dev-demos/features/point/linearline.tsx
  packages/utils/src/color.ts
Labels: PR: reviewed-approved, feature

#1285 Chore: 修复部分lint 警告，pre-commit 移除build命令
  .eslintignore
  .eslintrc.js
  dev-demos/features/point/image.tsx
  dev-demos/features/point/linearline.tsx
  dev-demos/features/point/tile.tsx
  package.json
  packages/component/src/control/logo.ts
  packages/core/src/utils/math.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/core/BaseModel.ts
  packages/layers/src/core/interface.ts
  packages/layers/src/core/triangulation.ts
  packages/layers/src/heatmap/triangulation.ts
  packages/layers/src/plugins/DataMappingPlugin.ts
  packages/layers/src/plugins/DataSourcePlugin.ts
  packages/layers/src/plugins/FeatureScalePlugin.ts
  packages/layers/src/plugins/LayerModelPlugin.ts
  packages/layers/src/plugins/LayerStylePlugin.ts
  packages/layers/src/raster/raster.ts
  packages/layers/src/tile/tmsTileLayer.ts
  packages/layers/src/utils/blend.ts
  packages/layers/src/utils/dataMappingStyle.ts
  packages/layers/src/utils/multiPassRender.ts
  packages/layers/src/utils/polylineNormal.ts
  packages/layers/src/utils/symbol-layout.ts
  packages/map/src/geo/lng_lat.ts
  packages/map/src/geo/transform.ts
  packages/map/src/handler/blockable_map_event.ts
  packages/maps/src/amap/map.ts
  packages/maps/src/amap2/map.ts
  packages/maps/src/earth/Viewport.ts
  packages/maps/src/mapbox/map.ts
  packages/renderer/src/regl/ReglFramebuffer.ts
  packages/renderer/src/regl/ReglModel.ts
  packages/source/src/transform/cluster.ts
  packages/source/src/transform/hexagon.ts
  packages/three/src/core/baseLayer.ts
  packages/three/src/core/threeRenderService.ts
Labels: PR: reviewed-approved

#1286 feat: add test case
  jest.config.js
  packages/core/__tests__/core.spec.ts
  packages/layers/src/Geometry/__tests__/layer.spec.ts
  packages/layers/src/canvas/__tests__/layer.spec.ts
  packages/layers/src/citybuliding/__tests__/layer.spec.ts
  packages/layers/src/citybuliding/building.ts
  packages/layers/src/core/__tests__/layer.spec.ts
  packages/layers/src/heatmap/__tests__/layer.spec.ts
  packages/layers/src/image/__tests__/imageLayer.spec.ts
  packages/layers/src/line/__tests__/lineLayer.spec.ts
  packages/layers/src/mask/__tests__/mask.spec.ts
  packages/layers/src/mask/__tests__/polygonTriangulation.spec.ts
  packages/layers/src/point/__tests__/layer.spec.ts
  packages/layers/src/wind/__tests__/wind.spec.ts
  packages/scene/__tests__/index.spec.ts
  packages/scene/__tests__/l7_map.spec.ts
Labels: PR: reviewed-approved, feature

#1288 feat: 修改 simple line 的网格构建和渲染方式
  dev-demos/features/point/simpleline.md
  dev-demos/features/point/simpleline.tsx
  jest.config.js
  packages/core/src/services/layer/IStyleAttributeService.ts
  packages/core/src/services/layer/StyleAttributeService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/core/triangulation.ts
  packages/layers/src/line/shaders/simple/simpleline_vert.glsl
  packages/renderer/src/regl/ReglModel.ts
  packages/scene/__tests__/l7_map.spec.ts
  packages/site/examples/gallery/animate/demo/grid.js
  stories/Map/components/gridTile.tsx
Labels: PR: reviewed-approved, feature

#1287 Chore: lint warn 移除未使用的import
  package.json
  packages/component/src/popup.ts
  packages/core/src/services/asset/FontService.ts
  packages/core/src/services/asset/IconService.ts
  packages/core/src/services/camera/CameraService.ts
  packages/core/src/services/camera/Landmark.ts
  packages/core/src/services/component/IMarkerService.ts
  packages/core/src/services/component/IPopupService.ts
  packages/core/src/services/component/MarkerService.ts
  packages/core/src/services/config/ConfigService.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/layer/IStyleAttributeService.ts
  packages/core/src/services/layer/LayerService.ts
  packages/core/src/services/layer/StyleAttribute.ts
  packages/core/src/services/layer/StyleAttributeService.ts
  packages/core/src/services/renderer/IRendererService.ts
  packages/core/src/services/renderer/passes/BaseNormalPass.ts
  packages/core/src/services/renderer/passes/PixelPickingPass.ts
  packages/core/src/services/scene/SceneService.ts
  packages/core/src/utils/__tests__/math.spec.ts
  packages/layers/src/Geometry/models/billboard.ts
  packages/layers/src/Geometry/models/sprite.ts
  packages/layers/src/canvas/models/canvas.ts
  packages/layers/src/earth/models/base.ts
  packages/layers/src/heatmap/models/heatmap.ts
  packages/layers/src/line/models/great_circle.ts
  packages/layers/src/line/models/line.ts
  packages/layers/src/line/models/tile.ts
  packages/layers/src/point/__tests__/layer.spec.ts
  packages/layers/src/polygon/models/tile.ts
  packages/layers/src/raster/buffers/triangulation.ts
  packages/layers/src/raster/models/raster.ts
  packages/layers/src/tile/tileFactory/base.ts
  packages/layers/src/tile/tileFactory/line.ts
  packages/layers/src/tile/tileFactory/point.ts
  packages/layers/src/tile/tileFactory/polygon.ts
  packages/layers/src/tile/tileFactory/raster.ts
  packages/layers/src/tile/tileLayer/baseTileLayer.ts
  packages/layers/src/wind/models/wind.ts
  packages/map/src/camera.ts
  packages/map/src/handler/events/index.ts
  packages/map/src/handler/mouse/mousepan_handler.ts
  packages/map/src/handler/touch/touch_rotate.ts
  packages/map/src/handler/touch/touch_zoom.ts
  packages/utils/src/dom.ts
Labels: PR: reviewed-approved

#1294 feat: 适量图层支持透传 transfrom
  dev-demos/features/point/tile.md
  dev-demos/features/tile/rastertile.md
  dev-demos/features/tile/rastertile.tsx
  dev-demos/features/tile/vectortile.md
  dev-demos/features/tile/vectortile.tsx
  packages/core/src/services/layer/ILayerService.ts
  packages/layers/src/tile/manager/tileLayerManager.ts
  packages/layers/src/tile/models/tileModel.ts
  packages/layers/src/tile/tileFactory/base.ts
  packages/layers/src/tile/tileLayer/baseTileLayer.ts
  packages/source/src/source.ts
Labels: PR: reviewed-approved, feature

#1291 test： 测试用例支持 new scene 对象
  jest.config.js
  jest/setupTests.ts
  packages/component/package.json
  packages/component/src/control/__tests__/BaseControl.spec.ts
  packages/component/src/control/__tests__/zoom.spec.ts
  packages/core/src/services/config/IConfigService.ts
  packages/core/src/services/renderer/IRendererService.ts
  packages/core/src/services/scene/SceneService.ts
  packages/map/src/index.ts
  packages/map/src/map.ts
  packages/maps/src/map/map.ts
  packages/maps/src/utils.ts
  packages/renderer/package.json
  packages/renderer/src/regl/__tests__/attribute.spec.ts
  packages/renderer/src/regl/__tests__/elements.spec.ts
  packages/renderer/src/regl/__tests__/framebuffer.spec.ts
  packages/renderer/src/regl/__tests__/model.draw.spec.ts
  packages/renderer/src/regl/__tests__/model.spec.ts
  packages/renderer/src/regl/__tests__/model.uniform.spec.ts
  packages/renderer/src/regl/__tests__/renderer.spec.ts
  packages/renderer/src/regl/__tests__/texture.spec.ts
  packages/renderer/src/regl/index.ts
  packages/scene/__tests__/index.spec.ts
  packages/scene/package.json
  packages/scene/src/index.ts
  packages/test-utils/.fatherrc.ts
  packages/test-utils/.gitignore
  packages/test-utils/README.md
  packages/test-utils/package.json
  packages/test-utils/src/check-pixels.ts
  packages/test-utils/src/create-context.ts
  packages/test-utils/src/default-precision.ts
  packages/test-utils/src/index.ts
  packages/test-utils/src/test-scene.ts
  packages/test-utils/tsconfig.build.json
  tsconfig.json
  typings.d.ts
Labels: PR: reviewed-approved

#1293 feat: 提供线图层偏移点位计算的通用方法
  dev-demos/features/point/arcline.md
  dev-demos/features/point/arcline.tsx
  dev-demos/features/point/greatcircleline.md
  dev-demos/features/point/greatcircleline.tsx
  dev-demos/features/point/line.md
  dev-demos/features/point/line.tsx
  dev-demos/features/tile/rastertile.tsx
  package.json
  packages/layers/src/line/shaders/line_arc_vert.glsl
  packages/utils/__tests__/lineAtOffset.spec.ts
  packages/utils/src/geo.ts
  packages/utils/src/index.ts
  packages/utils/src/interface/map.ts
  packages/utils/src/lineAtOffset/arc.ts
  packages/utils/src/lineAtOffset/greatCircle.ts
  packages/utils/src/lineAtOffset/index.ts
  packages/utils/src/lineAtOffset/interface.ts
  packages/utils/src/lineAtOffset/line.ts
Labels: PR: reviewed-approved, feature

#1296 chore: update version 2.9.23 -> 2.9.24
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1265 feat: 兼容 禁止多种API加载方式混用问题
  packages/maps/src/amap/map.ts
  packages/maps/src/amap2/map.ts
Labels: PR: partially-approved, feature

#1301 fix: 修复加载高德地图判断加载导致的缓存问题
  packages/maps/src/amap/map.ts
  packages/maps/src/amap2/map.ts
Labels: PR: reviewed-approved, bugfix

#1302 feat: 矢量图层支持 geojson-vt
  dev-demos/features/tile/geojson-vt.md
  dev-demos/features/tile/geojson-vt.tsx
  dev-demos/features/tile/vectortile.tsx
  packages/core/src/services/source/ISourceService.ts
  packages/layers/src/line/index.ts
  packages/layers/src/point/index.ts
  packages/layers/src/polygon/index.ts
  packages/layers/src/raster/index.ts
  packages/layers/src/tile/manager/tileLayerManager.ts
  packages/layers/src/tile/utils.ts
  packages/source/package.json
  packages/source/src/index.ts
  packages/source/src/interface.ts
  packages/source/src/parser/geojsonvt.ts
  packages/source/src/parser/mvt.ts
  packages/source/src/parser/raster-tile.ts
  packages/source/src/source.ts
Labels: PR: reviewed-approved, feature

#1304 docs: scale demo & IE 兼容
  .eslintrc.js
  .umirc.ts
  dev-demos/gallery/index.md
  dev-demos/gallery/scale/cat.md
  dev-demos/gallery/scale/cat.tsx
  dev-demos/gallery/scale/diverging.md
  dev-demos/gallery/scale/diverging.tsx
  dev-demos/gallery/scale/index.md
  dev-demos/gallery/scale/linear.md
  dev-demos/gallery/scale/linear.tsx
  dev-demos/gallery/scale/quantile.md
  dev-demos/gallery/scale/quantile.tsx
  dev-demos/gallery/scale/quantize.md
  dev-demos/gallery/scale/quantize.tsx
  dev-demos/gallery/scale/sequential.md
  dev-demos/gallery/scale/sequential.tsx
  dev-demos/gallery/scale/threshold.md
  dev-demos/gallery/scale/threshold.tsx
  dev-demos/gallery/scale/useLine.ts
  package.json
  packages/layers/src/plugins/FeatureScalePlugin.ts
  packages/three/src/core/baseLayer.ts
Labels: PR: reviewed-approved, documentation

#1307 fix: heatmap render error
  dev-demos/features/heatmap/heatmap.md
  dev-demos/features/heatmap/heatmap.tsx
  packages/layers/src/heatmap/models/heatmap.ts
Labels: PR: reviewed-approved, bugfix

#1308 chore: update version 2.9.24 -> 2.9.25
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/layers/src/tile/utils.ts
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1309 test: 新增marker组件测试用例，测试覆盖率0% -> 80%
  dev-demos/features/customLayer/marker-layer.md
  dev-demos/features/customLayer/marker.md
  packages/component/__tests__/marker.spec.tsx
Labels: PR: reviewed-approved

#1312 feat: source 支持 json 下新增 geometry 字段
  packages/core/src/services/source/ISourceService.ts
  packages/source/src/parser/geojson.ts
  packages/source/src/parser/json.ts
Labels: PR: reviewed-approved, feature

#1311 fix: 解决聚合情况下清空图层点数据未清空BUG
  packages/component/src/marker-layer.ts
Labels: PR: reviewed-approved, bugfix

#1315 fix: 修复 feature scale 可能存在的 source 取值问题
  packages/layers/src/plugins/FeatureScalePlugin.ts
  packages/source/src/source.ts
Labels: PR: reviewed-approved, bugfix

#1316 fix: 修复栅格图片瓦片的混合问题
  dev-demos/features/tile/rastertile.tsx
  packages/layers/src/image/models/image.ts
Labels: PR: reviewed-approved, bugfix

#1310 feat: 矢量文本计算优化、性能优化
  dev-demos/features/tile/testTile.md
  dev-demos/features/tile/testTile.tsx
  packages/core/src/services/layer/ILayerService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/index.ts
  packages/layers/src/line/index.ts
  packages/layers/src/mask/index.ts
  packages/layers/src/plugins/DataSourcePlugin.ts
  packages/layers/src/point/index.ts
  packages/layers/src/point/models/index.ts
  packages/layers/src/point/models/tileText.ts
  packages/layers/src/polygon/index.ts
  packages/layers/src/tile/manager/tileLayerManager.ts
  packages/layers/src/tile/models/tileModel.ts
  packages/layers/src/tile/tileFactory/index.ts
  packages/layers/src/tile/tileFactory/test.ts
  packages/layers/src/tile/tileFactory/vectorLayer.ts
  packages/layers/src/tile/tileTest.ts
  packages/layers/src/tile/utils.ts
  packages/source/src/index.ts
  packages/source/src/parser/json.ts
  packages/source/src/parser/testTile.ts
Labels: PR: reviewed-approved, feature

#1314 [chores] Remove unused dependencie
  packages/layers/package.json
Labels: PR: reviewed-approved

#1300 feat: 自定义图层 - marker&markerLayer - 多个marker节点性能优化
  dev-demos/features/customLayer/marker-layer.md
  packages/component/src/marker-layer.ts
  packages/component/src/marker.ts
  packages/core/src/services/component/IMarkerService.ts
Labels: PR: reviewed-approved, feature

#1319 chore: add demo
  dev-demos/features/line/line.md
  dev-demos/features/line/line.tsx
  dev-demos/features/line/linearline.md
  dev-demos/features/line/linearline.tsx
  dev-demos/features/line/lineblur.md
  dev-demos/features/line/lineblur.tsx
Labels: PR: reviewed-approved, ignore-for-release

#1318 chore: update version 2.9.25 -> 2.9.26
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release
