Repository antvis/L7, pull requests merged in 2022-12, with the labels that each got.

#1520 Feat/layer popup
  dev-demos/component/popup/popup.tsx
  packages/component/src/css/index.css
  packages/component/src/css/popup.less
  packages/component/src/popup/popup.ts
Labels: PR: reviewed-approved

#1522 Publish
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed

#1523 Publish
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/layers/src/core/BaseLayer.ts
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed

#1528 docs: 场景 Scene API 补充 addPopup 和 removePopup 方法说明
  package.json
  packages/site/docs/api/scene.zh.md
Labels: PR: unreviewed, documentation

#1532 Publish
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/docs/api/scene.zh.md
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed

#1534 fix: 修复 Popup 中 title 和 content 设置先后问题
  packages/component/src/popup/popup.ts
Labels: PR: reviewed-approved, bugfix

#1537 fix: 修复 isOpen 报错问题
  packages/component/src/marker.ts
  packages/component/src/popup/popup.ts
  packages/core/src/services/component/PopupService.ts
Labels: PR: reviewed-approved, bugfix

#1536 Feat earcut
  .github/workflows/mirror.yml
  dev-demos/bugs/heatmap/demos/map.tsx
  dev-demos/bugs/polygon/demos/polygon.tsx
  dev-demos/bugs/polygon/demos/scale.tsx
  packages/site/examples/tutorial/map/demo/amapInstance.js
  packages/utils/src/workers/triangulation.ts
Labels: PR: unreviewed

#1540 Fix token warn
  packages/core/src/services/config/warnInfo.ts
  packages/maps/src/amap2/map.ts
  packages/maps/src/utils/amap/AMapBaseService.ts
  packages/utils/src/workers/triangulation.ts
Labels: PR: unreviewed

#1547 fix: 修复 shape 更新失效
  dev-demos/features/point/demos/icons.tsx
  packages/layers/src/utils/updateShape.ts
Labels: PR: reviewed-approved, bugfix

#1548 Publish
  lerna.json
  package.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed

#1549 fix: getImage async method
  packages/component/src/control/exportImage.ts
Labels: PR: unreviewed, bugfix

#1550 fix: circle meter size && remove unuse code file
  dev-demos/features/line/demos/line.tsx
  dev-demos/features/line/demos/linearc.tsx
  dev-demos/features/point/circle.md
  dev-demos/features/point/demos/circlemeter.tsx
  dev-demos/features/point/demos/radar.tsx
  dev-demos/features/point/pointFillImage.md
  packages/core/src/shaders/projection.glsl
  packages/layers/src/core/interface.ts
  packages/layers/src/line/models/index.ts
  packages/layers/src/line/models/tile.ts
  packages/layers/src/line/shaders/tile/line_tile_map_vert.glsl
  packages/layers/src/line/shaders/tile/line_tile_vert.glsl
  packages/layers/src/line/shaders/tile/simpleline_map_vert.glsl
  packages/layers/src/line/shaders/tile/simpleline_vert.glsl
  packages/layers/src/point/models/fill.ts
  packages/layers/src/point/models/fillmage.ts
  packages/layers/src/point/models/index.ts
  packages/layers/src/point/models/radar.ts
  packages/layers/src/point/models/tile.ts
  packages/layers/src/point/models/tileText.ts
  packages/layers/src/point/shaders/fill_vert.glsl
  packages/layers/src/point/shaders/image/fillImage_vert.glsl
  packages/layers/src/point/shaders/radar/radar_vert.glsl
  packages/layers/src/point/shaders/text_vert.glsl
  packages/layers/src/point/shaders/tile/fill_tile_frag.glsl
  packages/layers/src/point/shaders/tile/fill_tile_vert.glsl
  packages/layers/src/point/shaders/tile/text_frag.glsl
  packages/layers/src/point/shaders/tile/text_map_frag.glsl
  packages/layers/src/point/shaders/tile/text_map_vert.glsl
  packages/layers/src/point/shaders/tile/text_vert.glsl
  packages/layers/src/polygon/index.ts
  packages/layers/src/polygon/models/index.ts
  packages/layers/src/polygon/models/tile.ts
  packages/layers/src/polygon/shaders/tile/polygon_tile_map_vert.glsl
  packages/layers/src/polygon/shaders/tile/polygon_tile_vert.glsl
  packages/maps/src/amap2/Viewport.ts
  packages/site/docs/api/point_layer/style.zh.md
Labels: PR: reviewed-approved, bugfix

#1557 refactor: 压缩图片主题组件中的图片尺寸
  packages/component/src/constants/index.ts
Labels: PR: reviewed-approved

#1556 Publish
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
  packages/utils/src/workers/triangulation.ts
Labels: PR: unreviewed

#1559 Publish 2.13.0
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed
