Repository antvis/L7, pull requests merged in 2022-06, with the labels that each got.

#1142 chore: 修改 lerna 版本号升级指令，l7 包内部固定依赖版本
  package.json
Labels: PR: reviewed-approved, ignore-for-release

#1143 fix： 修复样式数据映射失效
  packages/layers/src/line/models/arc.ts
  packages/layers/src/line/models/arc_3d.ts
  packages/layers/src/line/models/arcmini.ts
  packages/layers/src/line/models/great_circle.ts
  packages/layers/src/line/models/line.ts
  packages/layers/src/line/models/linearline.ts
  packages/layers/src/line/models/simpleLine.ts
  packages/layers/src/line/models/wall.ts
  packages/layers/src/point/models/extrude.ts
  packages/layers/src/point/models/fill.ts
  packages/layers/src/point/models/fillmage.ts
  packages/layers/src/point/models/image.ts
  packages/layers/src/point/models/normal.ts
  packages/layers/src/point/models/radar.ts
  packages/layers/src/point/models/simplePoint.ts
  packages/layers/src/point/models/text.ts
  packages/layers/src/polygon/models/extrude.ts
  packages/layers/src/polygon/models/fill.ts
  packages/layers/src/polygon/models/ocean.ts
  packages/layers/src/polygon/models/water.ts
  stories/Map/components/bugfix.tsx
Labels: PR: reviewed-approved

#1145 fix: IE11 兼容测试
  packages/l7/demo/circle.html
  packages/l7/demo/cylinder.html
  packages/l7/demo/dot.html
  packages/l7/demo/heatmap.html
  packages/l7/demo/heatmap3d.html
  packages/l7/demo/image.html
  packages/l7/demo/polygon.html
  packages/l7/demo/text.html
  packages/maps/src/amap2/map.ts
  packages/utils/src/mini-adapter/global.ts
  packages/utils/src/mini-adapter/index.ts
Labels: PR: reviewed-approved, bugfix

#1146 chore: update version 2.8.41 -> 2.8.42
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1147 Fix: 高德地图坐标转换
  packages/maps/src/amap2/map.ts
Labels: PR: reviewed-approved

#1148 chore: update version 2.8.42 -> 2.8.43
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1149 fix: 修复一些问题
  packages/core/src/services/interaction/InteractionService.ts
  packages/core/src/services/interaction/PickingService.ts
  packages/layers/src/polygon/models/extrude.ts
  packages/layers/src/polygon/models/fill.ts
Labels: PR: reviewed-approved, bugfix

#1150 chore: update version 2.8.43 -> 2.8.44
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1151 feat: 去除事件节流
  packages/core/src/services/interaction/PickingService.ts
Labels: PR: reviewed-approved, feature

#1152 chore: upodate version 2.8.44 -> 2.8.45
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1155 chore: update version 2.8.45 -> 2.9.0
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed, ignore-for-release

#1159 fix: 修复瓦片的一些 bug
  .storybook/preview.ts
  packages/core/src/services/source/ISourceService.ts
  packages/layers/src/tile/manager/tilePickerManager.ts
  packages/layers/src/tile/tmsTileLayer.ts
  packages/source/src/index.ts
  packages/source/src/source.ts
  packages/source/src/tileset-manager/const.ts
  packages/source/src/tileset-manager/index.ts
  packages/source/src/tileset-manager/tile.ts
  packages/source/src/tileset-manager/tileset-manager.ts
  packages/source/src/tileset-manager/types.ts
  packages/source/src/tileset-manager/utils/lonlat-tile.ts
  packages/source/src/tileset-manager/utils/strategies.ts
  packages/source/src/tileset-manager/utils/tile-url.ts
  stories/tile/components/VectorProvinceAllTile.tsx
Labels: PR: unreviewed, bugfix

#1160 chore: update version 2.9.0 -> 2.9.1
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed, ignore-for-release

#1162 chore: update version 2.9.1 -> 2.9.2
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed, ignore-for-release

#1163 feat: 优化数据栅格的拾取
  packages/layers/src/tile/manager/tilePickerManager.ts
  packages/layers/src/tile/tileFactory/base.ts
  stories/tile/components/RasterArrayBuffer2.tsx
  stories/tile/components/VectorPolygonTile.tsx
Labels: PR: unreviewed, feature

#1166 chore: update version 2.9.2 -> 2.9.3
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed, ignore-for-release

#1167 feat: 完善瓦片事件中 properties 的值透出
  packages/layers/src/tile/tileFactory/base.ts
  stories/tile/components/VectorPolygonTile.tsx
  stories/tile/components/VectorProvinceAllTile.tsx
Labels: PR: unreviewed, feature

#1156 chore: 透出组件类型定义
  packages/component/src/css/l7.css
  packages/component/src/index.ts
  packages/component/src/markerlayer.ts
Labels: PR: reviewed-approved, ignore-for-release

#1174 feat: sprite 粒子增加运动边界参数 spriteBottom
  packages/layers/src/Geometry/models/sprite.ts
  packages/layers/src/core/interface.ts
  stories/Object/components/sprite.tsx
Labels: PR: reviewed-approved, feature

#1175 chore: 透出组件类型定义
  packages/component/src/control/layer.ts
  packages/component/src/control/logo.ts
  packages/component/src/control/scale.ts
  packages/component/src/control/zoom.ts
  packages/component/src/index.ts
  packages/component/src/interface.ts
  packages/component/src/marker-layer.ts
Labels: PR: reviewed-approved, ignore-for-release

#1176 chore: update version 2.8.46 -> 2.8.47
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1178 style: change demo
  stories/tile/components/RasterArrayBuffer.tsx
  stories/tile/components/RasterArrayBuffer2.tsx
  stories/tile/components/RasterTile.tsx
  stories/tile/components/VectorPolygonTile.tsx
  stories/tile/components/VectorProvince.tsx
  stories/tile/components/VectorProvinceAllTile.tsx
  stories/tile/components/lerc.tsx
  stories/tile/components/timeline.tsx
  stories/tile/map.stories.tsx
Labels: PR: unreviewed

#1179 feat: 瓦片支持从中心视野优先加载
  packages/layers/src/tile/tmsTileLayer.ts
  packages/utils/src/tileset-manager/tileset-manager.ts
  packages/utils/src/tileset-manager/utils/lonlat-tile.ts
  stories/tile/components/QuXian.tsx
  stories/tile/map.stories.tsx
Labels: PR: reviewed-approved, feature

#1181 feat: 瓦片加载添加缓冲区域
  packages/layers/src/tile/tileLayer/baseTileLayer.ts
  packages/layers/src/tile/tmsTileLayer.ts
  packages/utils/src/tileset-manager/const.ts
  packages/utils/src/tileset-manager/tile.ts
  packages/utils/src/tileset-manager/tileset-manager.ts
  packages/utils/src/tileset-manager/utils/bound-buffer.ts
  packages/utils/src/tileset-manager/utils/lonlat-tile.ts
Labels: PR: unreviewed, feature

#1184 style: add tile demo
  stories/tile/components/OsmRasterTile.tsx
  stories/tile/components/RasterArrayBuffer2.tsx
  stories/tile/components/RasterTile.tsx
  stories/tile/components/VectorPolygonTile.tsx
  stories/tile/components/demFilter.tsx
  stories/tile/components/heightline.tsx
  stories/tile/components/landCover.tsx
  stories/tile/components/light.tsx
  stories/tile/map.stories.tsx
Labels: PR: unreviewed

#1185 chore: update version 2.9.4 -> 2.9.5 beta
  lerna.json
  packages/component/package.json
  packages/component/src/control/layer.ts
  packages/component/src/control/logo.ts
  packages/component/src/control/scale.ts
  packages/component/src/control/zoom.ts
  packages/component/src/css/l7.css
  packages/component/src/index.ts
  packages/component/src/interface.ts
  packages/component/src/marker-layer.ts
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/layers/src/Geometry/models/sprite.ts
  packages/layers/src/core/interface.ts
  packages/layers/src/heatmap/shaders/heatmap_frag.glsl
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
  stories/Map/components/bugfix.tsx
  stories/Object/components/sprite.tsx
Labels: PR: unreviewed, ignore-for-release

#1186 docs: 修改官网文档
  docs/api/tile/rasterTile_layer.zh.md
  docs/api/tile/tile_layer.zh.md
  stories/tile/components/VectorProvinceAllTile.tsx
  stories/tile/map.stories.tsx
Labels: PR: unreviewed, documentation

#1188 docs: 完善官网文档、demo
  docs/api/l7.zh.md
  examples/tile/raster/demo/dem.js
  examples/tile/raster/demo/lerc.js
  examples/tile/raster/demo/meta.json
  examples/tile/raster/demo/tiff.js
  examples/tile/vector/API.en.md
  examples/tile/vector/API.zh.md
  examples/tile/vector/demo/line.js
  examples/tile/vector/demo/meta.json
  examples/tile/vector/demo/point.js
  examples/tile/vector/demo/polygon.js
  examples/tile/vector/demo/text.js
  examples/tile/vector/index.en.md
  examples/tile/vector/index.zh.md
  gatsby-browser.js
  packages/layers/src/tile/tileFactory/rasterData.ts
  stories/tile/components/RasterArrayBuffer2.tsx
  stories/tile/components/VectorProvince.tsx
  stories/tile/components/VectorProvinceAllTile.tsx
  stories/tile/map.stories.tsx
Labels: PR: unreviewed, documentation

#1187 feat: 新增瓦片实时更新策略
  packages/utils/src/tileset-manager/const.ts
  packages/utils/src/tileset-manager/tileset-manager.ts
  packages/utils/src/tileset-manager/types.ts
  packages/utils/src/tileset-manager/utils/strategies.ts
Labels: PR: unreviewed, feature

#1189 docs: 修改官网文档内容
  examples/tile/raster/demo/tiff.js
  stories/tile/components/OsmRasterTile.tsx
  stories/tile/components/RasterArrayBuffer2.tsx
  stories/tile/components/RasterTile.tsx
  stories/tile/components/VectorPolygonTile.tsx
  stories/tile/components/heightline.tsx
  stories/tile/components/landCover.tsx
Labels: PR: unreviewed, documentation

#1191 chore: update version 2.9.5 beta -> 2.9.6
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed, ignore-for-release

#1194 docs: 新增官网瓦片 demo
  docs/api/tile/rasterTile_layer.zh.md
  docs/api/tile/tile_layer.zh.md
  docs/api/tile/vectorTile_layer.zh.md
  examples/tile/raster/demo/amap-satelliteMask.js
  examples/tile/raster/demo/meta.json
  examples/tile/raster/demo/tianditu-satellite.js
  examples/tile/raster/demo/tiff.js
  examples/tile/vector/demo/line.js
  examples/tile/vector/demo/point.js
  examples/tile/vector/demo/polygon.js
  examples/tile/vector/demo/text.js
Labels: PR: unreviewed

#1197 feat: 优化瓦片渲染性能
  .storybook/preview.ts
  examples/tile/raster/demo/dem.js
  examples/tile/raster/demo/lerc.js
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/layer/LayerService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/core/interface.ts
  packages/layers/src/raster/models/raster.ts
  packages/layers/src/tile/manager/tileLayerManager.ts
  packages/layers/src/tile/tileFactory/rasterData.ts
  packages/layers/src/tile/tileLayer/baseTileLayer.ts
  packages/layers/src/tile/tmsTileLayer.ts
  stories/tile/components/demFilter.tsx
  stories/tile/components/landCover.tsx
Labels: PR: unreviewed, feature

#1198 chore: update version 2.9.6 -> 2.9.7
  .storybook/preview.ts
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed, ignore-for-release

#1201 docs: 去除外源瓦片地图
  examples/tile/raster/demo/mapbox-streets.js
  examples/tile/raster/demo/meta.json
  examples/tile/raster/demo/open-street-map.js
  examples/tile/raster/demo/watercolor.js
Labels: PR: unreviewed

#1202 feat: 取消滞留请求中的瓦片
  packages/utils/src/tileset-manager/tile.ts
  packages/utils/src/tileset-manager/tileset-manager.ts
Labels: PR: unreviewed, feature

#1203 chore: update version 2.9.7 -> 2.9.8
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed

#1207 fix: 修复 scene 销毁后重执行的 clear 导致的问题
  packages/renderer/src/regl/index.ts
Labels: PR: unreviewed, bugfix

#1206 feat: 支持多域名瓦片服务地址
  examples/tile/raster/demo/amap-satellite.js
  examples/tile/raster/demo/tianditu-satellite.js
  packages/source/src/parser/mvt.ts
  packages/source/src/parser/raster-tile.ts
  packages/source/src/utils/getTile.ts
  stories/tile/components/RasterTile.tsx
Labels: PR: reviewed-approved, feature

#1210 fix: 修复 scene 销毁导致的 bug
  packages/renderer/src/regl/index.ts
Labels: PR: reviewed-approved, bugfix
