Repository antvis/L7, pull requests merged in 2022-07, with the labels that each got.

#1213 chore: 升级 pbf 依赖版本
  packages/source/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1214 chore: update version 2.9.8 -> 2.9.9
  .github/workflows/gitleaks.yml
  LICENSE.md
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1215 fix: L7Draw 对应 Github 和 文档地址变更
  README.en-US.md
  README.md
  docs/api/draw/start.zh.md
  examples/draw/basic/index.en.md
  gatsby-config.js
  packages/l7/README.en-US.md
  packages/l7/README.md
Labels: PR: reviewed-approved, bugfix

#1216 Fix scale linear,power,log 线性映射
  examples/polygon/fill/demo/usa.js
  packages/layers/package.json
  packages/layers/src/plugins/FeatureScalePlugin.ts
Labels: PR: unreviewed

#1218 chore: update version 2.9.9 -> 2.9.10
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1222 feat: 优化、修复点图层等面积点模式
  packages/core/src/services/map/IMapService.ts
  packages/layers/src/point/models/fill.ts
  packages/layers/src/point/shaders/fill_vert.glsl
  packages/maps/src/earth/index.ts
  packages/maps/src/earth/map.ts
  packages/maps/src/map/map.ts
  stories/Map/components/bugfix.tsx
Labels: PR: reviewed-approved, feature

#1223 chore: update version 2.9.10 -> 2.9.11
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1226 fix: 修复 option 参数未同步 style 更新导致的配置失效
  packages/layers/src/core/BaseLayer.ts
Labels: PR: reviewed-approved, bugfix

#1220 docs: 修复官网 tile 英文文档丢失
  docs/api/tile/rasterTile_layer.en.md
  docs/api/tile/tile_layer.en.md
  docs/api/tile/vectorTile_layer.en.md
Labels: PR: reviewed-approved, documentation

#1229 feat: add halfLine model
  packages/layers/src/line/index.ts
  packages/layers/src/line/models/half.ts
  packages/layers/src/line/models/index.ts
  packages/layers/src/line/shaders/half/line_half_frag.glsl
  packages/layers/src/line/shaders/half/line_half_vert.glsl
  packages/layers/src/plugins/DataMappingPlugin.ts
  stories/Map/components/bugfix.tsx
Labels: PR: unreviewed, feature

#1228 Fix cluster issue
  .github/workflows/mirror.yml
  package.json
  packages/layers/src/plugins/DataSourcePlugin.ts
  stories/District/Layer/Country.tsx
  stories/District/Layer/Country2.tsx
  stories/District/Layer/city.tsx
  stories/District/Layer/country_bubble.tsx
  stories/District/Layer/country_city.tsx
  stories/District/Layer/country_county.tsx
  stories/District/Layer/county.tsx
  stories/District/Layer/drillDown.tsx
  stories/District/Layer/province.tsx
  stories/District/Layer/world.tsx
  stories/District/district.stories.tsx
  stories/Layers/components/cluster.tsx
  stories/Layers/components/cluster2.tsx
  stories/Layers/data/cluster1.json
  stories/Layers/data/cluster2.json
Labels: PR: reviewed-approved

#1230 chore: update version 2.9.12 -> 2.9.13
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1233 chore: remove useless demo
  stories/React/React.stories.tsx
  stories/React/components/Scene.tsx
  stories/React/components/world.tsx
  stories/React/components/worldLayer.tsx
  stories/React/components/world_ncov.tsx
  stories/React/components/world_ncov_bubble.tsx
  stories/React/components/world_ncov_bubble_animate.tsx
  stories/React/components/world_ncov_column.tsx
  stories/React/components/world_ncov_fill.tsx
  stories/fun/components/line.tsx
  stories/fun/fun.stories.tsx
Labels: PR: reviewed-approved, ignore-for-release

#1235 fix: 修复 option 错误、shader 路径错误
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/point/models/earthExtrude.ts
  packages/layers/src/point/models/extrude.ts
Labels: PR: reviewed-approved, bugfix

#1236 chore: update version 2.9.13 -> 2.9.14
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1243 fix: 修复 webgl context lost
  .storybook/preview.ts
  packages/maps/src/amap2/map.ts
  packages/renderer/src/regl/index.ts
  stories/Map/components/bugfix.tsx
Labels: PR: reviewed-approved, bugfix

#1242 chore: 更新 scripts 标签
  build/rollup.config.worker.js
  package.json
  packages/component/package.json
  packages/l7/package.json
  packages/l7/tsconfig.build.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed, ignore-for-release

#1141 Upgrade @mapbox/geojson-rewind to address `minimalist` vulnerability
  packages/source/package.json
Labels: PR: reviewed-approved

#1244 chore: publish 2.9.14 -> 2.9.16
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1246 chore: 修改 worker 执行函数
  build/rollup-plugin-inline-worker.js
  packages/core/src/services/layer/StyleAttributeService.ts
  packages/l7/src/worker.ts
  packages/layers/src/core/triangulation.ts
  packages/utils/src/worker-helper/index.ts
Labels: PR: reviewed-approved, ignore-for-release

#1231 docs: 官网文档调整
  docs/api/district/start.en.md
  docs/api/district/start.zh.md
  docs/api/draw/start.en.md
  docs/api/draw/start.zh.md
  docs/api/experiment/canvas.en.md
  docs/api/experiment/canvas.zh.md
  docs/api/experiment/pass.en.md
  docs/api/experiment/pass.zh.md
  docs/api/experiment/wind.en.md
  docs/api/experiment/wind.zh.md
  docs/api/l7history.en.md
  docs/api/l7history.zh.md
  docs/api/react/start.en.md
  docs/api/react/start.zh.md
  docs/common/layer/mouse_event.md
  examples/point/scatter/demo/dynamicScatter.js
  examples/point/scatter/demo/meta.json
Labels: PR: reviewed-approved, documentation

#1250 docs: 更新文档
  docs/tutorial/quickstart.en.md
  docs/tutorial/quickstart.zh.md
  site/pages/index.zh.tsx
Labels: PR: reviewed-approved, documentation

#1253 chore: worker 注册放到 utils 里面
  build/rollup.config.worker.js
  packages/l7/src/index.ts
  packages/l7/src/worker.ts
  packages/utils/package.json
  packages/utils/src/worker-helper/index.ts
  packages/utils/src/workers/index.ts
Labels: PR: reviewed-approved, ignore-for-release

#1258 chore: update version 2.9.16 -> 2.9.17
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1260 fix: fix dash line shader compile
  .storybook/preview.ts
  packages/layers/src/line/shaders/dash/arc_dash_frag.glsl
  packages/layers/src/line/shaders/dash/line_dash_frag.glsl
  packages/layers/src/line/shaders/line_arc_great_circle_frag.glsl
Labels: PR: reviewed-approved, bugfix

#1261 chore: update version 2.9.17 -> 2.9.18 fix bug
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1263 feat: 优化风场图层的显示效果
  packages/layers/src/wind/models/wind.ts
  packages/layers/src/wind/models/windRender.ts
  stories/Map/components/amap2demo_wind.tsx
Labels: PR: reviewed-approved, feature
