Repository antvis/L7, pull requests merged in 2022-09, with the labels that each got.

#1322 fix: markerLayer在GaodeMapV2做底图时removeMarkerLayer视图图层层级改变时会复原被删除的图层
  dev-demos/features/customLayer/marker-layer.md
  packages/component/src/marker-layer.ts
Labels: PR: unreviewed, bugfix

#1323 chore: 增加覆盖率Ci
  .github/workflows/test.yml
  .gitignore
  jest.config.js
  packages/layers/src/point/__tests__/layer_init.spec.ts
  packages/renderer/src/regl/ReglElements.ts
  packages/test-utils/src/create-context.ts
  packages/test-utils/src/test-scene.ts
  tsconfig.json
  tslint.prod.json
Labels: PR: reviewed-approved, ignore-for-release

#1324 fix: 修复gaodev2下MarkerLayer清除有误问题
  dev-demos/features/customLayer/marker-layer.md
  packages/component/src/marker-layer.ts
Labels: PR: reviewed-approved, bugfix

#1328 docs: remove website demos
  packages/site/examples/choropleth/administrative/delete/administrative-switch.tsx
  packages/site/examples/choropleth/administrative/delete/china-city.ts
  packages/site/examples/choropleth/administrative/delete/china-map.ts
  packages/site/examples/choropleth/administrative/delete/world-map.ts
  packages/site/examples/choropleth/administrative/demo/meta.json
  packages/site/examples/choropleth/drill/API.en.md
  packages/site/examples/choropleth/drill/API.zh.md
  packages/site/examples/choropleth/drill/demo/drill-callback.ts
  packages/site/examples/choropleth/drill/demo/drill-intercept.ts
  packages/site/examples/choropleth/drill/demo/meta.json
  packages/site/examples/choropleth/drill/demo/order-drill.ts
  packages/site/examples/choropleth/drill/demo/unorder-drill.ts
  packages/site/examples/choropleth/drill/index.en.md
  packages/site/examples/choropleth/drill/index.zh.md
  packages/site/examples/gallery/animate/delete/amap_car.js
  packages/site/examples/gallery/animate/delete/box_select.js
  packages/site/examples/gallery/animate/delete/plane_animate.js
  packages/site/examples/gallery/animate/delete/route_line.js
  packages/site/examples/gallery/animate/demo/meta.json
  packages/site/examples/polygon/3d/demo/meta.json
  packages/site/examples/polygon/delete/china_linear_in.js
  packages/site/examples/polygon/delete/city.js
  packages/site/examples/polygon/delete/province.js
  packages/site/examples/polygon/delete/texture3D.js
  packages/site/examples/polygon/fill/demo/meta.json
  packages/site/examples/raster/basic/delete/dem.js
  packages/site/examples/raster/basic/delete/ndvi.js
  packages/site/examples/raster/basic/demo/meta.json
  packages/site/examples/react/covid/demo/covid_animate.tsx
  packages/site/examples/react/covid/demo/covid_bubble.tsx
  packages/site/examples/react/covid/demo/covid_column.tsx
  packages/site/examples/react/covid/demo/covid_extrude.tsx
  packages/site/examples/react/covid/demo/covid_fill.tsx
  packages/site/examples/react/covid/demo/covid_grid.tsx
  packages/site/examples/react/covid/demo/meta.json
  packages/site/examples/react/covid/index.en.md
  packages/site/examples/react/covid/index.zh.md
  packages/site/examples/tile/vector/API.en.md
  packages/site/examples/tile/vector/API.zh.md
  packages/site/examples/tile/vector/demo/line.js
  packages/site/examples/tile/vector/demo/meta.json
  packages/site/examples/tile/vector/demo/point.js
  packages/site/examples/tile/vector/demo/polygon.js
  packages/site/examples/tile/vector/demo/text.js
  packages/site/examples/tile/vector/index.en.md
  packages/site/examples/tile/vector/index.zh.md
Labels: PR: reviewed-approved, documentation

#1330 docs: 移除地球模式点图层demo
  packages/site/examples/earth/point/back/cylinder.js
  packages/site/examples/earth/point/back/index.en.md
  packages/site/examples/earth/point/back/index.zh.md
  packages/site/examples/earth/point/back/point.js
  packages/site/examples/earth/point/demo/meta.json
Labels: PR: reviewed-approved, documentation

#1331 fix: 默认source 配置
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/earth/index.ts
  packages/site/examples/earth/point/back/cylinder.js
  packages/site/examples/earth/point/back/index.en.md
  packages/site/examples/earth/point/back/index.zh.md
  packages/site/examples/earth/point/back/point.js
  packages/site/examples/earth/point/demo/meta.json
  packages/three/src/core/baseLayer.ts
Labels: PR: reviewed-approved, bugfix

#1332 fix: source empty err
  dev-demos/features/earth/earth.md
  dev-demos/features/earth/earth.tsx
  dev-demos/features/geometry/sprite.md
  dev-demos/features/geometry/sprite.tsx
  packages/core/src/services/layer/ILayerService.ts
  packages/layers/src/Geometry/index.ts
  packages/layers/src/core/BaseLayer.ts
  packages/three/src/core/baseLayer.ts
Labels: PR: reviewed-approved, bugfix

#1333 fix: 自定义图层 - markerLayer - 修复图层执行clear后聚合能力失效问题
  dev-demos/features/customLayer/marker-layer.md
  packages/component/src/marker-layer.ts
  packages/core/src/services/component/MarkerService.ts
Labels: PR: reviewed-approved, bugfix

#1334 docs: website remove mapbox demos
  packages/site/examples/choropleth/administrative/delete/administrative-switch.tsx
  packages/site/examples/choropleth/administrative/delete/china-city.ts
  packages/site/examples/choropleth/administrative/delete/china-map.ts
  packages/site/examples/choropleth/administrative/delete/world-map.ts
  packages/site/examples/choropleth/administrative/demo/hangzhou-city.ts
  packages/site/examples/choropleth/administrative/demo/xihu-district.ts
  packages/site/examples/choropleth/administrative/demo/zhejiang-province-district.ts
  packages/site/examples/choropleth/administrative/demo/zhejiang-province.ts
  packages/site/examples/draw/UI/demo/mapbox.js
  packages/site/examples/draw/UI/demo/meta.json
  packages/site/examples/engine/three/demo/mapbox_ant.js
  packages/site/examples/engine/three/demo/meta.json
  packages/site/examples/gallery/animate/delete/plane_animate.js
  packages/site/examples/gallery/animate/demo/turin.js
  packages/site/examples/gallery/basic/demo/arcCircle.js
  packages/site/examples/gallery/basic/demo/bus_dark.js
  packages/site/examples/gallery/basic/demo/light.js
  packages/site/examples/heatmap/grid/demo/grid_world.js
  packages/site/examples/heatmap/heatmap/demo/heatmap.js
  packages/site/examples/heatmap/heatmap/demo/heatmap_purple.js
  packages/site/examples/heatmap/hexagon/demo/china.js
  packages/site/examples/heatmap/hexagon/demo/hexagon.js
  packages/site/examples/heatmap/hexagon/demo/light.js
  packages/site/examples/line/animate/demo/animate_line.js
  packages/site/examples/line/animate/demo/line_animate.js
  packages/site/examples/line/animate/demo/plane_animate2.js
  packages/site/examples/line/animate/demo/trip_animate.js
  packages/site/examples/line/animate/demo/wind_animate.js
  packages/site/examples/line/arc/demo/arcCircle.js
  packages/site/examples/line/arc/demo/trip_arc.js
  packages/site/examples/line/arc/demo/trip_arc_dark.js
  packages/site/examples/line/arc/demo/trip_arc_dark_linear.js
  packages/site/examples/line/path/demo/bus_dark.js
  packages/site/examples/line/path/demo/bus_light.js
  packages/site/examples/line/path/demo/road_dark.js
  packages/site/examples/line/path/demo/road_dark_dash.js
  packages/site/examples/line/path/demo/shanghai_bus.js
  packages/site/examples/point/bubble/demo/world.js
  packages/site/examples/point/text/demo/polygon_text.js
  packages/site/examples/polygon/delete/city.js
  packages/site/examples/polygon/delete/province.js
  packages/site/examples/polygon/fill/demo/usa.js
  packages/site/examples/react/layer/demo/marker.tsx
  packages/site/examples/react/layer/demo/popup.tsx
  packages/site/examples/react/scene/demo/mapbox.jsx
  packages/site/examples/react/scene/demo/meta.json
  packages/site/examples/tile/raster/demo/dem.js
  packages/site/examples/tile/raster/demo/meta.json
  packages/site/examples/tutorial/control/demo/mapbox.js
  packages/site/examples/tutorial/control/demo/meta.json
  packages/site/examples/tutorial/map/demo/mapbox.js
  packages/site/examples/tutorial/map/demo/meta.json
  packages/site/examples/tutorial/marker/demo/amap.js
  packages/site/examples/tutorial/marker/demo/mapbox.js
  packages/site/examples/tutorial/marker/demo/meta.json
Labels: PR: reviewed-approved, documentation

#1338 build: worker 内联打包补加
  .fatherrc.ts
  .umirc.ts
  packages/utils/.fatherrc.ts
Labels: PR: reviewed-approved

#1347 feat: 瓦片性能和代码优化
  dev-demos/features/tile/rasterData/loadTiff.tsx
  packages/core/src/services/layer/ILayerService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/core/interface.ts
  packages/layers/src/raster/index.ts
  packages/layers/src/raster/models/rasterTile.ts
  packages/layers/src/raster/shaders/raster_2d_frag.glsl
  packages/layers/src/raster/shaders/raster_2d_vert.glsl
  packages/layers/src/tile/manager/baseMapTileLayerManager.ts
  packages/layers/src/tile/manager/baseTileManager.ts
  packages/layers/src/tile/manager/tileLayerManager.ts
  packages/layers/src/tile/manager/tilePickerManager.ts
  packages/layers/src/tile/models/tileModel.ts
  packages/layers/src/tile/tileFactory/rasterData.ts
  packages/layers/src/tile/tileFactory/rasterDataLayer.ts
  packages/layers/src/tile/tileLayer/baseMapTileLayer.ts
  packages/layers/src/tile/tileLayer/baseTileLayer.ts
  packages/layers/src/tile/tmsMapTileLayer.ts
  packages/layers/src/tile/tmsTileLayer.ts
  packages/layers/src/tile/utils.ts
Labels: PR: reviewed-approved, feature

#1349 feat: add Hill shade demo
  dev-demos/features/tile/hillshade.md
  dev-demos/features/tile/rasterData/hillshade.tsx
Labels: PR: reviewed-approved, feature

#1350 feat: 设置瓦片多服务重构、支持加载多文件
  dev-demos/features/tile/hillshade.md
  dev-demos/features/tile/raster/imageDataMapping.tsx
  dev-demos/features/tile/raster/satellite.tsx
  dev-demos/features/tile/rasterData/hillShade.tsx
  dev-demos/features/tile/rasterData/loadImageMask.tsx
  dev-demos/features/tile/rasterData/loadMultiTiff.tsx
  dev-demos/features/tile/rasterDataMul.md
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/layers/src/raster/shaders/raster_2d_frag.glsl
  packages/layers/src/tile/tileFactory/index.ts
  packages/layers/src/tile/tmsMapTileLayer.ts
  packages/layers/src/tile/tmsTileLayer.ts
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/examples/tile/raster/demo/amap-normal.js
  packages/site/examples/tile/raster/demo/amap-satellite.js
  packages/site/examples/tile/raster/demo/amap-satelliteMask.js
  packages/site/examples/tile/raster/demo/tianditu-satellite.js
  packages/site/package.json
  packages/source/package.json
  packages/source/src/index.ts
  packages/source/src/parser/mvt.ts
  packages/source/src/parser/raster-tile.ts
  packages/source/src/utils/getTile.ts
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
  packages/utils/src/ajax.ts
  packages/utils/src/tileset-manager/utils/tile-url.ts
Labels: PR: reviewed-approved, feature

#1351 fix: demo address err
  dev-demos/features/tile/hillshade.md
Labels: PR: reviewed-approved, bugfix

#1357 chore: update version 2.9.27 -> 2.9.28
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1358 fix: 修复 layer model 更新时候存在闪烁的问题
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/plugins/LayerModelPlugin.ts
Labels: PR: reviewed-approved, bugfix

#1360 chore: update version 2.9.28 -> 2.9.29
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/gatsby-config.js
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1361 feat: add l7-three father umd build config
  packages/three/.fatherrc.ts
  packages/three/package.json
  packages/three/src/core/baseLayer.ts
  packages/three/src/core/threeRender.ts
  packages/three/src/core/threeRenderService.ts
Labels: PR: reviewed-approved, feature

#1363 chore: update version 2.9.29 -> 2.9.30
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/.gitignore
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed, ignore-for-release
