Repository antvis/L7, pull requests merged in 2022-05, with the labels that each got.

#1091 feat: 新增公告牌 geometry
  packages/layers/src/Geometry/index.ts
  packages/layers/src/Geometry/models/billboard.ts
  packages/layers/src/Geometry/models/index.ts
  packages/layers/src/Geometry/shaders/billboard_frag.glsl
  packages/layers/src/Geometry/shaders/billboard_vert.glsl
  packages/layers/src/core/interface.ts
  packages/layers/src/index.ts
  stories/Object/components/billboard.tsx
  stories/Object/map.stories.tsx
Labels: PR: reviewed-approved

#1093 feat: change mapbox token
  packages/maps/src/mapbox/map.ts
Labels: PR: reviewed-approved

#1094 chore: update version 2.8.34 -> 2.8.35
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved

#1096 docs: update l7 package readme.md
  packages/l7/README.en-US.md
  packages/l7/README.md
Labels: PR: reviewed-approved

#1098 feat: sprite 优化，取消拾取，允许不设置 source
  packages/core/src/services/layer/IStyleAttributeService.ts
  packages/layers/src/Geometry/shaders/sprite_frag.glsl
  packages/layers/src/Geometry/shaders/sprite_vert.glsl
  packages/layers/src/plugins/FeatureScalePlugin.ts
  stories/Object/components/sprite.tsx
Labels: PR: reviewed-approved

#1097 ci: 新增 release label action
  .github/release.yaml
  .github/workflows/lint.yml
  .github/workflows/mirror.yml
  .github/workflows/preview.yml
  .github/workflows/release-label.yml
  .github/workflows/release.yml
  .gitignore
  lerna.json
  package.json
  packages/three/package.json
  scripts/beta.sh
  scripts/latest.sh
  scripts/mini.sh
  scripts/publish.sh
  scripts/tbeta.sh
Labels: PR: reviewed-approved

#1103 feat: 新增 mvt parser, Raster 支持 ImageBitmap
  packages/core/src/services/renderer/ITexture2D.ts
  packages/layers/src/image/models/image.ts
  packages/layers/src/point/index.ts
  packages/renderer/src/regl/ReglTexture2D.ts
  packages/source/package.json
  packages/source/src/index.ts
  packages/source/src/parser/image.ts
  packages/source/src/parser/mvt.ts
  packages/source/src/parser/raster-tile.ts
  packages/utils/src/ajax.ts
  packages/utils/src/env.ts
  packages/utils/src/fetchData.ts
  packages/utils/src/index.ts
  packages/utils/src/tileset-manager/tile.ts
  packages/utils/src/tileset-manager/tileset-manager.ts
  stories/Tile/components/OsmRasterTile.tsx
  stories/Tile/components/RasterTile.tsx
  stories/Tile/components/VectorTile.tsx
  stories/Tile/components/VextorTileClickTest.tsx
  stories/Tile/map.stories.tsx
Labels: PR: reviewed-approved, feature

#1105 fix: 修复拾取状态残留导致的拾取高亮错误
  packages/core/src/services/interaction/PickingService.ts
  stories/Map/components/amap2demo_polygon.tsx
Labels: PR: reviewed-approved, bugfix

#1114 fix: 修复 mouseup 失效
  packages/core/src/services/interaction/PickingService.ts
Labels: PR: reviewed-approved, bugfix

#1115 feat: 优化代码，使用 Array.includes 代替 ||
  packages/core/src/services/interaction/PickingService.ts
Labels: PR: reviewed-approved, feature

#1118 fix: 补全 ISource 接口定义
  packages/core/src/services/source/ISourceService.ts
  packages/layers/package.json
Labels: PR: reviewed-approved, bugfix

#1117 feat: 发布打包代码调整
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
  packages/utils/src/tileset-manager/const.ts
  packages/utils/src/tileset-manager/index.ts
  packages/utils/src/tileset-manager/tile.ts
  packages/utils/src/tileset-manager/tileset-manager.ts
  packages/utils/src/tileset-manager/types.ts
  packages/utils/src/tileset-manager/utils/lonlat-tile.ts
Labels: PR: unreviewed, feature

#1120 Fix 接口导出
  packages/layers/src/index.ts
  stories/Scale/Scale.stories.tsx
  stories/Scale/components/Threshold.tsx
Labels: PR: reviewed-approved

#1104 fix: 图层事件添加事件类型定义
  docs/common/layer/mouse_event.md
  packages/core/src/services/layer/ILayerService.ts
  packages/layers/src/core/BaseLayer.ts
Labels: PR: reviewed-approved, bugfix

#1122 chore: remove geo coord
  package.json
Labels: PR: reviewed-approved, ignore-for-release

#1124 feat: 支持动态配置坐标原点
  packages/core/src/services/source/ISourceService.ts
  packages/layers/src/plugins/DataMappingPlugin.ts
  packages/layers/src/plugins/ShaderUniformPlugin.ts
  packages/maps/src/amap2/map.ts
  packages/source/src/source.ts
  packages/utils/src/geo.ts
  stories/Map/components/amap2demo.tsx
Labels: PR: reviewed-approved, feature

#1126 chore: scale 升级优化
  packages/core/src/services/layer/IStyleAttributeService.ts
  packages/core/src/services/layer/StyleAttribute.ts
  packages/layers/package.json
  packages/layers/src/plugins/FeatureScalePlugin.ts
  stories/Scale/Scale.stories.tsx
  stories/Scale/components/Bvariate.tsx
  stories/Scale/components/Diverging.tsx
  stories/Scale/components/Point.tsx
Labels: PR: reviewed-approved, ignore-for-release

#1128 fix: 修复挤出几何体侧面渐变错误
  packages/layers/src/polygon/shaders/extrude/polygon_extrude_vert.glsl
Labels: PR: reviewed-approved, bugfix

#1125 fix: 修复 layer 包入口文件依赖注入有副作用影响
  packages/layers/package.json
Labels: PR: reviewed-approved, bugfix

#1130 fix: 修复高德2 动态点位引发的 bug
  packages/layers/src/plugins/DataMappingPlugin.ts
  packages/layers/src/plugins/ShaderUniformPlugin.ts
Labels: PR: reviewed-approved, bugfix

#1134 fix: 修复计算图层数据中心点时可能存在的计算错误
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/source/src/source.ts
  packages/three/package.json
  packages/utils/package.json
  stories/Map/components/amap2demo_polygon.tsx
Labels: PR: reviewed-approved, bugfix

#1135 chore: update version 2.8.39 -> 2.8.40
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed, ignore-for-release

#1136 chore: 修改 d3-interpolate 类型定义依赖版本
  packages/l7/src/version.ts
  packages/layers/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1137 feat: 高德2动态设置中心点
  packages/layers/src/plugins/DataMappingPlugin.ts
  packages/layers/src/plugins/ShaderUniformPlugin.ts
Labels: PR: reviewed-approved, feature

#1138 chore: update version 2.8.40 -> 2.8.41
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release
