Repository antvis/L7, pull requests merged in 2022-10, with the labels that each got.

#1365 fix: 瓦片事件监听失效
  packages/layers/src/tile/tileFactory/base.ts
Labels: PR: reviewed-approved, bugfix

#1368 fix: 修复拾取高亮状态异常
  dev-demos/features/fix/demos/fix.tsx
  packages/core/src/services/interaction/PickingService.ts
Labels: PR: reviewed-approved, bugfix

#1364 fix: font 加载逻辑，添加font 加载完成事件
  dev-demos/features/point/demos/iconfont.tsx
  dev-demos/features/tile/hillshade.md
  packages/core/src/services/asset/FontService.ts
  packages/core/src/services/asset/IFontService.ts
  packages/core/src/services/asset/IIconService.ts
  packages/core/src/services/scene/ISceneService.ts
  packages/core/src/services/scene/SceneService.ts
  packages/scene/src/index.ts
Labels: PR: reviewed-approved, bugfix

#1373 chore: update version 2.9.31 -> 2.9.32
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1375 Fix: css 打包方式内联
  packages/component/.fatherrc.ts
  packages/core/src/services/asset/FontService.ts
  packages/maps/.fatherrc.ts
Labels: PR: reviewed-approved

#1378 fix: 修复 source 模块 parser 为 Json geometry 情况下数据拾取问题
  dev-demos/bugs/index.md
  dev-demos/bugs/source/demos/source-geometry.tsx
  dev-demos/bugs/source/source.md
  packages/core/src/services/interaction/PickingService.ts
  packages/source/src/parser/json.ts
  packages/source/src/source.ts
Labels: PR: reviewed-approved, bugfix

#1379 chore: update version 2.9.32 -> 2.9.33
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1383 chore: 更新版本 2.9.34
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1384 fix: 优化多图层 setData 效果不同步的现象
  dev-demos/features/fix/demos/fix.tsx
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/utils/layerData.ts
Labels: PR: reviewed-approved, bugfix

#1385 chore: update version 2.9.34 -> 2.9.35
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1387 chore: update version 2.9.35 -> 2.9.36
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1390 chore: 瓦片代码重构
  dev-demos/features/tile/rasterData/update.tsx
  dev-demos/features/tile/rasterDataUpdate.md
  dev-demos/features/tile/vector.md
  dev-demos/features/tile/vector/geojson-vt.tsx
  dev-demos/features/tile/vector/line.tsx
  packages/core/src/services/layer/ILayerService.ts
  packages/layers/src/index.ts
  packages/layers/src/point/models/earthFill.ts
  packages/layers/src/tile/interaction/TilePickService.ts
  packages/layers/src/tile/interaction/getFeatureData.ts
  packages/layers/src/tile/interaction/getRasterData.ts
  packages/layers/src/tile/interaction/utils.ts
  packages/layers/src/tile/interface.ts
  packages/layers/src/tile/manager/base.ts
  packages/layers/src/tile/manager/layerManager.ts
  packages/layers/src/tile/manager/mapLayerManager.ts
  packages/layers/src/tile/manager/tilePickerManager.ts
  packages/layers/src/tile/models/tileModel.ts
  packages/layers/src/tile/render/TileRenderService.ts
  packages/layers/src/tile/style/TileStyleService.ts
  packages/layers/src/tile/style/constants.ts
  packages/layers/src/tile/style/utils.ts
  packages/layers/src/tile/tileFactory/base.ts
  packages/layers/src/tile/tileFactory/layers/rasterDataLayer.ts
  packages/layers/src/tile/tileFactory/layers/tileTest.ts
  packages/layers/src/tile/tileFactory/layers/vectorLayer.ts
  packages/layers/src/tile/tileFactory/line.ts
  packages/layers/src/tile/tileFactory/mask.ts
  packages/layers/src/tile/tileFactory/point.ts
  packages/layers/src/tile/tileFactory/polygon.ts
  packages/layers/src/tile/tileFactory/raster.ts
  packages/layers/src/tile/tileFactory/rasterData.ts
  packages/layers/src/tile/tileFactory/test.ts
  packages/layers/src/tile/tileLayer/MapTileLayer.ts
  packages/layers/src/tile/tileLayer/TileLayer.ts
  packages/layers/src/tile/tileLayer/base.ts
  packages/layers/src/tile/tileLayer/baseMapTileLayer.ts
  packages/layers/src/tile/tileLayer/baseTileLayer.ts
  packages/layers/src/tile/tmsMapTileLayer.ts
  packages/layers/src/tile/tmsTileLayer.ts
  packages/layers/src/tile/utils.ts
Labels: PR: reviewed-approved, ignore-for-release

#1392 chore: 代码警告清理 & 部分代码优化
  dev-demos/features/tile/rasterData/loadImageRGB.tsx
  dev-demos/features/tile/rasterData/loadTiff.tsx
  packages/core/src/services/asset/FontService.ts
  packages/core/src/services/interaction/PickingService.ts
  packages/core/src/services/layer/StyleAttribute.ts
  packages/core/src/services/layer/StyleAttributeService.ts
  packages/core/src/services/renderer/IModel.ts
  packages/core/src/services/renderer/passes/BaseNormalPass.ts
  packages/core/src/services/renderer/passes/PostProcessor.ts
  packages/layers/src/core/BaseModel.ts
  packages/layers/src/core/triangulation.ts
  packages/layers/src/heatmap/models/heatmap.ts
  packages/layers/src/image/models/dataImage.ts
  packages/layers/src/image/models/image.ts
  packages/layers/src/image/models/tileDataImage.ts
  packages/layers/src/line/models/great_circle.ts
  packages/layers/src/plugins/FeatureScalePlugin.ts
  packages/layers/src/plugins/LightingPlugin.ts
  packages/layers/src/plugins/RegisterStyleAttributePlugin.ts
  packages/layers/src/point/models/image.ts
  packages/layers/src/polygon/models/ocean.ts
  packages/layers/src/polygon/models/water.ts
  packages/layers/src/raster/models/raster.ts
  packages/layers/src/raster/models/rasterRgb.ts
  packages/layers/src/raster/models/rasterTile.ts
  packages/layers/src/tile/tileFactory/base.ts
  packages/layers/src/tile/tileFactory/layers/vectorLayer.ts
  packages/layers/src/tile/tileFactory/rasterData.ts
  packages/layers/src/tile/tileFactory/test.ts
  packages/layers/src/tile/utils.ts
  packages/layers/src/utils/dataMappingStyle.ts
  packages/layers/src/utils/extrude_polyline.ts
  packages/layers/src/utils/multiPassRender.ts
  packages/layers/src/wind/models/wind.ts
  packages/map/src/camera.ts
  packages/map/src/earthmap.ts
  packages/map/src/geo/simple.ts
  packages/map/src/handler/mouse/mouse_handler.ts
  packages/map/src/handler/touch/two_touch.ts
  packages/map/src/map.ts
  packages/maps/src/amap2/Viewport.ts
  packages/maps/src/utils/amap/AMapBaseService.ts
  packages/renderer/src/regl/ReglFramebuffer.ts
  packages/renderer/src/regl/__tests__/attribute.spec.ts
  packages/source/src/transform/map.ts
  packages/three/src/core/baseLayer.ts
  packages/utils/src/ajax.ts
  packages/utils/src/dom.ts
  packages/utils/src/geo.ts
  packages/utils/src/lineAtOffset/greatCircle.ts
  packages/utils/src/lineAtOffset/index.ts
  packages/utils/src/lru_cache.ts
  packages/utils/src/tileset-manager/tileset-manager.ts
  packages/utils/src/workers/commonFeatureFunc.ts
  packages/utils/src/workers/extrude_polyline.ts
  packages/utils/src/workers/lineModel.ts
Labels: PR: reviewed-approved, ignore-for-release

#1393 fix:修复事件名丢失
  dev-demos/features/line/demos/greatcircleline.tsx
  dev-demos/features/line/demos/line.tsx
  dev-demos/features/line/demos/linearc.tsx
  dev-demos/features/mask/demos/heatmap.tsx
  dev-demos/features/polygon/demos/fill.tsx
  dev-docs/ConfigSchemaValidation.md
  dev-docs/IoC 容器、依赖注入与服务说明.md
  packages/layers/src/Geometry/index.ts
  packages/layers/src/Geometry/models/billboard.ts
  packages/layers/src/Geometry/models/plane.ts
  packages/layers/src/Geometry/models/sprite.ts
  packages/layers/src/canvas/index.ts
  packages/layers/src/citybuliding/building.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/heatmap/index.ts
  packages/layers/src/image/index.ts
  packages/layers/src/image/models/dataImage.ts
  packages/layers/src/image/models/image.ts
  packages/layers/src/image/models/tileDataImage.ts
  packages/layers/src/line/index.ts
  packages/layers/src/mask/index.ts
  packages/layers/src/plugins/DataMappingPlugin.ts
  packages/layers/src/plugins/DataSourcePlugin.ts
  packages/layers/src/plugins/FeatureScalePlugin.ts
  packages/layers/src/plugins/LayerModelPlugin.ts
  packages/layers/src/point/index.ts
  packages/layers/src/polygon/index.ts
  packages/layers/src/raster/index.ts
  packages/layers/src/raster/raster.ts
  packages/layers/src/tile/tileFactory/layers/rasterDataLayer.ts
  packages/layers/src/tile/tileFactory/layers/vectorLayer.ts
  packages/layers/src/wind/index.ts
  packages/layers/src/wind/models/wind.ts
  packages/scene/src/index.ts
  packages/source/src/source.ts
  packages/utils/src/lineAtOffset/index.ts
  stories/layerbuild/components/SourceTest.tsx
Labels: PR: reviewed-approved, bugfix

#1394 feat: 升级图例方法、图例更新事件
  dev-demos/bugs/source/demos/source-update.tsx
  dev-demos/bugs/source/sourceUpdate.md
  dev-demos/features/legend/cat.md
  dev-demos/features/legend/cat.tsx
  dev-demos/features/legend/useLine.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/layer/IStyleAttributeService.ts
  packages/core/src/services/layer/StyleAttributeService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/plugins/UpdateStyleAttributePlugin.ts
  packages/site/docs/common/layer/layer_event.md
  packages/site/docs/common/layer/layer_interaction.md
Labels: PR: reviewed-approved, feature

#1395 feat: 瓦片更新代码重构
  packages/core/src/services/layer/ILayerService.ts
  packages/layers/src/tile/manager/base.ts
  packages/layers/src/tile/manager/layerManager.ts
  packages/layers/src/tile/manager/mapLayerManager.ts
  packages/layers/src/tile/tileLayer/base.ts
  packages/utils/src/tileset-manager/tile.ts
Labels: PR: reviewed-approved, feature

#1397 chore: update version 2.9.36 -> 2.9.37
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1400 chore: add bands demo
  dev-demos/features/rasterLayer/demos/rasterNDVI.tsx
  dev-demos/features/rasterLayer/demos/rasterRgb3.tsx
  dev-demos/features/rasterLayer/rasterNDVI.md
  dev-demos/features/rasterLayer/rasterRgb3.md
  dev-demos/features/tile/worldmap.md
  dev-demos/features/tile/worldmap.tsx
Labels: PR: reviewed-approved, ignore-for-release

#1403 fix: 修复 gatsby 运行打包 iconfont 失败问题
  packages/component/src/assets/iconfont/iconfont.js
Labels: PR: reviewed-approved, bugfix

#1405 fix: 拾取操作
  dev-demos/tile/district/chinamap.tsx
  dev-demos/tile/district/rasterData.tsx
  dev-demos/tile/district/worldmap.tsx
  packages/core/src/services/interaction/PickingService.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/layer/LayerService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/tile/service/TileLayerService.ts
  packages/layers/src/tile/service/TilePickService.ts
  packages/layers/src/tile/tileFactory/layers/TileDebugLayer.ts
  packages/layers/src/tile/tileLayer/MapTileLayer.ts
  packages/layers/src/tile/tileLayer/base.ts
Labels: PR: unreviewed, bugfix

#1406 docs: 修复选择框类型控件事件说明文档
  packages/site/docs/common/control/select-event.md
Labels: PR: reviewed-approved, documentation

#1407 chore: 合并冲突
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/layer/LayerService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/plugins/LayerModelPlugin.ts
  packages/layers/src/tile/manager/base.ts
  packages/layers/src/tile/service/TileLayerService.ts
  packages/layers/src/tile/service/TilePickService.ts
  packages/layers/src/tile/tileFactory/base.ts
  packages/layers/src/tile/tileLayer/TileLayer.ts
  packages/layers/src/wind/models/wind.ts
  packages/scene/src/index.ts
Labels: PR: unreviewed, ignore-for-release

#1408 feat: simple line 支持
  dev-demos/tile/district/simpleLine.tsx
  dev-demos/tile/simpleLine.md
  packages/core/src/services/layer/ILayerService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/core/triangulation.ts
  packages/layers/src/line/index.ts
  packages/layers/src/plugins/DataMappingPlugin.ts
  packages/layers/src/point/__tests__/layer_init.spec.ts
  packages/source/src/source.ts
Labels: PR: unreviewed, feature

#1409 Chore tile
  dev-demos/features/tile/basemap/basemap.tsx
  dev-demos/features/tile/basemap/chinamap.tsx
  dev-demos/tile/district/debug.tsx
  dev-demos/tile/district/worldmap.tsx
  packages/core/src/inversify.config.ts
  packages/layers/src/tile/service/TileLayerService.ts
  packages/layers/src/tile/tileFactory/DebugTile.ts
  packages/layers/src/tile/tileFactory/ImageTile.ts
  packages/layers/src/tile/tileFactory/RasterTile.ts
  packages/layers/src/tile/tileFactory/VectorTile2.ts
  packages/layers/src/tile/tileFactory/debug.ts
  packages/layers/src/tile/tileFactory/layers/TileDebugLayer.ts
  packages/layers/src/tile/tileLayer/base.ts
  packages/maps/src/amap2/map.ts
Labels: PR: unreviewed

#1410 feat: add vector tile mask support
  dev-demos/tile/district/simpleLine.tsx
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/layer/LayerService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/tile/service/TileLayerService.ts
  packages/layers/src/tile/tileFactory/Tile.ts
  packages/layers/src/tile/tileFactory/VectorTile2.ts
  packages/layers/src/tile/tileFactory/util.ts
  packages/layers/src/utils/dataMappingStyle.ts
Labels: PR: unreviewed, feature

#1411 refactor: 控件 LayerControl 改造
  dev-demos/layer/control/layerControl.md
  dev-demos/layer/control/layerSwitch.md
  dev-demos/layer/control/layerSwitch.tsx
  packages/component/__tests__/layerControl.spec.ts
  packages/component/__tests__/layerSwitch.spec.ts
  packages/component/src/control/layerSwitch.ts
  packages/component/src/index.ts
  packages/site/docs/api/component/control/layerSwitch.zh.md
  packages/site/examples/component/control/demo/layerSwitch.ts
  packages/site/examples/component/control/demo/mapTheme.ts
  packages/site/examples/component/control/demo/meta.json
  packages/site/examples/component/control/demo/mouseLocation.ts
Labels: PR: reviewed-approved

#1413 feat: 修复 l7-component 打包依赖报错问题
  packages/component/src/control/layerSwitch.ts
Labels: PR: reviewed-approved, feature

#1414 feat: Merge master
  packages/component/src/control/layerSwitch.ts
Labels: PR: unreviewed, feature

#1415 fix: 修复 LayerSwitch 展示图层变更时触发两次的问题
  packages/component/src/control/layerSwitch.ts
Labels: PR: reviewed-approved, bugfix

#1416 feat: 增加 Mask Tile Layer
  dev-demos/tile/district/image.tsx
  dev-demos/tile/district/point.tsx
  dev-demos/tile/point.md
  packages/layers/src/tile/service/TileLayerService.ts
  packages/layers/src/tile/tileFactory/MaskTile.ts
  packages/layers/src/tile/tileFactory/index.ts
  packages/layers/src/tile/tileFactory/util.ts
  packages/scene/src/index.ts
Labels: PR: unreviewed, feature

#1417 Chore tile
  dev-demos/tile/district/worldmap.tsx
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/source/ISourceService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/plugins/DataMappingPlugin.ts
  packages/layers/src/plugins/LayerModelPlugin.ts
  packages/layers/src/polygon/models/index.ts
  packages/layers/src/tile/manager/layerManager.ts
  packages/layers/src/tile/models/tileModel.ts
  packages/layers/src/tile/style/utils.ts
  packages/layers/src/tile/tileFactory/DebugTile.ts
  packages/layers/src/tile/tileFactory/VectorTile2.ts
  packages/layers/src/tile/tileFactory/base.ts
  packages/layers/src/tile/tileFactory/debug.ts
  packages/layers/src/tile/tileFactory/mask.ts
  packages/layers/src/tile/tileFactory/raster.ts
  packages/layers/src/tile/tileFactory/rasterData.ts
  packages/layers/src/tile/tileFactory/vectortile.ts
  packages/layers/src/tile/tileLayer/BaseLayer.ts
  packages/layers/src/tile/tileLayer/MapTileLayer.ts
  packages/layers/src/tile/tileLayer/TileLayer.ts
  packages/layers/src/utils/layerData.ts
  packages/source/src/source.ts
  packages/three/src/core/baseLayer.ts
Labels: PR: unreviewed

#1418 feat: remove tile model
  dev-demos/tile/district/point.tsx
  packages/core/src/services/layer/ILayerService.ts
  packages/layers/src/index.ts
  packages/layers/src/line/index.ts
  packages/layers/src/line/models/index.ts
  packages/layers/src/mask/index.ts
  packages/layers/src/mask/models/index.ts
  packages/layers/src/point/index.ts
  packages/layers/src/point/models/index.ts
  packages/layers/src/polygon/index.ts
  packages/layers/src/polygon/models/index.ts
  packages/layers/src/raster/index.ts
  packages/layers/src/raster/models/index.ts
  packages/layers/src/tile/models/tileModel.ts
  packages/layers/src/tile/service/TileLayerService.ts
  packages/layers/src/tile/tileFactory/RasterTile.ts
  packages/layers/src/tile/tileFactory/layers/TileDebugLayer.ts
  packages/layers/src/tile/tileFactory/util.ts
Labels: PR: unreviewed, feature

#1419 fix: fix mask tile layer err
  dev-demos/tile/district/worldmap.tsx
  packages/core/package.json
  packages/core/src/services/asset/FontService.ts
  packages/core/src/services/layer/LayerService.ts
  packages/layers/src/index.ts
  packages/layers/src/mask/index.ts
  packages/layers/src/tile/tileFactory/MaskTile.ts
  packages/layers/src/tile/tileFactory/layers/TileDebugLayer.ts
  packages/layers/src/tile/tileFactory/layers/vectorLayer.ts
Labels: PR: reviewed-approved, bugfix

#1420 Chore Pick 拾取方案
  dev-demos/tile/district/worldmap.tsx
  packages/core/src/services/interaction/IPickingService.ts
  packages/core/src/services/interaction/PickingService.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/core/LayerPickService.ts
  packages/layers/src/index.ts
  packages/layers/src/tile/service/TileLayerService.ts
  packages/layers/src/tile/service/TilePickService.ts
  packages/layers/src/tile/tileFactory/Tile.ts
  packages/layers/src/tile/tileFactory/VectorTile.ts
  packages/layers/src/tile/tileFactory/index.ts
  packages/layers/src/tile/tileFactory/layers/TileDebugLayer.ts
  packages/layers/src/tile/tileLayer/BaseLayer.ts
Labels: PR: reviewed-approved

#1421 Chore tile
  dev-demos/tile/district/worldmap.tsx
  packages/layers/src/tile/service/TilePickService.ts
  packages/layers/src/tile/tileFactory/VectorTile.ts
  packages/source/src/parser/mvt.ts
Labels: PR: reviewed-approved

#1424 Feat tile layer
  dev-demos/tile/district/simpleLine.tsx
  dev-demos/tile/district/worldmap.tsx
  packages/core/src/inversify.config.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/layers/src/Geometry/index.ts
  packages/layers/src/canvas/index.ts
  packages/layers/src/citybuliding/building.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/earth/index.ts
  packages/layers/src/heatmap/index.ts
  packages/layers/src/image/index.ts
  packages/layers/src/line/index.ts
  packages/layers/src/mask/index.ts
  packages/layers/src/point/index.ts
  packages/layers/src/polygon/index.ts
  packages/layers/src/raster/index.ts
  packages/layers/src/tile/service/TilePickService.ts
  packages/layers/src/tile/tileFactory/DebugTile.ts
  packages/layers/src/tile/tileFactory/RasterRGBTile.ts
  packages/layers/src/tile/tileFactory/RasterTile.ts
  packages/layers/src/tile/tileFactory/VectorTile.ts
  packages/layers/src/tile/tileFactory/layers/RasterDataLayer.ts
  packages/layers/src/wind/index.ts
  packages/utils/src/tileset-manager/tileset-manager.ts
Labels: PR: unreviewed

#1425 Feat tile layer 文本瓦片shape 设置
  dev-demos/tile/district/chinamap.tsx
  dev-demos/tile/district/worldmap.tsx
  packages/layers/src/point/index.ts
  packages/layers/src/point/models/text.ts
Labels: PR: unreviewed

#1426 feat: Tile style update
  dev-demos/tile/district/imageRGB.tsx
  dev-demos/tile/district/rasterData.tsx
  dev-demos/tile/district/simpleLine.tsx
  packages/core/src/services/interaction/PickingService.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/tile/interaction/utils.ts
  packages/layers/src/tile/service/TileLayerService.ts
  packages/layers/src/tile/service/TilePickService.ts
  packages/layers/src/tile/style/style.ts
  packages/layers/src/tile/tileFactory/RasterTile.ts
  packages/layers/src/tile/tileFactory/Tile.ts
  packages/layers/src/tile/tileLayer/BaseLayer.ts
  packages/layers/src/tile/utils.ts
Labels: PR: unreviewed, feature

#1428 feat: tile style update
  packages/core/src/services/layer/ILayerService.ts
  packages/layers/src/tile/interaction/TilePickService.ts
  packages/layers/src/tile/manager/mapLayerManager.ts
  packages/layers/src/tile/render/TileRenderService.ts
  packages/layers/src/tile/service/TilePickService.ts
  packages/layers/src/tile/style/TileStyleService.ts
  packages/layers/src/tile/style/constants.ts
  packages/layers/src/tile/style/style.ts
  packages/layers/src/tile/style/utils.ts
  packages/layers/src/tile/tileLayer/BaseLayer.ts
  packages/layers/src/tile/utils.ts
Labels: PR: unreviewed, feature

#1433 chore: update version 2.10.0 -> 2.10.1
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1435 Chore tslint
  package.json
  packages/layers/src/canvas/index.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/earth/index.ts
  packages/layers/src/line/index.ts
  packages/layers/src/mask/index.ts
  packages/layers/src/plugins/DataMappingPlugin.ts
  packages/layers/src/plugins/DataSourcePlugin.ts
  packages/layers/src/plugins/FeatureScalePlugin.ts
  packages/layers/src/plugins/RegisterStyleAttributePlugin.ts
  packages/layers/src/plugins/ShaderUniformPlugin.ts
  packages/layers/src/point/index.ts
  packages/layers/src/polygon/index.ts
  packages/layers/src/tile/utils.ts
  packages/layers/src/utils/dataMappingStyle.ts
  packages/layers/src/utils/layerData.ts
  packages/map/src/geo/lng_lat_bounds.ts
  packages/maps/src/earth/map.ts
  packages/maps/src/map/map.ts
  packages/maps/src/mapbox/map.ts
  packages/maps/src/utils/index.ts
  packages/maps/src/utils/utils.ts
  packages/source/src/parser/geojsonvt.ts
  packages/source/src/parser/json.ts
  packages/source/src/parser/raster-tile.ts
  packages/source/src/parser/raster.ts
  packages/source/src/parser/rasterRgb.ts
  packages/source/src/utils/util.ts
  packages/three/src/core/baseLayer.ts
  packages/utils/src/lineAtOffset/arc.ts
  packages/utils/src/lineAtOffset/greatCircle.ts
  packages/utils/src/lineAtOffset/index.ts
  packages/utils/src/tileset-manager/tile.ts
  packages/utils/src/tileset-manager/tileset-manager.ts
  tslint.json
Labels: PR: reviewed-approved

#1431 Feat 新增 WMS 和 WMTS 服务支持
  dev-demos/tile/district/image.tsx
  dev-demos/tile/district/wms.tsx
  dev-demos/tile/district/wmts.tsx
  dev-demos/tile/wmsmap.md
  dev-demos/tile/wmts.md
  packages/core/src/services/source/ISourceService.ts
  packages/layers/src/tile/tileFactory/VectorTile.ts
  packages/source/src/interface.ts
  packages/source/src/parser/geojsonvt.ts
  packages/source/src/parser/mvt.ts
  packages/source/src/parser/raster-tile.ts
  packages/source/src/parser/testTile.ts
  packages/source/src/source.ts
  packages/source/src/utils/tile/getRasterTile.ts
  packages/utils/src/ajax.ts
  packages/utils/src/tileset-manager/utils/tile-url.ts
Labels: PR: unreviewed

#1423 docs: 添加marker demo
  dev-demos/features/marker/demos/marker.tsx
  dev-demos/features/marker/marker.md
Labels: PR: reviewed-approved, documentation

#1436 fix: fix code tslint err
  dev-demos/features/line/demos/greatcircleline.tsx
  dev-demos/features/line/demos/line.tsx
  dev-demos/features/line/demos/linearc.tsx
  packages/layers/src/canvas/index.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/plugins/LayerAnimateStylePlugin.ts
  packages/layers/src/plugins/ShaderUniformPlugin.ts
  packages/layers/src/plugins/UpdateStyleAttributePlugin.ts
  packages/renderer/src/regl/ReglModel.ts
  packages/source/src/parser/geojsonvt.ts
  packages/source/src/parser/json.ts
  packages/source/src/parser/raster.ts
  packages/source/src/parser/rasterRgb.ts
  packages/source/src/parser/testTile.ts
  packages/utils/__tests__/lineAtOffset.spec.ts
  packages/utils/src/lineAtOffset/greatCircle.ts
  packages/utils/src/lineAtOffset/index.ts
  packages/utils/src/lineAtOffset/line.ts
Labels: PR: reviewed-approved, bugfix

#1437 fix: fix heatmap err
  packages/layers/src/heatmap/models/heatmap.ts
Labels: PR: unreviewed, bugfix

#1443 fix: fix windLayer render failed
  packages/layers/src/wind/models/wind.ts
Labels: PR: reviewed-approved, bugfix

#1441 fix: 修复 LayerPopup 中的类型 BaseLayer => ILayer
  packages/component/src/popup/layerPopup.ts
Labels: PR: partially-approved, bugfix

#1440 feat: 控件的 position 支持自定义 DOM 容器
  dev-demos/layer/control/position.tsx
  packages/component/__tests__/control.spec.ts
  packages/component/src/control/baseControl/control.ts
  packages/component/src/control/baseControl/popperControl.ts
  packages/site/docs/api/component/control/control.zh.md
  packages/site/docs/common/control/api.md
Labels: PR: partially-approved, feature

#1447 feat: 瓦片图层事件获取数据、瓦片数据解析
  dev-demos/layer/control/exportImage.tsx
  dev-demos/layer/control/hide.tsx
  dev-demos/layer/control/layerSwitch.tsx
  dev-demos/layer/control/mapTheme.tsx
  dev-demos/layer/control/navigation.tsx
  dev-demos/layer/control/remove.tsx
  dev-demos/layer/control/setOptions.tsx
  dev-demos/layer/popup/layerPopup.tsx
  dev-demos/tile/district/polygon.tsx
  dev-demos/tile/district/worldmap.tsx
  packages/component/src/control/baseControl/popperControl.ts
  packages/component/src/control/baseControl/selectControl.ts
  packages/component/src/control/fullscreen.ts
  packages/component/src/popup/layerPopup.ts
  packages/component/src/popup/popup.ts
  packages/core/src/services/interaction/IPickingService.ts
  packages/core/src/services/interaction/PickingService.ts
  packages/layers/src/tile/service/TileLayerService.ts
  packages/layers/src/tile/service/TilePickService.ts
  packages/layers/src/tile/tileFactory/Tile.ts
  packages/layers/src/tile/tileFactory/VectorTile.ts
  packages/source/src/parser/mvt.ts
  packages/source/src/source.ts
Labels: PR: unreviewed, feature

#1449 feat: 完善矢量图层事件的数据拾取
  dev-demos/features/rasterLayer/demos/rasterRgb3.tsx
  dev-demos/tile/district/geojsonvt-line.tsx
  dev-demos/tile/district/image.tsx
  packages/core/src/services/interaction/PickingService.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/layers/src/tile/service/TilePickService.ts
  packages/layers/src/tile/service/TileSourceService.ts
  packages/layers/src/tile/tileFactory/MaskTile.ts
  packages/layers/src/tile/tileFactory/Tile.ts
  packages/layers/src/tile/tileFactory/VectorTile.ts
Labels: PR: unreviewed, feature

#1442 Publish
  dev-demos/tile/district/geojsonvt-line.tsx
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
  packages/utils/src/ajax.ts
Labels: PR: unreviewed

#1451 fix: 修复 babel 升级导致的打包报错问题
  package.json
Labels: PR: reviewed-approved, bugfix

#1444 fix: fix lint err
  packages/layers/src/line/index.ts
  packages/layers/src/mask/index.ts
  packages/layers/src/plugins/UpdateStyleAttributePlugin.ts
Labels: PR: unreviewed, bugfix
