Repository antvis/L7, pull requests merged in 2023-08, with the labels that each got.

#1778 fix: 修复图层不可见时请求不必要瓦片资源问题
  package.json
  packages/layers/src/tile/tileLayer/BaseLayer.ts
Labels: bugfix

#1775 docs: 更新未注册token 提示
  dev-demos/features/line/demos/linedash.tsx
  packages/core/src/services/config/warnInfo.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/core/BaseModel.ts
  packages/site/docs/api/map/map.zh.md
  packages/site/docs/api/point_layer/style.zh.md
  packages/site/docs/common/layer/style_encode.md
Labels: documentation

#1780 chore: update 版本 2.17.8
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: ignore-for-release

#1786 feat: 缩放控件 zoom 新增 showZoom 配置，用于控制是否展示 zoom 数值
  dev-demos/component/control/zoom.tsx
  packages/component/src/control/zoom.ts
  packages/component/src/css/index.css
  packages/component/src/css/zoom.less
  packages/site/docs/api/component/control/zoom.zh.md
Labels: feature

#1787 chore: 通过打包配置更新版本
  packages/l7/.fatherrc.ts
  packages/l7/__tests__/version.spec.ts
  packages/l7/src/version.ts
Labels: ignore-for-release

#1776 chore: 升级官网行政地图 L7Plot 版本
  package.json
  packages/site/package.json
Labels: ignore-for-release

#1793 docs: 官网示例新增 L7Plot 复合图层透出
  package.json
  packages/site/.dumi/global.ts
  packages/site/.dumirc.ts
  packages/site/examples/composite-layers/l7plot/API.en.md
  packages/site/examples/composite-layers/l7plot/API.zh.md
  packages/site/examples/composite-layers/l7plot/demo/flow-layer.js
  packages/site/examples/composite-layers/l7plot/demo/icon-layer.js
  packages/site/examples/composite-layers/l7plot/demo/image-layer.js
  packages/site/examples/composite-layers/l7plot/demo/meta.json
  packages/site/examples/composite-layers/l7plot/index.en.md
  packages/site/examples/composite-layers/l7plot/index.zh.md
  packages/site/package.json
Labels: documentation

#1799 docs: update issue template
  .github/ISSUE_TEMPLATE.md
  .github/workflows/main.yml
Labels: documentation
