Repository antvis/L7, pull requests merged in 2023-02, with the labels that each got.

#1582 Publish
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed

#1584 Fix map max zoom
  dev-demos/bugs/marker/demo.tsx
  dev-demos/bugs/polygon/demos/district.tsx
  dev-demos/bugs/polygon/district.md
  dev-demos/component/control/exportImage.tsx
  dev-demos/component/control/fullscreen.tsx
  dev-demos/component/control/hide.tsx
  dev-demos/component/control/layerSwitch.tsx
  dev-demos/component/control/logo.tsx
  dev-demos/component/control/mapTheme.tsx
  dev-demos/component/control/mouseLocation.tsx
  dev-demos/component/control/scale.tsx
  dev-demos/component/popup/layerPopup.tsx
  dev-demos/component/popup/popup.tsx
  dev-demos/draw/demo/drawControl.tsx
  dev-demos/draw/demo/drawpolygon.tsx
  dev-demos/features/citybuilding/amap1.tsx
  dev-demos/features/citybuilding/amap2.tsx
  dev-demos/features/citybuilding/mapbox.tsx
  dev-demos/features/earth/earth.tsx
  dev-demos/features/imageLayer/raster.tsx
  dev-demos/features/legend/cat.tsx
  dev-demos/features/tile/worldmap.tsx
  dev-demos/gallery/scale/diverging.tsx
  dev-demos/gallery/scale/linear.tsx
  dev-demos/gallery/scale/map.tsx
  dev-demos/gallery/scale/quantile.tsx
  dev-demos/gallery/scale/quantize.tsx
  dev-demos/gallery/scale/sequential.tsx
  dev-demos/gallery/scale/threshold.tsx
  dev-demos/raster/demos/rasterFile.tsx
  package.json
  packages/site/docs/common/layer/layer_encode.md
  packages/site/docs/tutorial/scale.zh.md
  packages/source/src/transform/hexagon.ts
  packages/utils/src/tileset-manager/index.ts
Labels: PR: unreviewed

#1586 feat: 去除 Control options 多余类型导致的 Omit 失效问题
  packages/component/src/control/baseControl/control.ts
Labels: PR: reviewed-approved, feature

#1589 chore: add ChatGPT action
  .github/workflows/chatgpt.yml
  dev-demos/draw/demo/drawpolygon.tsx
  packages/site/examples/component/marker/demo/defaultmarker.js
  packages/site/examples/component/marker/demo/meta.json
  packages/site/examples/gallery/animate/demo/meta.json
  packages/site/examples/gallery/animate/demo/timeline.js
Labels: PR: reviewed-approved, ignore-for-release

#1591 feat: mvt 实现getCustomdata 方法
  dev-demos/tile/Vector/demos/citytile.tsx
  packages/site/docs/api/source/mvt.zh.md
  packages/source/src/parser/mvt.ts
Labels: PR: unreviewed, feature

#1593 Publish
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed

#1594 feat: 栅格表达式添加 min/max/log10/log2/计算逻辑&文本更新避让能力完善
  dev-demos/bugs/point/demos/image.tsx
  dev-demos/bugs/point/demos/text.tsx
  packages/core/src/services/asset/FontService.ts
  packages/core/src/services/asset/IconService.ts
  packages/layers/src/point/models/fill.ts
  packages/layers/src/point/models/fillmage.ts
  packages/layers/src/point/models/image.ts
  packages/layers/src/point/models/text.ts
  packages/site/docs/common/layer/layer_encode.md
  packages/source/src/utils/bandOperation/math.ts
  packages/utils/src/color.ts
  packages/utils/src/index.ts
Labels: PR: unreviewed, feature

#1596 Publish 2.13.5
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed

#1599 fix: 删除单独的sourcelog,优化了log 流程
  packages/core/src/services/debug/DebugService.ts
  packages/core/src/services/debug/IDebugService.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/layer/LayerService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/line/models/line.ts
  packages/layers/src/plugins/DataMappingPlugin.ts
  packages/layers/src/plugins/DataSourcePlugin.ts
  packages/layers/src/plugins/FeatureScalePlugin.ts
  packages/layers/src/plugins/LayerModelPlugin.ts
  packages/source/src/log.ts
  packages/source/src/source.ts
Labels: PR: unreviewed, bugfix

#1598 Fix 矢量瓦片拾取&线纹理&一些lint fixed
  dev-demos/tile/Vector/demos/event.tsx
  dev-demos/tile/Vector/event.md
  packages/core/src/services/interaction/PickingService.ts
  packages/layers/src/line/models/line.ts
  packages/layers/src/tile/service/TilePickService.ts
  packages/layers/src/tile/service/TileSourceService.ts
  packages/layers/src/tile/tileFactory/VectorTile.ts
  packages/site/docs/api/tile/common/options.zh.md
  packages/source/src/index.ts
  packages/source/src/parser/geojson.ts
  packages/source/src/source.ts
Labels: PR: unreviewed

#1590 feat: add DebugService
  dev-demos/features/line/demos/linedash.tsx
  packages/core/src/index.ts
  packages/core/src/inversify.config.ts
  packages/core/src/services/config/IConfigService.ts
  packages/core/src/services/debug/DebugService.ts
  packages/core/src/services/debug/IDebugService.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/layer/LayerService.ts
  packages/core/src/services/scene/SceneService.ts
  packages/core/src/types.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/plugins/DataMappingPlugin.ts
  packages/layers/src/plugins/DataSourcePlugin.ts
  packages/layers/src/plugins/FeatureScalePlugin.ts
  packages/layers/src/plugins/LayerModelPlugin.ts
  packages/layers/src/point/__tests__/layer_init.spec.ts
  packages/renderer/src/regl/index.ts
  packages/scene/src/index.ts
  packages/site/.dumirc.ts
  packages/site/docs/api/debug/debugservice.en.md
  packages/site/docs/api/debug/debugservice.zh.md
  packages/site/docs/api/scene.zh.md
  packages/site/docs/tutorial/debug/layerInit.en.md
  packages/site/docs/tutorial/debug/layerInit.zh.md
  packages/site/docs/tutorial/debug/mapInit.en.md
  packages/site/docs/tutorial/debug/mapInit.zh.md
  packages/site/docs/tutorial/debug/render.en.md
  packages/site/docs/tutorial/debug/render.zh.md
  packages/utils/src/hash.ts
  packages/utils/src/index.ts
Labels: PR: reviewed-approved, feature

#1608 chore: remove extra libs
  package.json
Labels: PR: reviewed-approved, ignore-for-release

#1607 fix: fix website demo err
  packages/site/examples/tutorial/control/demo/amap.js
Labels: PR: unreviewed, bugfix

#1610 chore: 修改 debugService 的类型定义
  packages/core/src/services/debug/DebugService.ts
  packages/core/src/services/debug/IDebugService.ts
Labels: PR: unreviewed, ignore-for-release

#1612 refactor: 修改 debugService 日志结构
  dev-demos/features/line/demos/linedash.tsx
  packages/core/src/services/debug/DebugService.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/plugins/DataMappingPlugin.ts
  packages/layers/src/plugins/DataSourcePlugin.ts
  packages/layers/src/plugins/FeatureScalePlugin.ts
  packages/layers/src/plugins/LayerModelPlugin.ts
Labels: PR: unreviewed

#1613 chore: update version 2.13.6 -> 2.13.7
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed, ignore-for-release

#1614 fix: debug service undefined
  packages/layers/src/core/BaseLayer.ts
Labels: PR: reviewed-approved, bugfix

#1615 chore: update version 2.13.7 -> 2.13.8
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1616 fix: 修复高德2.x 下，Marker 在 IOS 终端的 click 事件失效
  dev-demos/features/fix/demos/fix2.tsx
  packages/component/src/marker.ts
  packages/utils/src/env.ts
Labels: PR: unreviewed, bugfix

#1617 chore: update version 2.13.8 -> 2.13.9
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1620 fix: 修复图层数据更新时，LayerPopup 不消失的问题
  packages/component/src/popup/layerPopup.ts
Labels: PR: partially-approved, bugfix

#1625 Publish 2.14.0 beta
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed
