Repository antvis/L7, pull requests merged in 2023-12, with the labels that each got.

#2090 补充腾讯地图文档
  packages/site/docs/api/map/tencent.en.md
  packages/site/docs/api/map/tencent.zh.md
Labels: documentation

#2111 fix: radar 数据映射
  packages/layers/src/point/models/radar.ts
  packages/layers/src/point/shaders/radar/radar_frag.glsl
  packages/layers/src/point/shaders/radar/radar_vert.glsl
Labels: bugfix, pr(fix)

#2117 chore: ocean
  dev-demos/features/polygon/demos/ocean.tsx
  dev-demos/features/polygon/demos/water.tsx
  package.json
  packages/layers/src/polygon/models/ocean.ts
  packages/layers/src/polygon/models/water.ts
  packages/layers/src/polygon/shaders/extrude/polygon_extrudetex_frag.glsl
  packages/layers/src/polygon/shaders/water/polygon_ocean_frag.glsl
  packages/layers/src/polygon/shaders/water/polygon_ocean_vert.glsl
  packages/layers/src/polygon/shaders/water/polygon_water_frag.glsl
  packages/layers/src/polygon/shaders/water/polygon_water_vert.glsl
  packages/renderer/package.json
  packages/renderer/src/regl/ReglModel.ts
Labels: ignore-for-release, pr(chore)

#2122 fix: blend in device api
  dev-demos/features/point/demos/circle-device.tsx
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/plugins/PixelPickingPlugin.ts
  packages/renderer/src/device/DeviceModel.ts
  packages/renderer/src/device/index.ts
Labels: bugfix, pr(fix)

#2121 chore: pointLayer image
  packages/layers/src/point/models/image.ts
  packages/layers/src/point/shaders/image_frag.glsl
  packages/layers/src/point/shaders/image_vert.glsl
Labels: ignore-for-release, pr(chore)

#2124 chore: 重构fill 目录结构
  packages/layers/src/polygon/models/fill.ts
  packages/layers/src/polygon/models/ocean.ts
  packages/layers/src/polygon/shaders/fill/fill_frag.glsl
  packages/layers/src/polygon/shaders/fill/fill_linear_frag.glsl
  packages/layers/src/polygon/shaders/fill/fill_linear_vert.glsl
  packages/layers/src/polygon/shaders/fill/fill_vert.glsl
  packages/layers/src/polygon/shaders/ocean/ocean_frag.glsl
  packages/layers/src/polygon/shaders/ocean/ocean_vert.glsl
Labels: ignore-for-release, pr(chore)

#2142 fix: billboard rotation
  dev-demos/features/geometry/demos/billboard.tsx
  packages/layers/src/core/BaseModel.ts
  packages/layers/src/geometry/models/billboard.ts
  packages/layers/src/geometry/shaders/billboard_frag.glsl
  packages/layers/src/geometry/shaders/billboard_vert.glsl
Labels: bugfix, pr(fix)

#2149 Chore citybuilding update engine
  dev-demos/features/citybuilding/amap1.tsx
  dev-demos/features/citybuilding/amap2.tsx
  dev-demos/features/citybuilding/mapbox.tsx
  packages/layers/src/citybuliding/models/build.ts
  packages/layers/src/citybuliding/shaders/build_frag.glsl
  packages/layers/src/citybuliding/shaders/build_vert.glsl
Labels: AntV OSCP

#2148 chore: 升级geometry的plane支持G引擎
  dev-demos/features/geometry/demos/plane.tsx
  dev-demos/features/geometry/plane.md
  packages/layers/src/geometry/models/plane.ts
  packages/layers/src/geometry/shaders/plane_frag.glsl
  packages/layers/src/geometry/shaders/plane_vert.glsl
Labels: ignore-for-release, pr(chore)

#2135 [wip]chore: update pointLayer billboard draw engine
  dev-demos/features/point/demos/billboard.tsx
  dev-demos/features/point/pointBillboard.md
  packages/layers/src/point/models/billboard_point.ts
  packages/layers/src/point/shaders/billboard_point_frag.glsl
  packages/layers/src/point/shaders/billboard_point_vert.glsl
Labels: ignore-for-release

#2155 feat: migrate sprite layer
  dev-demos/features/geometry/demos/sprite.tsx
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/geometry/models/sprite.ts
  packages/renderer/src/device/DeviceBuffer.ts
  packages/renderer/src/device/DeviceModel.ts
Labels: feature, pr(feature)

#2136 feat: 新增 Swipe 卷帘对比控件
  dev-demos/component/control/swipe.md
  dev-demos/component/control/swipe.tsx
  packages/component/src/control/swipe.ts
  packages/component/src/css/index.css
  packages/component/src/css/index.less
  packages/component/src/css/swipe.less
  packages/component/src/index.ts
  packages/layers/src/core/BaseLayer.ts
  packages/site/docs/api/component/swipe.en.md
  packages/site/docs/api/component/swipe.zh.md
  packages/site/docs/common/control/event.en.md
  packages/site/examples/component/control/demo/meta.json
  packages/site/examples/component/control/demo/swipe.ts
Labels: feature, pr(feature)

#2162 fix: 箭头问题
  dev-demos/features/line/demos/lineArrow.tsx
  packages/layers/src/line/shaders/flow/flow_line_vert.glsl
Labels: bugfix, pr(fix)

#2175 chore: recombination heatmapLayer's model and layer
  dev-demos/features/heatmap/demos/grid.tsx
  dev-demos/features/heatmap/demos/grid3d.tsx
  dev-demos/features/heatmap/grid.md
  dev-demos/features/heatmap/grid3d.md
  dev-demos/features/line/demos/line_stroke.tsx
  packages/layers/src/heatmap/models/grid.ts
  packages/layers/src/heatmap/models/grid3d.ts
  packages/layers/src/heatmap/models/heatmap.ts
  packages/layers/src/heatmap/models/hexagon.ts
  packages/layers/src/heatmap/shaders/grid/grid_frag.glsl
  packages/layers/src/heatmap/shaders/grid/grid_vert.glsl
  packages/layers/src/heatmap/shaders/grid3d/grid_3d_frag.glsl
  packages/layers/src/heatmap/shaders/grid3d/grid_3d_vert.glsl
  packages/layers/src/heatmap/shaders/heatmap/heatmap_3d_frag.glsl
  packages/layers/src/heatmap/shaders/heatmap/heatmap_3d_vert.glsl
  packages/layers/src/heatmap/shaders/heatmap/heatmap_frag.glsl
  packages/layers/src/heatmap/shaders/heatmap/heatmap_framebuffer_frag.glsl
  packages/layers/src/heatmap/shaders/heatmap/heatmap_framebuffer_vert.glsl
  packages/layers/src/heatmap/shaders/heatmap/heatmap_vert.glsl
  packages/layers/src/heatmap/shaders/hexagon/hexagon_frag.glsl
  packages/layers/src/heatmap/shaders/hexagon/hexagon_vert.glsl
Labels: ignore-for-release, pr(chore)

#2188 fix: each layer should have its own picking ubo
  dev-demos/features/mask/demos/singleMask.tsx
  dev-demos/features/point/demos/circle-device.tsx
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/layer/LayerService.ts
  packages/core/src/shaders/scene_uniforms.glsl
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/plugins/PixelPickingPlugin.ts
  packages/layers/src/plugins/ShaderUniformPlugin.ts
  packages/renderer/src/device/DeviceBuffer.ts
  packages/renderer/src/device/DeviceModel.ts
  packages/renderer/src/device/index.ts
Labels: bugfix, pr(fix)

#2181 Chore:refactor pointLayer model and shader
  dev-demos/features/point/demos/circle-device.tsx
  dev-demos/features/point/pointBillboard.md
  dev-demos/features/point/pointCircleDevice.md
  dev-demos/features/point/pointCircleWebGPU.md
  dev-demos/features/point/pointColumn.md
  dev-demos/features/point/pointEarthfill.md
  dev-demos/features/point/pointFillImage.md
  dev-demos/features/point/pointNormalDevice.md
  dev-demos/features/point/pointRadar.md
  packages/layers/src/point/models/billboard_point.ts
  packages/layers/src/point/models/earthExtrude.ts
  packages/layers/src/point/models/earthFill.ts
  packages/layers/src/point/models/extrude.ts
  packages/layers/src/point/models/fill.ts
  packages/layers/src/point/models/fillImage.ts
  packages/layers/src/point/models/image.ts
  packages/layers/src/point/models/normal.ts
  packages/layers/src/point/models/radar.ts
  packages/layers/src/point/models/text.ts
  packages/layers/src/point/shaders/animate/wave_frag.glsl
  packages/layers/src/point/shaders/billboard/billboard_point_frag.glsl
  packages/layers/src/point/shaders/billboard/billboard_point_vert.glsl
  packages/layers/src/point/shaders/earthExtrude/earthExtrude_frag.glsl
  packages/layers/src/point/shaders/earthExtrude/earthExtrude_vert.glsl
  packages/layers/src/point/shaders/earthFill/earthFill_frag.glsl
  packages/layers/src/point/shaders/earthFill/earthFill_vert.glsl
  packages/layers/src/point/shaders/fill/fill_frag.glsl
  packages/layers/src/point/shaders/fill/fill_vert.glsl
  packages/layers/src/point/shaders/fillImage/fillImage_frag.glsl
  packages/layers/src/point/shaders/fillImage/fillImage_vert.glsl
  packages/layers/src/point/shaders/image/image_frag.glsl
  packages/layers/src/point/shaders/image/image_vert.glsl
  packages/layers/src/point/shaders/normal/normal_frag.glsl
  packages/layers/src/point/shaders/normal/normal_vert.glsl
  packages/layers/src/point/shaders/radar/radar_vert.glsl
  packages/layers/src/point/shaders/text/text_frag.glsl
  packages/layers/src/point/shaders/text/text_vert.glsl
Labels: AntV OSCP

#2186 feat: imageLayer支持图像增强
  dev-demos/features/imageLayer/image.tsx
  dev-demos/features/line/demos/linePopulation.tsx
  packages/layers/src/core/interface.ts
  packages/layers/src/image/models/image.ts
  packages/layers/src/image/shaders/image_frag.glsl
  packages/layers/src/image/shaders/image_vert.glsl
  packages/site/docs/api/image_layer/style.zh.md
  packages/utils/.umirc.ts
  packages/utils/src/index.ts
Labels: feature, pr(feature)

#2194 fix: 地图样式，文档样式
  examples/demos/index.ts
  examples/demos/raster/tiff.ts
  examples/index.html
  examples/view.tsx
  packages/maps/src/bmap/logo.css
  packages/maps/src/tmap/logo.css
  packages/maps/src/tmap/map.ts
  packages/site/docs/common/control/api.en.md
  packages/site/docs/common/control/btn-api.en.md
  packages/site/docs/common/control/event.en.md
  packages/site/docs/common/control/method.en.md
  packages/site/docs/common/control/popper-api.en.md
  packages/site/docs/common/control/popper-event.en.md
  packages/site/docs/common/control/select-event.en.md
Labels: bugfix, pr(fix)

#2199 fix: version & publish 2.20.8
  examples/view.tsx
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: bugfix, pr(fix)

#2196 fix: destroy event when destroy map
  .umirc.ts
  dev-demos/bugs/scene/demos/testDestroy.tsx
  dev-demos/bugs/scene/testDestroy.md
  packages/map/src/earthmap.ts
  packages/map/src/map.ts
Labels: bugfix, pr(fix)

#2206 fix: 大数据量 updateAttributeByFeatureRange 内存溢出
  examples/demos/bugfix/color.ts
  examples/demos/bugfix/index.ts
  examples/demos/index.ts
  examples/demos/point/fill.ts
  examples/demos/point/image.ts
  packages/core/src/services/layer/StyleAttributeService.ts
Labels: bug, bugfix, pr(fix)

#2211 feat: 图层显隐组件 LayerSwitch 新增单选模式
  .vscode/settings.json
  dev-demos/component/control/layerSwitch.tsx
  packages/component/src/control/baseControl/selectControl.ts
  packages/component/src/control/layerSwitch.ts
  packages/component/src/css/index.css
  packages/site/docs/api/other/city_building.en.md
  packages/site/docs/api/other/city_building.zh.md
  packages/utils/src/dom.ts
Labels: feature, pr(feature)

#2214 chore: publish
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: ignore-for-release, pr(chore)

#2215 fix: single component data texture
  examples/demos/raster/dem.ts
  examples/demos/raster/image.ts
  examples/demos/raster/tiff.ts
  packages/core/src/services/renderer/IRendererService.ts
  packages/core/src/services/renderer/ITexture2D.ts
  packages/core/src/services/renderer/gl.ts
  packages/layers/src/raster/models/raster.ts
  packages/renderer/src/device/DeviceTexture2D.ts
  packages/renderer/src/device/index.ts
  packages/renderer/src/regl/index.ts
Labels: bugfix, pr(fix)

#2218 fix: 修复图层显隐控件LayerSwitch单选模式下未默认展示单个图层问题
  dev-demos/component/control/layerSwitch.tsx
  packages/component/src/control/layerSwitch.ts
  packages/site/docs/api/component/layer_switch.zh.md
Labels: bugfix, pr(fix)

#2219 chore: multiband rgb raster parse
  __tests__/e2e/tests.ts
  examples/demos/raster/index.ts
  examples/demos/raster/multiband.ts
  packages/layers/src/raster/index.ts
  packages/layers/src/raster/models/rasterRgb.ts
  packages/site/docs/api/other/city_building.en.md
  packages/site/docs/api/other/city_building.zh.md
  packages/source/src/index.ts
  packages/source/src/parser/raster/rgb.ts
  packages/source/src/utils/bandOperation/operationSchema.ts
Labels: ignore-for-release, pr(chore)

#2220 chore: publish 2.20.11
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: ignore-for-release, pr(chore)

#2221 feat: 图层显隐控件配置更新时，新增处理单选模式图层显示逻辑
  packages/component/src/control/layerSwitch.ts
Labels: feature, pr(feature)

#2230 chore: publish
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: ignore-for-release, pr(chore)

#2231 fix: 修复图层隐藏时，LayerPopup 未跟随隐藏的问题
  dev-demos/component/popup/layerPopup.tsx
  packages/component/src/popup/layerPopup.ts
Labels: bugfix, pr(fix)
