Repository antvis/L7, pull requests merged in 2023-11, with the labels that each got.

#2004 fix: 图片图层在跨域请求的情况下不发送 cookies
  packages/source/src/parser/image.ts
Labels: bugfix, pr(fix)

#2008 docs: 删除 RasterLayer 旧文档样式描述
  packages/site/docs/common/layer/raster/rampcolors.en.md
  packages/site/docs/common/layer/raster/rampcolors.zh.md
Labels: documentation, pr(documentation)

#2005 chore: 更新 regl 版本 IE 兼容
  .fatherrc.ts
  package.json
  packages/component/.fatherrc.ts
  packages/component/src/assets/iconfont/iconfont.js
  packages/core/.fatherrc.ts
  packages/l7/.fatherrc.ts
  packages/l7/demo/cylinder.html
  packages/l7/demo/polygon.html
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/.fatherrc.ts
  packages/map/.fatherrc.ts
  packages/map/src/map.ts
  packages/maps/.fatherrc.ts
  packages/mini/.fatherrc.ts
  packages/renderer/.fatherrc.ts
  packages/renderer/package.json
  packages/scene/.fatherrc.ts
  packages/source/.fatherrc.ts
  packages/test-utils/.fatherrc.ts
  packages/test-utils/package.json
  packages/three/.fatherrc.ts
  packages/utils/.fatherrc.ts
Labels: ignore-for-release, pr(chore)

#2009 chore: publish 2.19.8
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: ignore-for-release, pr(chore)

#2010 fix: credentials: include 产生跨域问题
  packages/source/src/parser/image.ts
Labels: bugfix, pr(fix)

#2011 chore: publish 2.19.9
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: ignore-for-release, pr(chore)

#2014 chore: 优化线图层
  dev-demos/features/line/arc_deg.md
  dev-demos/features/line/demos/arc_deg.tsx
  dev-demos/features/line/demos/greatcircleline.tsx
  dev-demos/features/line/demos/line_stroke.tsx
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/core/BaseModel.ts
  packages/layers/src/core/CommonStyleAttribute.ts
  packages/layers/src/core/constant.ts
  packages/layers/src/core/interface.ts
  packages/layers/src/line/index.ts
  packages/layers/src/line/models/arc.ts
  packages/layers/src/line/models/great_circle.ts
  packages/layers/src/line/models/line.ts
  packages/layers/src/line/models/linearline.ts
  packages/layers/src/line/models/simpleLine.ts
  packages/layers/src/line/models/wall.ts
  packages/layers/src/line/shaders/dash/arc_dash_frag.glsl
  packages/layers/src/line/shaders/dash/arc_dash_vert.glsl
  packages/layers/src/line/shaders/dash/line_dash_frag.glsl
  packages/layers/src/line/shaders/line_arc_3d_frag.glsl
  packages/layers/src/line/shaders/line_arc_3d_vert.glsl
  packages/layers/src/line/shaders/line_arc_frag.glsl
  packages/layers/src/line/shaders/line_arc_great_circle_frag.glsl
  packages/layers/src/line/shaders/line_arc_great_circle_vert.glsl
  packages/layers/src/line/shaders/line_arc_vert.glsl
  packages/layers/src/line/shaders/line_frag.glsl
  packages/layers/src/line/shaders/line_vert.glsl
  packages/layers/src/line/shaders/linear/arc_linear_vert.glsl
  packages/layers/src/line/shaders/linear/line_linear_frag.glsl
  packages/layers/src/line/shaders/linearLine/line_linear_vert.glsl
  packages/layers/src/line/shaders/simple/simpleline_linear_frag.glsl
  packages/layers/src/line/shaders/simple/simpleline_vert.glsl
  packages/site/docs/api/line_layer/style.zh.md
Labels: ignore-for-release, pr(chore)

#2019 fix(packages/maps): fix l7 draw layer bug on tencent map
  packages/maps/src/tmap/map.ts
Labels: bugfix, pr(fix)

#2015 feat: 图片图层请求数据支持自定义参数
  packages/source/src/parser/image.ts
Labels: feature, pr(feature)

#2026 docs: 修改文档示例拼写错误 nodataValue => noDataValue
  packages/site/examples/mask/basic/demo/rastertile_raster.ts
  packages/site/examples/raster/single_raster/demo/light.js
  packages/site/examples/raster/single_raster/demo/light_default.js
Labels: documentation, pr(documentation)

#2032 docs: 更新开发者文档Windows环境配置 (#2028)
  .github/CONTRIBUTING.md
Labels: documentation, pr(documentation)

#2034 chore: publish
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: ignore-for-release, pr(chore)

#2037 docs: 更新开发者英文文档Windows环境配置（#2028）
  .github/CONTRIBUTING_ENGLISH.md
Labels: documentation, pr(documentation)

#2039 Fix/tencent map
  packages/maps/src/tmap/map.ts
Labels: AntV OSCP, OSCP 已认领

#2036 chore: add changelog
  CHANGELOG.md
  package.json
Labels: ignore-for-release, pr(chore)

#2043 补充百度地图文档
  packages/site/docs/api/map/bmap.zh.md
  packages/site/docs/api/map/gaode.zh.md
  packages/site/docs/api/map/mapbox.zh.md
  packages/site/docs/api/map/tianditu.zh.md
  packages/site/docs/api/map/tmap.zh.md
Labels: AntV OSCP

#2016 chore: 升级flow line arrow 样式
  dev-demos/features/line/demos/flowline.tsx
  dev-demos/features/line/demos/lineArrow.tsx
  dev-demos/features/point/demos/radar.tsx
  dev-demos/tile/Vector/demos/vectormask.tsx
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/layer/IStyleAttributeService.ts
  packages/core/src/services/layer/StyleAttributeService.ts
  packages/core/src/shaders/projection.glsl
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/core/interface.ts
  packages/layers/src/core/line_trangluation.ts
  packages/layers/src/core/shape/arrow.ts
  packages/layers/src/core/triangulation.ts
  packages/layers/src/line/index.ts
  packages/layers/src/line/models/arc.ts
  packages/layers/src/line/models/arc_3d.ts
  packages/layers/src/line/models/earthArc_3d.ts
  packages/layers/src/line/models/flow.ts
  packages/layers/src/line/models/index.ts
  packages/layers/src/line/models/line.ts
  packages/layers/src/line/shaders/dash/arc_dash_vert.glsl
  packages/layers/src/line/shaders/flow/flow_line_vert.glsl
  packages/layers/src/line/shaders/linear/arc_linear_vert.glsl
  packages/layers/src/plugins/DataMappingPlugin.ts
  tsconfig.json
Labels: ignore-for-release, pr(chore)

#1961 feat: implement renderer service with g-device-api
  .eslintrc.js
  .gitignore
  .umirc.ts
  dev-demos/features/point/demos/circle-webgpu.tsx
  dev-demos/features/point/demos/circlemeter.tsx
  dev-demos/features/point/demos/normal-device.tsx
  dev-demos/features/point/demos/normal.tsx
  dev-demos/features/point/pointCircleWebGPU.md
  dev-demos/features/point/pointNormalDevice.md
  packages/core/src/index.ts
  packages/core/src/services/config/IConfigService.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/layer/LayerService.ts
  packages/core/src/services/renderer/IAttribute.ts
  packages/core/src/services/renderer/IBuffer.ts
  packages/core/src/services/renderer/IModel.ts
  packages/core/src/services/renderer/IRendererService.ts
  packages/core/src/services/shader/ShaderModuleService.ts
  packages/core/src/shaders/picking.frag.glsl
  packages/core/src/shaders/picking.vert.glsl
  packages/core/src/shaders/projection.glsl
  packages/core/src/utils/shader-module.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/core/BaseModel.ts
  packages/layers/src/core/CommonStyleAttribute.ts
  packages/layers/src/plugins/PixelPickingPlugin.ts
  packages/layers/src/plugins/RegisterStyleAttributePlugin.ts
  packages/layers/src/plugins/ShaderUniformPlugin.ts
  packages/layers/src/point/index.ts
  packages/layers/src/point/models/fill.ts
  packages/layers/src/point/models/normal.ts
  packages/layers/src/point/shaders/fill_frag.glsl
  packages/layers/src/point/shaders/fill_vert.glsl
  packages/layers/src/point/shaders/normal_frag.glsl
  packages/layers/src/point/shaders/normal_vert.glsl
  packages/renderer/package.json
  packages/renderer/src/device/DeviceAttribute.ts
  packages/renderer/src/device/DeviceBuffer.ts
  packages/renderer/src/device/DeviceElements.ts
  packages/renderer/src/device/DeviceFramebuffer.ts
  packages/renderer/src/device/DeviceModel.ts
  packages/renderer/src/device/DeviceTexture2D.ts
  packages/renderer/src/device/constants.ts
  packages/renderer/src/device/index.ts
  packages/renderer/src/device/utils/pipeline.ts
  packages/renderer/src/device/utils/typedarray.ts
  packages/renderer/src/device/utils/webgl.ts
  packages/renderer/src/index.ts
  packages/renderer/src/regl/ReglModel.ts
  packages/renderer/src/regl/index.ts
  packages/scene/src/index.ts
  packages/test-utils/package.json
  public/antv.png
  public/glsl_wgsl_compiler_bg.wasm
Labels: feature, pr(feature)

#2057 fix: 修复 LayerSwitch 样式问题，完善文档
  dev-demos/component/control/layerSwitch.md
  dev-demos/component/control/layerSwitch1.tsx
  packages/component/src/css/index.css
  packages/component/src/css/select.less
  packages/component/src/css/variables.less
  packages/component/src/index.ts
  packages/site/docs/api/component/layer_switch.zh.md
  packages/site/examples/component/control/demo/layerswitch1.ts
  packages/site/examples/component/control/demo/meta.json
Labels: bugfix, pr(fix)

#2062 chore: publish
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: ignore-for-release, pr(chore)

#2063 fix: 修复 LayerPopup unclick 不消失问题
  packages/site/docs/api/component/layer_switch.zh.md
Labels: bugfix, pr(fix)

#2064 chore: 更新版本,升级sdf 依赖
  jest.config.ts
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/core/src/services/asset/tiny_sdf.ts
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: ignore-for-release, pr(chore)

#2066 fix: 修复 LayerSwitch 误识别 L7Plot 问题
  packages/component/src/control/layerSwitch.ts
Labels: bugfix, pr(fix)

#2068 fix: 修复windows环境下shader字符串中的换行符导致shader替换结果错误的bug
  .eslintrc.js
  packages/core/src/services/shader/ShaderModuleService.ts
Labels: bugfix, pr(fix)

#2072 chore: update dumi-theme-antv
  packages/site/.dumirc.ts
  packages/site/package.json
Labels: ignore-for-release, pr(chore)

#2074 docs: image position change
  packages/site/.dumirc.ts
  packages/site/package.json
Labels: documentation, pr(documentation)

#2075 fix: 修复 LayerPopup trigger & items 导致的 Bug
  dev-demos/component/popup/layerPopup.tsx
  packages/component/src/popup/layerPopup.ts
Labels: bugfix, pr(fix)

#2078 chore: publish v2.20.2
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: ignore-for-release, pr(chore)

#2059 L7实现地图卷帘demo
  dev-demos/tile/Mask/demos/raster_roller.tsx
  dev-demos/tile/Mask/raster_roller.md
Labels: AntV OSCP

#2055 feat add demo of line-population
  dev-demos/features/line/demos/linePopulation.tsx
  dev-demos/features/line/linePopulation.md
Labels: AntV OSCP

#2081 docs: 文档更新
  packages/core/src/shaders/projection.glsl
  packages/layers/src/point/shaders/extrude/extrude_vert.glsl
  packages/site/docs/api/map/bmap.en.md
  packages/site/docs/api/map/gaode.en.md
  packages/site/docs/api/map/map.en.md
  packages/site/docs/api/map/mapbox.en.md
  packages/site/docs/api/map/maplibre.en.md
  packages/site/docs/api/map/tencent.en.md
  packages/site/docs/common/map.en.md
  packages/site/examples/polygon/3d/demo/polygon_stylemap.js
Labels: documentation, pr(documentation)

#2051 fix(line_wall_shader): possibly fixed the line wall unit problem
  packages/core/src/shaders/projection.glsl
  packages/layers/src/line/shaders/wall/wall_vert.glsl
Labels: bugfix, pr(fix), AntV OSCP

#2087 chore: publish
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: ignore-for-release, pr(chore)

#2091 fix: 修复 MapTheme 换行样式问题
  packages/component/src/css/index.css
  packages/component/src/css/select.less
  packages/component/src/css/variables.less
Labels: bugfix, pr(fix)

#2092 chore: pointlayer extruder 支持 device render
  dev-demos/features/point/demos/circlemeter.tsx
  dev-demos/features/point/demos/column.tsx
  dev-demos/features/point/pointColumn.md
  packages/layers/src/core/BaseModel.ts
  packages/layers/src/core/CommonStyleAttribute.ts
  packages/layers/src/core/constant.ts
  packages/layers/src/core/utils.ts
  packages/layers/src/point/models/extrude.ts
  packages/layers/src/point/models/image.ts
  packages/layers/src/point/shaders/extrude/extrude_frag.glsl
  packages/layers/src/point/shaders/extrude/extrude_vert.glsl
Labels: ignore-for-release, pr(chore)

#2101 fix: setdata 更新 & Arcline fix #2100
  dev-demos/bugs/polygon/demos/highlight.tsx
  dev-demos/bugs/polygon/highlight.md
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/line/models/great_circle.ts
Labels: bugfix, pr(fix)

#2104 fix: quantile scale mutlipoygon 不准确 fix: #2086
  dev-demos/bugs/polygon/demos/quantile.tsx
  dev-demos/bugs/polygon/quantile.md
  packages/layers/src/plugins/FeatureScalePlugin.ts
Labels: bugfix, pr(fix)

#2105 feat: scene 提供 animate 控制方法,用于调试
  dev-demos/features/point/demos/circlemeter.tsx
  package.json
  packages/scene/src/index.ts
  packages/site/docs/api/scene.en.md
  packages/site/docs/api/scene.zh.md
Labels: feature, pr(feature)
