Repository antvis/L7, pull requests merged in 2023-10, with the labels that each got.

#1904 fix: 修复 frozen 的 geojson 数据
  packages/source/src/parser/geojson.ts
  packages/source/src/parser/json.ts
  packages/source/src/utils/util.ts
Labels: bugfix, pr(fix)

#1905 chore: publish
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: ignore-for-release, pr(chore)

#1900 fix: scale 为 identity 时的问题 & extrusion demo
  dev-demos/features/point/demos/circlemeter.tsx
  dev-demos/features/polygon/demos/indoor.tsx
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/plugins/FeatureScalePlugin.ts
  packages/layers/src/polygon/index.ts
  packages/layers/src/polygon/shaders/extrusion/polygon_extrusion_vert.glsl
  packages/site/.dumi/pages/Examples/index.module.less
  packages/site/docs/api/point_layer/style.zh.md
  packages/site/docs/api/polygon_layer/shape.zh.md
  packages/site/docs/api/polygon_layer/style.zh.md
  packages/site/examples/gallery/animate/demo/meta.json
  packages/site/examples/point/dot/demo/normal.js
  packages/site/examples/point/text/demo/point_text.js
  packages/site/examples/polygon/extrusion/demo/meta.json
  packages/site/examples/polygon/extrusion/demo/polygon.js
  packages/site/examples/polygon/extrusion/index.en.md
  packages/site/examples/polygon/extrusion/index.zh.md
Labels: bugfix, pr(fix)

#1907 docs: 更新demo
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/examples/gallery/basic/demo/normal.js
  packages/site/examples/polygon/extrusion/demo/meta.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: documentation, pr(documentation)

#1910 chore: umd 打包
  packages/l7/.fatherrc.ts
  packages/l7/demo/text2.html
  packages/maps/src/index.ts
Labels: ignore-for-release, pr(chore)

#1912 docs: 将 L7Editor 入口由内嵌转为超链接跳转
  packages/site/.dumi/pages/custom/l7editor/index.md
  packages/site/.dumi/pages/custom/l7editor/index.tsx
  packages/site/.dumirc.ts
Labels: documentation, pr(documentation)

#1916 chore: add issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/oscp.yml
Labels: ignore-for-release, pr(chore)

#1917 docs: 1. 文档中 LI => L7VP 2. 轮播新增 L7Editor
  README.en-US.md
  README.md
  packages/l7/README.en-US.md
  packages/l7/README.md
  packages/site/.dumirc.ts
Labels: documentation, pr(documentation)

#1913 feat: 新增 BMap
  .umirc.ts
  dev-demos/bugs/scene/bmap.md
  dev-demos/bugs/scene/demos/bmap.tsx
  package.json
  packages/maps/src/bmap/index.ts
  packages/maps/src/bmap/map.ts
  packages/maps/src/index.ts
  packages/maps/typings/index.d.ts
Labels: feature, pr(feature)

#1927 docs: 英文文档标题
  packages/site/docs/api/component/map_theme.en.md
  packages/site/docs/tutorial/polygon/extrude.en.md
  packages/site/docs/tutorial/polygon/fill.en.md
  packages/site/docs/tutorial/polygon/water.zh.md
Labels: documentation, pr(documentation)

#1935 docs: 新增demo
  packages/site/examples/gallery/story/demo/gaza.js
  packages/site/examples/gallery/story/demo/meta.json
  packages/site/examples/gallery/story/demo/yidaiyilu.js
  packages/site/examples/gallery/story/index.en.md
  packages/site/examples/gallery/story/index.zh.md
  packages/site/examples/tile/vector/demo/worldmap.ts
Labels: documentation, pr(documentation)

#1937 fix(layer): fix simple line 渐变色
  dev-demos/features/line/demos/line.tsx
  dev-demos/features/line/demos/simplelines.tsx
  packages/layers/src/line/shaders/simple/simpleline_linear_frag.glsl
  packages/layers/src/line/shaders/simple/simpleline_vert.glsl
Labels: bugfix, pr(fix)

#1940 fix: updtate JS API token
  packages/maps/src/amap2/map.ts
  packages/site/.dumirc.ts
Labels: bugfix, pr(fix)

#1941 chore: publish
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/maps/src/amap2/map.ts
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/.dumirc.ts
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: ignore-for-release, pr(chore)

#1952 Publish 2.19.6
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/maps/src/amap2/map.ts
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/docs/api/map/amap.zh.md
  packages/site/docs/tutorial/l7.zh.md
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: bugfix

#1955 Update oscp.yml
  .github/ISSUE_TEMPLATE/oscp.yml
Labels: ci

#1962 fix: 修改文档
  packages/site/docs/api/map/amap.zh.md
  packages/site/examples/gallery/story/demo/meta.json
  packages/site/examples/gallery/story/demo/yidaiyilu2.js
  packages/site/examples/tutorial/map/demo/bmapInstance.js
  packages/site/examples/tutorial/map/demo/meta.json
Labels: bugfix, pr(fix)

#1976 docs: 更新地图配置
  packages/site/examples/gallery/story/demo/yidaiyilu2.js
Labels: documentation, pr(documentation)

#1966 feat(packages/maps): support tencent map
  package.json
  packages/maps/src/index.ts
  packages/maps/src/tmap/index.ts
  packages/maps/src/tmap/logo.css
  packages/maps/src/tmap/map.ts
  packages/maps/src/tmap/maploader.ts
  packages/maps/typings/index.d.ts
  packages/site/examples/tutorial/map/demo/meta.json
  packages/site/examples/tutorial/map/demo/tencentmap.js
  packages/site/examples/tutorial/map/demo/tmapInstance.js
Labels: feature, pr(feature)

#1978 chore: 地图模块目录
  packages/site/.dumirc.ts
  packages/site/examples/map/map/API.en.md
  packages/site/examples/map/map/API.zh.md
  packages/site/examples/map/map/demo/amapInstance.js
  packages/site/examples/map/map/demo/baidumap.js
  packages/site/examples/map/map/demo/bmapInstance.js
  packages/site/examples/map/map/demo/gaodemap.js
  packages/site/examples/map/map/demo/meta.json
  packages/site/examples/map/map/demo/tencentmap.js
  packages/site/examples/map/map/demo/tmapInstance.js
  packages/site/examples/map/map/index.en.md
  packages/site/examples/map/map/index.zh.md
Labels: ignore-for-release, pr(chore)

#1981 chore: publish 2.19.7
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: ignore-for-release, pr(chore)

#1983 Update oscp.yml
  .github/ISSUE_TEMPLATE/oscp.yml
Labels: chore

#1990 feat: layerSwitch 新增支持传入 layerSwitchItem 属性
  packages/component/src/control/layerSwitch.ts
Labels: feature, pr(feature)

#1994 fix: 修改判断
  packages/component/src/control/layerSwitch.ts
Labels: bugfix, pr(fix)

#1997 fix: 修复 LayerPopup items 为空时，followCursor 问题
  packages/component/src/popup/layerPopup.ts
Labels: bugfix, pr(fix)

#1999 chore: 移除无效依赖
  babel.config.js
  dev-demos/features/tile/raster/satellite.tsx
  dev-demos/features/tile/raster/signGenerator.ts
  dev-demos/features/tile/rasterImage.md
  package.json
  vercel.json
Labels: ignore-for-release, pr(chore)
