Repository antvis/L7, pull requests merged in 2023-09, with the labels that each got.

#1816 docs: geojsontvt 文档样式
  dev-demos/features/polygon/demos/extrude1.tsx
  packages/site/.dumirc.ts
  packages/site/docs/api/tile/geojsonvt_tile_layer.zh.md
  packages/site/docs/common/layer/layer_style.md
  packages/site/docs/tutorial/polygon/extrude.zh.md
  packages/site/examples/line/path/demo/arrow.js
  packages/site/examples/line/path/demo/meta.json
  packages/site/examples/polygon/3d/demo/polygon_stylemap.js
  packages/site/examples/polygon/3d/demo/polygonstylemap.js
Labels: documentation

#1832 chore: add issue action
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE_EN.md
  .github/workflows/chatgpt.yml
  .github/workflows/issue.yml
Labels: ignore-for-release

#1834 fix: flow line mapbox bug #1777 #1822
  dev-demos/features/line/demos/flowline.tsx
  packages/layers/src/line/shaders/flow/flow_line_vert.glsl
  packages/utils/src/workers/index.ts
Labels: bugfix

#1837 fix: 添加welcome action
  .github/workflows/issue-close-require.yml
  .github/workflows/issue.yml
  .github/workflows/issue_action.yml
  .github/workflows/issue_welcome.yml
  .github/workflows/main.yml
Labels: bugfix

#1849 fix: 修复 Control 与 Antd 5.x Modal z-index 冲突问题
  packages/component/src/css/control.less
  packages/component/src/css/index.css
  packages/component/src/css/l7.less
  packages/component/src/css/variables.less
Labels: bugfix

#1853 点图层旋转 Rotate 支持 常量和数据映射 #1841
  dev-demos/bugs/point/demos/circle.tsx
  dev-demos/bugs/point/demos/image.tsx
  dev-demos/features/point/demos/iconfont.tsx
  dev-demos/features/point/demos/text.tsx
  dev-demos/features/point/pointFillImage.md
  packages/core/src/services/shader/ShaderModuleService.ts
  packages/core/src/shaders/common_attr.vert.glsl
  packages/core/src/shaders/rotation_2d.glsl
  packages/core/src/shaders/styleMapping.glsl
  packages/core/src/shaders/styleMappingCalOpacity.glsl
  packages/core/src/shaders/styleMappingCalStrokeOpacity.glsl
  packages/core/src/shaders/styleMappingCalStrokeWidth.glsl
  packages/core/src/shaders/styleMappingCalThetaOffset.glsl
  packages/layers/src/core/BaseModel.ts
  packages/layers/src/core/CommonStyleAttribute.ts
  packages/layers/src/plugins/FeatureScalePlugin.ts
  packages/layers/src/point/index.ts
  packages/layers/src/point/models/fillmage.ts
  packages/layers/src/point/models/text.ts
  packages/layers/src/point/shaders/fill_vert.glsl
  packages/layers/src/point/shaders/image/fillImage_frag.glsl
  packages/layers/src/point/shaders/image/fillImage_vert.glsl
  packages/layers/src/point/shaders/text_vert.glsl
Labels: bug, enhancement, improvement

#1862 chore: add new issue action
  .github/CONTRIBUTING_ENGLISH.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE_EN.md
  .github/workflows/issue_assigness.yml
  .github/workflows/issue_labeled.yml
  .github/workflows/issues-similarity-analysis.yml
  .github/workflows/monthly_issue_metrics.yml
  .github/workflows/pr-auto-set-label.yml
  .github/workflows/pr-closed.yml
  .github/workflows/pr-labeled.yml
  packages/site/docs/tutorial/develop.en.md
  packages/site/docs/tutorial/develop.zh.md
Labels: ignore-for-release

#1859 fix: 点图层数据映射
  dev-demos/bugs/point/demos/circle.tsx
  dev-demos/bugs/point/demos/image.tsx
  dev-demos/features/point/demos/iconfont.tsx
  dev-demos/features/point/demos/icons.tsx
  dev-demos/features/point/demos/simple.tsx
  dev-demos/features/point/demos/text.tsx
  dev-demos/features/point/pointFillImage.md
  dev-demos/features/point/pointImage.md
  packages/layers/src/core/BaseModel.ts
  packages/layers/src/core/CommonStyleAttribute.ts
  packages/layers/src/core/interface.ts
  packages/layers/src/point/index.ts
  packages/layers/src/point/models/billboard_point.ts
  packages/layers/src/point/models/fillmage.ts
  packages/layers/src/point/models/image.ts
  packages/layers/src/point/models/index.ts
  packages/layers/src/point/models/normal.ts
  packages/layers/src/point/shaders/billboard_point_frag.glsl
  packages/layers/src/point/shaders/billboard_point_vert.glsl
  packages/layers/src/point/shaders/fill_vert.glsl
  packages/layers/src/point/shaders/image/fillImage_vert.glsl
  packages/layers/src/point/shaders/image_frag.glsl
  packages/layers/src/point/shaders/image_vert.glsl
  packages/layers/src/point/shaders/normal_vert.glsl
  packages/layers/src/point/shaders/text_vert.glsl
  packages/site/docs/api/point_layer/style.zh.md
  packages/site/docs/tutorial/point/symbol.zh.md
  packages/site/examples/point/image/demo/image.js
  packages/site/examples/point/image/demo/monsoon.js
Labels: bugfix

#1870 docs: 更新文档
  packages/site/.dumirc.ts
  packages/site/docs/tutorial/develop.zh.md
  packages/site/docs/tutorial/quick_issue.en.md
  packages/site/docs/tutorial/quick_issue.zh.md
Labels: documentation, pr(documentation)

#1895 docs: 升级官网，支持快速编辑、github 相关信息展示
  .github/workflows/issue_labeled.yml
  .github/workflows/issue_welcome.yml
  packages/site/.dumi/pages/404.tsx
  packages/site/.dumi/pages/Example/index.module.less
  packages/site/.dumi/pages/Example/index.tsx
  packages/site/.dumi/pages/Example/utils.ts
  packages/site/.dumi/pages/Examples/components/GalleryPageContent/DemoCard/index.tsx
  packages/site/.dumi/pages/Examples/components/GalleryPageContent/index.tsx
  packages/site/.dumi/pages/Examples/index.module.less
  packages/site/.dumi/pages/Examples/index.tsx
  packages/site/.dumi/pages/Examples/types.ts
  packages/site/.dumi/theme/slots/CodePreview/CodeHeader.module.less
  packages/site/.dumi/theme/slots/CodePreview/CodeHeader.tsx
  packages/site/.dumi/theme/slots/CodePreview/index.module.less
  packages/site/.dumi/theme/slots/CodePreview/index.tsx
  packages/site/.dumi/theme/slots/CodeRunner/index.module.less
  packages/site/.dumi/theme/slots/CodeRunner/index.tsx
  packages/site/.dumi/theme/slots/CodeRunner/utils.ts
  packages/site/.dumi/theme/slots/GithubButtonBar.tsx
  packages/site/.dumi/theme/slots/ManualContent/index.module.less
  packages/site/.dumi/theme/slots/ManualContent/index.tsx
  packages/site/.dumi/theme/slots/ManualContent/utils.ts
  packages/site/.dumirc.ts
  packages/site/docs/api/mask_layer/masklayer.en.md
  packages/site/docs/api/mask_layer/masklayer.zh.md
  packages/site/docs/api/mask_layer/options.en.md
  packages/site/docs/api/mask_layer/options.zh.md
  packages/site/docs/api/mask_layer/source.en.md
  packages/site/docs/api/mask_layer/source.zh.md
  packages/site/docs/api/raster_layer/raster_multi_band.zh.md
  packages/site/docs/api/raster_layer/raster_rgb.zh.md
  packages/site/docs/api/raster_layer/raster_single_band.zh.md
  packages/site/docs/api/source/mvt.zh.md
  packages/site/docs/api/source/raster.zh.md
  packages/site/docs/api/source/raster_rgb.en.md
  packages/site/docs/api/source/raster_rgb.zh.md
  packages/site/docs/api/source/raster_tile.zh.md
  packages/site/docs/api/source/source.zh.md
  packages/site/docs/api/tile/raster_tile_layer.zh.md
  packages/site/docs/common/layer/raster/rampcolors.md
  packages/site/docs/common/layer/raster/style.md
  packages/site/docs/common/layer/raster/style_single.md
  packages/site/docs/common/source/raster/raster_band_calc.md
  packages/site/docs/common/source/raster/raster_multi.md
  packages/site/docs/common/source/raster/raster_rgb.md
  packages/site/docs/common/source/raster/raster_single.md
  packages/site/docs/common/source/tile/method.md
  packages/site/examples/gallery/animate/demo/meta.json
  packages/site/package.json
Labels: documentation, pr(documentation)

#1898 fix: 修复 PopperControl unclick 时，弹出框不关闭的问题
  packages/component/src/utils/popper.ts
  packages/utils/src/dom.ts
Labels: bugfix, pr(fix)

#1899 docs: example 新增搜索功能
  packages/site/.dumi/pages/Examples/components/GalleryPageContent/index.tsx
  packages/site/.dumi/pages/Examples/components/SelectExampleBar/index.module.less
  packages/site/.dumi/pages/Examples/components/SelectExampleBar/index.tsx
  packages/site/.dumi/pages/Examples/index.tsx
  packages/site/.dumirc.ts
Labels: documentation, pr(documentation)
