Repository antvis/L7, pull requests merged in 2023-04, with the labels that each got.

#1665 fix: 修复 Map 底图下导出地图不生效问题
  packages/component/src/control/exportImage.ts
Labels: PR: reviewed-approved, bugfix

#1670 docs: 修正官网文案
  packages/site/docs/api/scene.zh.md
Labels: PR: reviewed-approved, documentation

#1672 Publish 2.15.1
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed

#1674 Fix fontservice 对字体渲染
  dev-demos/bugs/point/demos/pointstroke.tsx
  packages/core/src/services/asset/FontService.ts
  packages/core/src/services/asset/IFontService.ts
  packages/layers/src/point/models/text.ts
Labels: PR: unreviewed

#1675 Publish 2.15.2
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed

#1677 docs: 文档新增有关 L7Editor 链接
  README.en-US.md
  README.md
  packages/l7/README.en-US.md
  packages/l7/README.md
  packages/site/.dumirc.ts
Labels: PR: reviewed-approved, documentation

#1684 chore: 依赖升级& 网站关闭msfu
  package.json
  packages/site/.dumirc.ts
Labels: PR: unreviewed, ignore-for-release

#1687 fix: 修复removeClass 多 class 字符串报错的问题
  packages/utils/src/dom.ts
Labels: PR: reviewed-approved, bugfix

#1690 Fix marker 移动端事件
  dev-demos/bugs/marker/event.md
  dev-demos/bugs/marker/marker1.tsx
  packages/component/src/marker.ts
Labels: PR: unreviewed
