Repository antvis/L7, pull requests merged in 2023-01, with the labels that each got.

#1562 fix: 修复 gl jest-test 测试
  packages/layers/src/point/__tests__/layer_init.spec.ts
Labels: PR: reviewed-approved, bugfix

#1561 fix: 修复鸿蒙系统 webgl 扩展不支持错误
  packages/layers/src/line/models/line.ts
Labels: PR: reviewed-approved, bugfix

#1565 chore: publish update version 2.13.0 -> 2.13.1
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: reviewed-approved, ignore-for-release

#1569 docs: 修复文档部分问题
  packages/site/docs/api/line_layer/source.zh.md
  packages/site/docs/api/polygon_layer/source.zh.md
  packages/site/examples/tutorial/layer/demo/layer_boxselect.js
  packages/site/examples/tutorial/layer/demo/meta.json
  packages/site/package.json
Labels: PR: reviewed-approved, documentation

#1563 feat: try to replace regl with g-webgl
  packages/core/src/services/scene/SceneService.ts
  packages/layers/src/plugins/LayerAnimateStylePlugin.ts
  packages/layers/src/plugins/LightingPlugin.ts
  packages/layers/src/plugins/ShaderUniformPlugin.ts
  packages/layers/src/plugins/UpdateModelPlugin.ts
  packages/renderer/package.json
  packages/renderer/src/regl/index.ts
Labels: PR: unreviewed, feature

#1574 feat: scale update 不生效
  dev-demos/bugs/polygon/demos/polygon.tsx
  dev-demos/bugs/polygon/demos/scale.tsx
  dev-demos/draw/demo/drawpolygon.tsx
  dev-demos/draw/line_area.md
  dev-demos/draw/polygon.md
  dev-demos/gallery/scale/index.md
  packages/core/src/services/layer/IStyleAttributeService.ts
  packages/core/src/services/layer/StyleAttributeService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/site/docs/api/base_layer/base.zh.md
  packages/site/docs/common/layer/layer_encode.md
  packages/site/docs/common/layer/layer_texture.md
  packages/site/docs/common/layer/layer_update.md
  packages/site/docs/tutorial/scale.en.md
  packages/site/docs/tutorial/scale.zh.md
Labels: PR: unreviewed, feature

#1576 Fix scale update diff
  packages/layers/src/core/BaseLayer.ts
Labels: PR: unreviewed

#1577 Publish 2.13.2
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: PR: unreviewed
