Repository antvis/L7, pull requests merged in 2023-07, with the labels that each got.

#1750 fix: 线图层 opacity
  packages/layers/src/line/models/arc.ts
  packages/layers/src/line/models/line.ts
  packages/layers/src/line/models/linearline.ts
  packages/layers/src/line/models/simpleLine.ts
Labels: bugfix

#1755 fix: 修复 export 冲突问题
  packages/component/src/control/baseControl/index.ts
  packages/component/src/index.ts
Labels: bugfix

#1760 fix: 虚线图层style 更新
  dev-demos/features/line/demos/linedash.tsx
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/line/models/line.ts
  packages/layers/src/line/shaders/dash/line_dash_vert.glsl
  packages/layers/src/line/shaders/line_frag.glsl
  packages/layers/src/line/shaders/line_vert.glsl
  packages/layers/src/line/shaders/linear/line_linear_frag.glsl
  packages/layers/src/plugins/LayerModelPlugin.ts
  packages/layers/src/plugins/LayerStylePlugin.ts
Labels: bugfix

#1764 chore: update version 2.17.5
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: ignore-for-release

#1766 feat: 文字支持textoffset,anchor
  dev-demos/features/point/demos/text2.tsx
  dev-demos/features/point/pointText2.md
  packages/core/src/services/layer/ILayerService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/core/BaseModel.ts
  packages/layers/src/line/index.ts
  packages/layers/src/line/models/arc_3d.ts
  packages/layers/src/point/index.ts
  packages/layers/src/point/models/text.ts
  packages/layers/src/polygon/index.ts
Labels: feature

#1768 fix: threejs build layer
  dev-demos/bugs/three/demo/marker.tsx
  dev-demos/bugs/three/marker.md
  packages/three/src/core/baseLayer.ts
  packages/three/src/layer/Symbol3DLayer.ts
Labels: bugfix

#1770 chore: update version 2.17.7
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/l7/src/version.ts
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/mini/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: ignore-for-release
