Repository antvis/L7, pull requests merged in 2024-04, with the labels that each got.

#2370 fix: removeLayer 无法正确的移除多个 layer
  .github/PULL_REQUEST_TEMPLATE.md
  examples/constants.ts
  examples/demos/bugfix/index.ts
  examples/demos/bugfix/remove-muti-layer.ts
  examples/demos/index.ts
  examples/demos/point/fill.ts
  examples/demos/template.ts
  examples/template.ts
  examples/types.ts
  examples/view.tsx
  jest.config.ts
  packages/component/__tests__/swipe.spec.ts
  packages/core/src/services/layer/LayerService.ts
  packages/layers/__tests__/tile/raster-tile.spec.ts
  packages/layers/__tests__/tile/vector-tile.spec.ts
Labels: bugfix, pr(fix)

#2371 chore: publish
  lerna.json
  package.json
  packages/component/package.json
  packages/component/src/css/index.css
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
  site/package.json
Labels: ignore-for-release, pr(chore)

#2374 chore: publish
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
  site/package.json
Labels: ignore-for-release, pr(chore)

#2386 chore: Upgrade project engineering - Part 3
  .github/CONTRIBUTING.md
  .github/CONTRIBUTING_ENGLISH.md
  .github/workflows/create-bumb-version-pr.yml
  .github/workflows/deploy-site.yml
  .github/workflows/issue_welcome.yml
  .github/workflows/release-notify.yml
  .github/workflows/release.yml
  .github/workflows/update-snapshots.yml
  CHANGELOG.md
  CODE_GUIDELINES.md
  CONTRIBUTING.en-US.md
  CONTRIBUTING.md
  README.en-US.md
  README.md
  __tests__/integration/gallery.spec.ts
  __tests__/integration/line.spec.ts
  __tests__/integration/mask.spec.ts
  __tests__/integration/point.spec.ts
  __tests__/integration/polygon.spec.ts
  __tests__/integration/snapshot.spec.ts
  __tests__/integration/test-cases/index.ts
  __tests__/integration/utils/generator.ts
  lerna.json
  package.json
  packages/component/CHANGELOG.md
  packages/component/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/l7/CHANGELOG.md
  packages/l7/package.json
  packages/layers/CHANGELOG.md
  packages/layers/package.json
  packages/map/CHANGELOG.md
  packages/map/package.json
  packages/maps/CHANGELOG.md
  packages/maps/package.json
  packages/renderer/CHANGELOG.md
  packages/renderer/package.json
  packages/scene/CHANGELOG.md
  packages/scene/package.json
  packages/source/CHANGELOG.md
  packages/source/package.json
  packages/test-utils/CHANGELOG.md
  packages/three/CHANGELOG.md
  packages/three/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
  site/package.json
Labels: ignore-for-release, pr(chore)

#2393 fix: 修复 MapLibre 下使用 CanvasLayer 鼠标事件异常问题
  packages/maps/src/maplibre/map.ts
Labels: bugfix, pr(fix)

#2399 fix: 修复rastertile类型对应请求无法自定义请求头参数
  .changeset/late-windows-hunt.md
  packages/source/src/utils/tile/getRasterTile.ts
Labels: bugfix, pr(fix)

#2403 fix: 修复 arraybuffer 类型数据自定义请求头参数透传逻辑
  .changeset/tame-trees-fold.md
  packages/source/src/parser/raster-tile.ts
  packages/source/src/utils/tile/getRasterTile.ts
Labels: bugfix, pr(fix)

#2410 docs: update tree structure
  CONTRIBUTING.en-US.md
  CONTRIBUTING.md
  README.en-US.md
Labels: documentation, pr(documentation)

#2412 fix: 修复 arraybuffer 类型数据自定义请求头参数透传逻辑
  .changeset/pre.json
  .changeset/tame-trees-fold.md
  packages/source/src/parser/raster-tile.ts
  packages/source/src/utils/tile/getRasterTile.ts
Labels: bugfix, pr(fix)

#2415 docs: 修改掩模文案
  legacy/dev-demos/src/tile/Mask/demos/raster_roller.tsx
  legacy/dev-demos/src/tile/Mask/raster_roller.md
  legacy/dev-demos/src/tile/Mask/vector_raster.md
  legacy/dev-demos/src/tile/Vector/vectormask.md
  packages/component/src/control/swipe.ts
  packages/core/src/services/layer/LayerService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/utils/stencil.ts
  packages/renderer/src/regl/ReglModel.ts
  site/docs/api/common/layer/mask_method.zh.md
  site/docs/api/common/layer/mask_options.zh.md
  site/examples/mask/basic/demo/meta.json
  site/examples/mask/basic/index.zh.md
  site/examples/tile/basemap/demo/meta.json
Labels: documentation, pr(documentation)
