Repository antvis/L7, pull requests merged in 2024-03, with the labels that each got.

#2330 fix: getViewportSize dpr
  packages/core/src/services/interaction/PickingService.ts
Labels: bugfix, pr(fix)

#2331 chore: publish 2.20.20
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: ignore-for-release, pr(chore)

#2335 chore: remove debug log
  packages/component/src/marker.ts
Labels: ignore-for-release, pr(chore)

#2338 fix: legend event
  examples/demos/bugfix/event_legend.ts
  examples/demos/bugfix/index.ts
  examples/utils/sleep.ts
  packages/core/src/services/layer/IStyleAttributeService.ts
  packages/core/src/services/layer/StyleAttributeService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/site/docs/api/common/layer/layer_event.en.md
  packages/site/docs/api/common/layer/layer_event.zh.md
Labels: bugfix, pr(fix)

#2344 feat: CanvasLayer 改造
  dev-demos/features/canvasLayer/canvas2d.md
  dev-demos/features/canvasLayer/canvas2d.tsx
  dev-demos/features/canvasLayer/custom.md
  dev-demos/features/canvasLayer/custom2.md
  examples/demos/canvas/event.ts
  examples/demos/canvas/index.ts
  examples/demos/canvas/layer.ts
  examples/demos/index.ts
  packages/core/src/services/map/IMapService.ts
  packages/layers/src/canvas/index.ts
  packages/layers/src/canvas/models/canvas.ts
  packages/layers/src/canvas/models/constants.ts
  packages/layers/src/canvas/models/index.ts
  packages/layers/src/core/interface.ts
  packages/layers/src/index.ts
  packages/map/src/map.ts
  packages/maps/src/amap/logo.css
  packages/maps/src/amap2/logo.css
  packages/maps/src/bmap/map.ts
  packages/maps/src/earth/map.ts
  packages/maps/src/gmap/map.ts
  packages/maps/src/map/map.ts
  packages/maps/src/mapbox/map.ts
  packages/maps/src/maplibre/map.ts
  packages/maps/src/tmap/logo.css
  packages/maps/src/tmap/map.ts
  packages/maps/src/utils/BaseMapService.ts
  packages/maps/src/utils/amap/AMapBaseService.ts
  packages/site/.dumirc.ts
  packages/site/docs/api/experiment/canvas.zh.md
  packages/site/docs/api/other/canvas.en.md
  packages/site/docs/api/other/canvas.zh.md
  packages/site/examples/point/chart/demo/custom.js
Labels: feature, pr(feature)

#2346 chore: publish 2.21.0
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: ignore-for-release, pr(chore)

#2347 docs: 补充 marker cluster 文档 & active，select 交互 fix #969
  examples/demos/point/fill.ts
  packages/component/src/marker.ts
  packages/core/src/services/interaction/PickingService.ts
  packages/core/src/shaders/picking.frag.glsl
  packages/core/src/shaders/picking.vert.glsl
  packages/core/src/shaders/picking_uniforms.glsl
  packages/layers/src/plugins/PixelPickingPlugin.ts
  packages/site/docs/api/component/marker_layer.en.md
  packages/site/docs/api/component/marker_layer.zh.md
Labels: documentation, pr(documentation)

#2351 feat: 新增 3D 底图 demo
  dev-demos/gallery/map/demo/3d_base_map.tsx
  dev-demos/gallery/map/suspension-map.md
  package.json
  packages/site/.dumi/global.ts
  packages/site/docs/tutorial/quickstart.zh.md
  packages/site/examples/gallery/animate/demo/3d_base_map.js
  packages/site/examples/gallery/animate/demo/meta.json
  packages/site/package.json
Labels: feature, pr(feature)

#2354 fix: 修改 DistrictData demo 和文档
  packages/site/.dumi/pages/custom/docs/sdk.md
  packages/site/.dumi/pages/custom/docs/service.md
  packages/site/maptools/demo/index.tsx
  packages/site/maptools/demo/util.ts
  packages/site/package.json
Labels: bugfix, pr(fix)

#2356 docs: 修改 Leaflet 和 district-data 的gitHub地址
  packages/site/docs/api/map/leaflet.en.md
  packages/site/docs/api/map/leaflet.zh.md
  packages/site/maptools/component/Hero/index.tsx
Labels: documentation, pr(documentation)

#2359 feat: 图表图层支持非矩形范围
  examples/demos/raster/image_coord.ts
  examples/demos/raster/index.ts
  jest.config.ts
  packages/core/src/services/source/ISourceService.ts
  packages/layers/src/core/triangulation.ts
  packages/layers/src/image/__tests__/imageLayer.spec.ts
  packages/layers/src/raster/__tests__/raster.spec.ts
  packages/site/docs/api/source/image.en.md
  packages/site/docs/api/source/image.zh.md
  packages/site/examples/raster/image/demo/image-coord.js
  packages/site/examples/raster/image/demo/image.js
  packages/site/examples/raster/image/demo/meta.json
  packages/source/src/interface.ts
  packages/source/src/parser/image.ts
  packages/source/src/parser/json.ts
  packages/source/src/parser/raster.ts
  packages/source/src/parser/raster/ndi.ts
  packages/source/src/parser/raster/rgb.ts
  packages/source/src/parser/rasterRgb.ts
  packages/source/src/utils/util.ts
Labels: feature, pr(feature)

#2360 chore: 未初始化情况下 setdata
  examples/demos/bugfix/polygon.ts
  examples/demos/components/index.ts
  examples/demos/components/swipe.ts
  examples/demos/polygon/water.ts
  lerna.json
  package.json
  packages/component/package.json
  packages/component/src/control/swipe.ts
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/line/models/line.ts
  packages/layers/src/point/models/fill.ts
  packages/layers/src/polygon/models/fill.ts
  packages/map/package.json
  packages/maps/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/scene/src/index.ts
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
  packages/utils/src/index.ts
  packages/utils/src/worker-helper/index.ts
  packages/utils/src/worker-helper/worker-map.ts
  packages/utils/src/workers/commonFeatureFunc.ts
  packages/utils/src/workers/extrude_polyline.ts
  packages/utils/src/workers/index.ts
  packages/utils/src/workers/interface.ts
  packages/utils/src/workers/lineModel.ts
  packages/utils/src/workers/pointFillModel.ts
  packages/utils/src/workers/polygonFillModel.ts
  packages/utils/src/workers/triangulation.ts
Labels: ignore-for-release, pr(chore)

#2369 ci: 解决测试工程访问 gl 环境不一致
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  __tests__/unit/preset/environment.ts
  packages/renderer/__tests__/regl/attribute.spec.ts
  packages/renderer/__tests__/regl/elements.spec.ts
  packages/renderer/__tests__/regl/framebuffer.spec.ts
  packages/renderer/__tests__/regl/model.draw.spec.ts
  packages/renderer/__tests__/regl/model.spec.ts
  packages/renderer/__tests__/regl/model.uniform.spec.ts
  packages/renderer/__tests__/regl/renderer.spec.ts
  packages/renderer/__tests__/regl/texture.spec.ts
  packages/renderer/__tests__/regl/utils/create-context.ts
  packages/renderer/package.json
  packages/test-utils/package.json
  packages/test-utils/src/check-pixels.ts
  packages/test-utils/src/create-context.ts
  packages/test-utils/src/default-precision.ts
  packages/test-utils/src/gl-context.ts
  packages/test-utils/src/index.ts
  packages/test-utils/src/test-scene.ts
Labels: ignore-for-release
