Repository antvis/L7, pull requests merged in 2024-11, with the labels that each got.

#2630 feat: rasterTile support extent
  .changeset/thick-wombats-lie.md
  packages/core/src/services/source/ISourceService.ts
  packages/source/src/parser/raster-tile.ts
Labels: pr(feature)

#2631 chore: commit changeset
  .changeset/thick-wombats-lie.md
  packages/component/CHANGELOG.md
  packages/component/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/l7/CHANGELOG.md
  packages/l7/package.json
  packages/layers/CHANGELOG.md
  packages/layers/package.json
  packages/map/CHANGELOG.md
  packages/map/package.json
  packages/maps/CHANGELOG.md
  packages/maps/package.json
  packages/renderer/CHANGELOG.md
  packages/renderer/package.json
  packages/scene/CHANGELOG.md
  packages/scene/package.json
  packages/source/CHANGELOG.md
  packages/source/package.json
  packages/test-utils/CHANGELOG.md
  packages/test-utils/package.json
  packages/three/CHANGELOG.md
  packages/three/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
Labels: ignore-for-release

#2636 fix: scale domain when default undefined
  .changeset/heavy-glasses-compete.md
  packages/layers/src/plugins/FeatureScalePlugin.ts
Labels: pr(bugfix)

#2635 fix: GeoJsonVT 瓦片中文文档表格错乱
  site/docs/api/tile/geojsonvt_tile_layer.zh.md
Labels: pr(bugfix)

#2638 docs: format table style
  site/docs/api/tile/geojsonvt_tile_layer.zh.md
Labels: pr(documentation)
