Repository antvis/L7, pull requests merged in 2024-05, with the labels that each got.

#2446 fix: 修复 LayerPopup followCursor 默认值问题
  examples/demos/components/index.ts
  examples/demos/components/layerPopup.ts
  packages/component/src/popup/layerPopup.ts
Labels: bugfix, pr(fix)

#2447 fix: device 渲染模式下 setData 时不生效
  examples/demos/bugfix/index.ts
  examples/demos/bugfix/polygon.ts
  examples/demos/bugfix/set-data.ts
  packages/renderer/src/device/DeviceModel.ts
Labels: bugfix, pr(fix)

#2448 refactor: 移除 TAA 算法后处理抗锯齿逻辑
  packages/core/src/inversify.config.ts
  packages/core/src/services/camera/CameraService.ts
  packages/core/src/services/camera/ICameraService.ts
  packages/core/src/services/config/ConfigService.ts
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/renderer/passes/TAAPass.ts
  packages/core/src/shaders/post-processing/blend.glsl
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/utils/multiPassRender.ts
Labels: pr(refactor)

#2455 chore:修复文档map.leaflet文案错误
  site/docs/api/map/leaflet.zh.md
Labels: ignore-for-release, pr(chore)

#2453 fix: mapbox 下部分面数据图层绘制异常
  .changeset/tiny-seas-camp.md
  examples/demos/bugfix/index.ts
  examples/demos/bugfix/muti-polygon.ts
  packages/layers/src/core/shape/extrude.ts
  packages/layers/src/core/triangulation.ts
  packages/layers/src/core/utils.ts
  packages/utils/src/geo.ts
Labels: bugfix, pr(fix)

#2456 docs: 从示例中移除风场图层
  site/.dumirc.ts
  site/examples/gallery/animate/delete/wind.js
  site/examples/gallery/animate/demo/meta.json
  site/examples/wind/basic/demo/meta.json
  site/examples/wind/basic/demo/wind.js
  site/examples/wind/basic/index.en.md
  site/examples/wind/basic/index.zh.md
Labels: documentation, pr(documentation)

#2457 feat: 新增 Popup 支持更新 className 和 style
  .changeset/curly-ligers-tap.md
  examples/demos/components/index.ts
  examples/demos/components/popup.ts
  packages/component/src/popup/popup.ts
Labels: pr(feature), feature

#2460 chore: add changeset
  .changeset/eighty-oranges-search.md
  .changeset/grumpy-tables-dream.md
Labels: ignore-for-release

#2458 fix: use antialias option in webgl
  __tests__/integration/snapshots/Gallery_fujian.png
  __tests__/integration/snapshots/Line_arc.png
  __tests__/integration/snapshots/Line_arc_plane.png
  __tests__/integration/snapshots/Line_dash.png
  __tests__/integration/snapshots/Line_flow.png
  __tests__/integration/snapshots/Mask_single.png
  __tests__/integration/snapshots/Point_column.png
  __tests__/integration/snapshots/Polygon_extrude.png
  package.json
  packages/layers/package.json
  packages/renderer/src/device/index.ts
Labels: pr(bugfix), bugfix

#2462 chore: 移除 d3-array 版本锁定
  package.json
  packages/layers/package.json
Labels: ignore-for-release

#2464 chore: 官网 Loading 组件丢失问题
  site/.dumi/pages/404.tsx
  site/.dumi/theme/slots/Loading.tsx
  site/.dumirc.ts
Labels: ignore-for-release

#2470 chore: 官网 dumi 锁定至 2.2.17
  site/.dumi/pages/404.tsx
  site/.dumi/theme/slots/Loading.tsx
  site/.dumirc.ts
  site/package.json
Labels: ignore-for-release

#2471 fix: use stencil.func.ref for each pipeline
  __tests__/integration/mask.spec.ts
  __tests__/integration/snapshots/Mask_multi.png
  __tests__/integration/snapshots/Point_billboard.png
  __tests__/integration/snapshots/Point_fill_image.png
  __tests__/integration/snapshots/Point_text.png
  examples/demos/mask/multi.ts
  packages/renderer/src/device/DeviceModel.ts
Labels: pr(bugfix)

#2473 chore: add changeset
  .changeset/proud-flies-change.md
Labels: ignore-for-release

#2474 fix: mapbox 线图层的贴图变形
  .changeset/clean-beers-try.md
  __tests__/integration/snapshots/Line_arc.png
  __tests__/integration/snapshots/Line_arc3D.png
  __tests__/integration/snapshots/Line_normal.png
  __tests__/integration/snapshots/Line_simple.png
  __tests__/integration/snapshots/Line_wall.png
  __tests__/integration/snapshots/Mask_multi.png
  __tests__/integration/snapshots/Mask_single.png
  __tests__/integration/snapshots/Point_billboard.png
  __tests__/integration/snapshots/Point_column.png
  __tests__/integration/snapshots/Point_fill_image.png
  __tests__/integration/snapshots/Point_text.png
  __tests__/integration/snapshots/Polygon_extrude.png
  __tests__/integration/snapshots/Polygon_extrusion.png
  __tests__/integration/snapshots/Polygon_fill.png
  examples/demos/gallery/vari-flight.ts
  packages/core/src/shaders/projection.glsl
  packages/layers/src/line/shaders/arc/line_arc_vert.glsl
  packages/layers/src/line/shaders/flow/flow_line_vert.glsl
  packages/layers/src/line/shaders/greatCircle/line_arc_great_circle_vert.glsl
Labels: pr(bugfix)

#2490 fix: raster with luminance in webgl1
  packages/renderer/src/device/DeviceTexture2D.ts
Labels: pr(bugfix)

#2493 docs: district-data 下架 wgs84 说明和导出
  site/.dumi/pages/custom/docs/sdk.md
  site/.dumi/pages/custom/docs/service.md
  site/maptools/demo/index.tsx
Labels: pr(documentation)

#2500 fix: 修复热力蜂窝图层渲染空白
  .changeset/honest-schools-relate.md
  __tests__/integration/snapshots/heatmap_grid.png
  __tests__/integration/snapshots/heatmap_hexagon.png
  examples/demos/heatmap/grid.ts
  examples/demos/heatmap/hexagon.ts
  examples/utils/scene.ts
  packages/layers/src/heatmap/models/hexagon.ts
Labels: pr(bugfix)

#2509 fix: 无地图与 MapLibre 模式移动 Marker 出错
  .changeset/five-singers-rush.md
  examples/demos/components/marker.ts
  packages/component/src/control/mouseLocation.ts
  packages/component/src/marker.ts
Labels: pr(bugfix)

#2511 fix: 在 WebGL2 拾取事件冒泡延迟问题
  .changeset/polite-apples-rule.md
  packages/core/src/services/interaction/PickingService.ts
  packages/core/src/services/renderer/passes/PixelPickingPass.ts
  packages/renderer/src/device/index.ts
Labels: pr(bugfix)

#2513 fix: 天地图 setCenter 方法缺失
  .changeset/rude-crabs-cheer.md
  examples/main.tsx
  examples/utils/scene.ts
  packages/maps/src/tdtmap/map.ts
Labels: pr(bugfix)

#2507 refactor: remove regl render mode
  .changeset/brave-nails-wave.md
  examples/constants.ts
  examples/main.tsx
  examples/types.ts
  packages/core/src/services/config/IConfigService.ts
  packages/renderer/__tests__/index.spec.ts
  packages/renderer/package.json
  packages/renderer/src/DeviceAttribute.ts
  packages/renderer/src/DeviceBuffer.ts
  packages/renderer/src/DeviceCache.ts
  packages/renderer/src/DeviceElements.ts
  packages/renderer/src/DeviceFramebuffer.ts
  packages/renderer/src/DeviceModel.ts
  packages/renderer/src/DeviceRendererService.ts
  packages/renderer/src/DeviceTexture2D.ts
  packages/renderer/src/constants.ts
  packages/renderer/src/index.ts
  packages/renderer/src/regl/ReglAttribute.ts
  packages/renderer/src/regl/ReglBuffer.ts
  packages/renderer/src/regl/ReglElements.ts
  packages/renderer/src/regl/ReglFramebuffer.ts
  packages/renderer/src/regl/ReglModel.ts
  packages/renderer/src/regl/ReglRenderbuffer.ts
  packages/renderer/src/regl/ReglTexture2D.ts
  packages/renderer/src/regl/constants.ts
  packages/renderer/src/regl/index.ts
  packages/renderer/src/utils/HashMap.ts
  packages/renderer/src/utils/pipeline.ts
  packages/renderer/src/utils/typedarray.ts
  packages/renderer/src/utils/webgl.ts
  packages/scene/src/index.ts
Labels: V3
