Repository antvis/L7, pull requests merged in 2024-01, with the labels that each got.

#2233 fix: 修正L7Plot官网图表示例按钮跳转链接
  packages/component/src/control/layerSwitch.ts
  packages/site/site/pages/index.zh.tsx
Labels: bugfix

#2235 chore: publish 2.20.13
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: ignore-for-release, pr(chore)

#2245 chore: add threejs demo
  packages/site/examples/engine/three/demo/basic_geometry.js
  packages/site/examples/engine/three/demo/meta.json
Labels: ignore-for-release, pr(chore)

#2251 chore: update threejs demo
  packages/site/examples/engine/three/demo/basic_geometry.js
  packages/site/examples/engine/three/demo/meta.json
Labels: ignore-for-release, pr(chore)

#2258 提升瓦片图层性能
  __tests__/e2e/snapshots/Tile_vector.png
  examples/demos/tile/vector.ts
  examples/demos/webgpu/perf-animate.ts
  packages/renderer/package.json
  packages/renderer/src/device/DeviceCache.ts
  packages/renderer/src/device/DeviceModel.ts
  packages/renderer/src/device/index.ts
Labels: bugfix, 3.0

#2262 支持 Raster Layer 在 WebGPU 下的渲染
  .npmrc
  examples/demos/bugfix/color.ts
  examples/demos/point/fill.ts
  examples/demos/point/image.ts
  examples/demos/point/text.ts
  examples/demos/tile/index.ts
  examples/demos/tile/perf.ts
  examples/demos/webgpu/heatmap_grid.ts
  examples/demos/webgpu/heatmap_grid3d.ts
  examples/demos/webgpu/heatmap_normal.ts
  examples/demos/webgpu/index.ts
  examples/demos/webgpu/line_normal.ts
  examples/demos/webgpu/perf-animate.ts
  examples/demos/webgpu/perf.ts
  examples/demos/webgpu/point_column.ts
  examples/demos/webgpu/point_fill.ts
  examples/demos/webgpu/point_image.ts
  examples/demos/webgpu/point_text.ts
  examples/demos/webgpu/polygon_extrude.ts
  examples/demos/webgpu/polygon_fill.ts
  examples/demos/webgpu/polygon_texture.ts
  examples/demos/webgpu/polygon_water.ts
  examples/demos/webgpu/raster_dem.ts
  examples/demos/webgpu/raster_image.ts
  examples/demos/webgpu/raster_multiband.ts
  examples/demos/webgpu/raster_ndvi.ts
  examples/demos/webgpu/raster_tiff.ts
  packages/layers/src/core/TextureService.ts
  packages/layers/src/raster/models/raster.ts
  packages/layers/src/raster/models/rasterRgb.ts
  packages/layers/src/raster/shaders/raster/raster_2d_frag.glsl
  packages/layers/src/raster/shaders/raster/raster_2d_vert.glsl
  packages/layers/src/raster/shaders/rgb/raster_rgb_frag.glsl
  packages/layers/src/raster/shaders/terrain/terrain_rgb_frag.glsl
  packages/layers/src/raster/shaders/terrain/terrain_rgb_vert.glsl
  packages/renderer/package.json
  packages/renderer/src/device/DeviceModel.ts
  packages/renderer/src/device/DeviceTexture2D.ts
  packages/renderer/src/device/utils/typedarray.ts
Labels: bugfix, 3.0

#2259 chore: test loaded 完成后截图
  .github/workflows/build_test.yml
  .npmrc
  .yarnrc
  __tests__/e2e/snapshots/Line_arc.png
  __tests__/e2e/snapshots/Line_dash.png
  __tests__/e2e/snapshots/Line_flow.png
  __tests__/e2e/snapshots/Polygon_texture.png
  __tests__/e2e/snapshots/Raster_tiff.png
  __tests__/e2e/tests.ts
  examples/demos/bugfix/index.ts
  examples/demos/bugfix/touchend.ts
  examples/demos/components/control.ts
  examples/demos/components/index.ts
  examples/demos/gallery/fujian.ts
  examples/demos/heatmap/grid.ts
  examples/demos/heatmap/hexagon.ts
  examples/demos/heatmap/normal.ts
  examples/demos/index.ts
  examples/demos/line/arc.ts
  examples/demos/line/arc_plane.ts
  examples/demos/line/dash.ts
  examples/demos/line/flow.ts
  examples/demos/line/normal.ts
  examples/demos/polygon/ocean.ts
  examples/demos/polygon/texture.ts
  examples/demos/polygon/water.ts
  examples/demos/raster/dem.ts
  examples/demos/raster/image.ts
  examples/demos/raster/multiband.ts
  examples/demos/raster/ndvi.ts
  examples/demos/raster/tiff.ts
  examples/demos/tile/index.ts
  examples/demos/tile/usa.ts
  examples/demos/tile/vector.ts
  examples/demos/tile/world.ts
  examples/demos/webgpu/index.ts
  package.json
  packages/core/package.json
  packages/core/src/services/interaction/InteractionService.ts
  packages/core/src/services/interaction/PickingService.ts
  packages/core/src/services/scene/ISceneService.ts
  packages/core/src/services/scene/SceneService.ts
  packages/layers/src/plugins/ShaderUniformPlugin.ts
  packages/layers/src/tile/core/BaseLayer.ts
  packages/maps/src/amap2/map.ts
  packages/maps/src/bmap/map.ts
  packages/maps/src/tmap/map.ts
  packages/site/docs/api/common/layer/mouse_event.zh.md
Labels: ignore-for-release, pr(chore)

#2272 feat: add google map
  examples/demos/index.ts
  packages/maps/package.json
  packages/maps/src/gmap/index.ts
  packages/maps/src/gmap/logo.css
  packages/maps/src/gmap/map.ts
  packages/maps/src/gmap/maploader.ts
  packages/maps/src/index.ts
  packages/maps/typings/index.d.ts
Labels: feature, pr(feature)
