Repository antvis/L7, pull requests merged in 2024-02, with the labels that each got.

#2297 fix: 修复 LayerPopup 因 Popup setOptions 误触发 show() 的问题
  packages/component/src/popup/layerPopup.ts
Labels: bugfix, pr(fix)

#2298 fix: mvt tile pick fix #2273
  examples/demos/heatmap/normal.ts
  examples/demos/raster/dem.ts
  examples/demos/tile/perf.ts
  packages/core/src/services/interaction/PickingService.ts
  packages/core/src/services/layer/IStyleAttributeService.ts
  packages/core/src/services/layer/LayerService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/core/LayerPickService.ts
  packages/layers/src/heatmap/index.ts
  packages/layers/src/raster/index.ts
  packages/layers/src/utils/rampcolor_legend.ts
  packages/site/docs/api/common/layer/layer_event.zh.md
  packages/site/docs/api/common/layer/layer_interaction.zh.md
  packages/site/examples/gallery/basic/demo/meta.json
  packages/site/examples/gallery/basic/demo/point.js
  packages/site/examples/gallery/basic/demo/swipe.ts
  packages/site/examples/line/path/demo/line_blur.js
  packages/site/examples/line/path/demo/meta.json
  packages/source/src/parser/geojson.ts
  packages/source/src/source/vector.ts
Labels: bugfix, pr(fix)

#2305 chore: publish 2.20.17
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: ignore-for-release, pr(chore)

#2304 feat: 同步地图demo
  dev-demos/component/sync-scene/helper.ts
  dev-demos/component/sync-scene/syncScene.tsx
  dev-demos/component/sync-scene/syncSene.md
  dev-demos/component/sync-scene/types.ts
  packages/site/examples/component/control/demo/meta.json
  packages/site/examples/component/control/demo/syncScene.ts
Labels: feature, pr(feature)

#2310 chore: publish 2.20.18
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: ignore-for-release, pr(chore)

#2314 chore: publish 2.20.19
  lerna.json
  packages/component/package.json
  packages/core/package.json
  packages/l7/package.json
  packages/layers/package.json
  packages/map/package.json
  packages/maps/package.json
  packages/renderer/package.json
  packages/scene/package.json
  packages/site/package.json
  packages/source/package.json
  packages/test-utils/package.json
  packages/three/package.json
  packages/utils/package.json
Labels: ignore-for-release, pr(chore)

#2317 chore: use getViewportSize 获取 画布大小
  .travis.yml
  examples/demos/bugfix/index.ts
  examples/demos/bugfix/polygon.ts
  examples/demos/polygon/fill.ts
  examples/demos/tile/vector.ts
  packages/component/__tests__/popup.spec.ts
  packages/core/src/services/interaction/PickingService.ts
  packages/core/src/services/layer/LayerService.ts
  packages/layers/src/core/BaseLayer.ts
  packages/layers/src/core/__tests__/layer.event.spec.ts
  packages/layers/src/polygon/__tests__/polygon_layer.spec.ts
  packages/layers/src/tile/interaction/getRasterData.ts
  packages/layers/src/tile/utils/utils.ts
  packages/map/__tests__/map.init.spec.ts
  packages/map/__tests__/map.spec.ts
  packages/maps/src/map/map.ts
  packages/scene/__tests__/index.spec.ts
  packages/test-utils/src/create-context.ts
  packages/test-utils/src/test-scene.ts
Labels: ignore-for-release, pr(chore)
